### ISSUE TITLE
version info also pops up from clicking in some corner place

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/oscm#10]
_From @SylviaDehn on October 19, 2017 11:59_

[Version] OSCM 17.4.0 2017/10/19
Docker image with TomEE

[How to reproduce]
1. check version of app software
http://estst1.intern.est.fujitsu.com:8880/oscm-app/

[Expected result]
clicking on OSCM on the left gives me version info

[Observed result]
I do not know where to click, cursor does not change shape

_Copied from original issue: servicecatalog/development#873_

**Comment by DawidCh** [comment]
_From @kwodzynski on October 23, 2017 8:45_

You need to click on the right of "USER ID: name_of_logged_user" (right top corner). The place to show version info should be standardized and always be displayed after click on OSCM logo.
The problem occurs on each controller.

**Comment by grubskim** [comment]
Fixed header to be clickable and to change cursor to pointer.

**Comment by kwodzynski** [comment]
Tested on Docker image 17.5 2017/11/03 - Version info is shown after click on "Open Service Catalog Manager" logo. But right top corner is still clickable. We can display version info after click on two above places. Is it good behavior? In portal only logo is clickable.
Reopen, please close if the behavior is good.

**Comment by Crystalzord** [comment]
Tested on 17.9 2019/02/21 - this issue does not appear anymore. I can see that only left top corner with "Open Service Catalog Manager" logo is cliclable now.
