### ISSUE TITLE
It is not possible to change Controller_org_ID in the App-controler-configuration

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#100]
[Build]
docker 17.7 2018/06/11

[Steps to reproduce]
 log in to App-Controller-configuration xxx:8881/oscm-app/
 edit  "Organization ID"  to a different organization "ab6b5473"
log in to AWS-Controler xxx:8881/oscm-app-aws
    
[Expected result]
should be work
    
[Observed result]
 is not possible

[Details]
In the "bssapp" db the BSS_USER_ID for ess.aws is administrator, but this is not a  user of the organisation "ab6b5473"

**Comment by GoebelL** [comment]
The steps required to change the reponsible organization should be same for all controllers. 
This is as described in OSIntegration.pdf, 4.5 Changing the Responsible Organization:

change the technology provider organization responsible for the IaaS service
controller using the Web interface of APP:

1. In a Web browser, access the Web interface (base URL) of APP. The access URL has the following format:
https://<hostname.fqdn>:<port>/oscm-app
<hostname.fqdn> is the name and the fully qualified domain name of the machine where the
oscm-app container has been deployed, <port> is the port to address the machine (default:
8881), oscm-app is the default context root of APP and cannot be changed.
2. Log in with the ID and password of the user specified for BSS_USER_KEY in the configuration
settings for APP or as another administrator of the same organization.
3. Specify the technology provider organization for the service controller, ess.....
4. Save the settings.
5. Make sure that the configuration settings for the service controller are updated.
Any technology manager registered for the technology provider organization you specified
can log in to the graphical user interface for updating the controller configuration settings (see
above). _At least the ID and password of the user to be used for accessing OSCM must be
changed_ in the controller configuration settings.

**Comment by GoebelL** [comment]
Platform Operator should always have access to controller UIs. Check issue #23.

**Comment by GoebelL** [comment]
@marcin-fest (or @fest-floreks?) Please check the documented steps listed above. If changes are required, it'll be nice if you write the details and assign this to @gertipoppel for adaption.

**Comment by ghost** [comment]
I am looking at it now. I have just finished to test VMware controller and everything seems to work correctly - after changing Organization ID I am able to login with new user and with main administrator:

![obraz](https://user-images.githubusercontent.com/40793285/42440389-ec670740-8365-11e8-9391-f91ddf690316.png)

![obraz](https://user-images.githubusercontent.com/40793285/42440467-2238c5ca-8366-11e8-8bdd-6532811dde23.png)

![obraz](https://user-images.githubusercontent.com/40793285/42440499-385664ca-8366-11e8-82ee-76ea93367ac6.png)

Now I will test it OpenStack controller.

On the first image you can see a bug, that I will report soon.

**Comment by ghost** [comment]
When testing AWS and OpenStack controllers I am failing to login as new user and as an administrator. I will investigate it:

![obraz](https://user-images.githubusercontent.com/40793285/42445837-af63722a-8374-11e8-8fcc-4d342088957f.png)

**Comment by ghost** [comment]
Okay, so I have investigated it with @kowalczyka it seems that @elfriedegoetz steps are incorrect considering current implementation.

Correct steps to change user at the moment are:

Login to specific controller's UI with user that is able to view it, i.e. https://10.140.18.123:8881/oscm-app-aws/ for AWS controller. After logging in you can change user credentials:

![obraz](https://user-images.githubusercontent.com/40793285/42448425-64d35578-837d-11e8-9543-15597c6083fe.png)

After saving this configuration you have to go back to https://10.140.18.123:8881/oscm-app/ and modify `Organization ID`:

![obraz](https://user-images.githubusercontent.com/40793285/42448510-aa8690e4-837d-11e8-93c7-c9e50d0d69f9.png)

After changes in these two locations you should be able to login with the new user from another organization. It is important that:

- data in oscm-app-* and oscm-app has to be in sync
- in order to keep the data in sync you have to start updates with changes in oscm-app-* UI

I think this should be improved and all this data should be changeable from oscm-app if there is no functional/client requirement saying otherwise.

**Comment by ghost** [comment]
PTAL @elfriedegoetz @GoebelL

**Comment by ghost** [comment]
And there is one more issue - there is no way to change user ID, key and password for VMware controller in the UI it seems. At least, from /oscm-app-vmware endpoint.

**Comment by GoebelL** [comment]
@marcin-fest 
Thanks for the analysis. I can also confirm that the organization is changeable with the described procedure. Thus it's working as designed. 

>there is no way to change user ID, key and password for VMware controller in the UI it seems. At least, >from /oscm-app-vmware endpoint.

That's true. @elfriedegoetz has already reported this as issue #122. There is a fix in progress by @xusuest.

This issue is closed.

**Comment by elfriedegoetz** [comment]
It is not possible to change the Controler_ID for vmware. see Bug 122

**Comment by elfriedegoetz** [comment]
It is not possible to Change the Controller ID for aws:
step1: Install docker with sample data
step2: Login to APP with administrator  passwoed admin123
step3: Change Organisation ID for ess.aws to PLATFORM_OPERATOR
step4: click save
step5: Login to aws Controller with supplier@adfs.com  Password supplier
step6: click  save
error message: *** User does not belong to the correct organization.
![awscontroller](https://user-images.githubusercontent.com/15209605/44463733-368d9e00-a608-11e8-8941-67f72ecf3bbb.PNG)

**Comment by GoebelL** [comment]
This works as expected because supplier@adfs.com is not member of PLATFORM_OPERATOR.

**Comment by GoebelL** [comment]
If you want to change the organization you should  proceed as described in the documentation - see above.

**Comment by elfriedegoetz** [comment]
The behavior is strange, therefore it is not easy to test and describe.
I suspect that the data is not always read from the database.
I have tested again for vmware Controller.

step1: Install docker with sample data
 step2: Login to APP with "administrator password admin123"
 step3: Change Organisation ID for ess.vmware to PLATFORM_OPERATOR
 step4: click save
 step5: Login to vmware Controller with "administrator password admin123"
step6: change BSS_USER_ID to administrator  1000 admin123
 step7: click save
works fine

now I Change the Organisation ID back to "959c9bf7"

 step1: Login to APP with "administrator password admin123"
 step2: Change Organisation ID for ess.vmware to  959c9bf7
 step3: click save
 step4: Login to vmware Controller with "administrator password admin123"
   Login is not possible for administrator. 
   Login for "supplier@adfs.com" Password supplier works fine.

note: I tested with Firefox private mode to make sure that nothing is stored in the browser

**Comment by elfriedegoetz** [comment]
tha same for aws controller

**Comment by elfriedegoetz** [comment]
sorry, above I mean Organisation ID for the Controller and NOT Controller ID

**Comment by kowalczyka** [comment]
If you change the organization id so that not PLATFORM_OPERATOR is used, the administrator (PLATFORM_OPERATOR organization) will no longer be able to login to controller UI

**Comment by elfriedegoetz** [comment]
Okay: It works as described  from Goebel above. (see  commented on Jun 22 )
But Platform Operator should always have access to controller UIs.  see comment from Goebell above.
I am not sure if this is still necessary.

**Comment by ghost** [comment]
> But Platform Operator should always have access to controller UIs

Are you 100% sure about it? 

> see comment from Goebell above.

Which comment?

**Comment by elfriedegoetz** [comment]
GoebelL commented on Jun 26 or it ther a misunderstanding?

**Comment by ghost** [comment]
> GoebelL commented on Jun 26 or it ther a misunderstanding?

Okay, in my opinion we should create separate issue for it and close this one.

**Comment by GoebelL** [comment]
Lots of duplicate reporting. Please check the open issues before filing new ones.

> in my opinion we should create separate issue for it and close this one.

Not needed. The missing access for the platform administrator is reported in issue #23. This one is closed.
