### ISSUE TITLE
Fix OIDC Webtests

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1016]
**Summary**
Fix and improve Webtests

**Details**
- Identify current issues on OIDC webtest and 
- collect improvement ideas to avoid them in future (e.g. stabilize with fix paths or ids, improving logging / failure reporting)   
- ignore test temporarily where needed
- Fix tests to green again
- Create task issue on github of collected ideas for webtest improvements 

**Acceptance criteria**
- [ ] Temporary Ignores have been removed
- [ ] Tests are green
- [ ] Issue with improvement ideas on GitHub

**Additional context**
Ask me

**Comment by Piotr-K8i** [comment]
From what I see, UI tests have not passed since Friday for Internal mode

![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/f061890c-3872-4eb1-91d3-1f1ab2eb8ef3)

**Comment by GoebelL** [comment]
OIDC Webtests are green again. Thanks @KabacinskiPiotr  and @cworf91
