### ISSUE TITLE
Branding not loaded on first access

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1029]
**Version Info**
v19, latest 2020-07-17

**Describe the bug**
Branding files are not loaded imediatelly.

**How to Reproduce**
1. Download branding package 
2. Costomize bootstrap main color in '(branding)/customBootsrap/scss/_myvariables.scss' to $red
3. Compile the package and deploy it on the host '/docker/config/brandings/...'
4. Login to the oscm-portal and set respective branding CSS URL for a marketplace 
5. Access the custom branded marketplace

**Expected behavior**
Marketplace is loaded with custom branding and buttons appear red now.

**Observed behavior**
Marketplace is loaded with custom branding but the buttons still appear default green. First after reloading the page they turn to red. After logout again they appear first green and only after reloading red.

**Screenshots**
TBD

**Additional context**
Ask me.

**Comment by GoebelL** [comment]
How about this issue? Can you fix this?

**Comment by farmakiG** [comment]
Yes sure, look at the commits.
