### ISSUE TITLE
Investigate Improvment of Integration Tests

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm#1035]
**Summary**
When the integration tests are failing, it´s difficult to fix them, duo to bad error messages. Therefore, it should be examined whether it is possible to improve the error messages.

**Details**
A suitable option to improve the error messages is to log the http response. Therefore, it should be examined if selenium supports the possibility to log the respons. 

**Acceptance criteria**
[ ] A possability to integrate this improvment with a effort estimation

**Comment by cworf91** [comment]
It seems that Selenium doesn´t provide any posibility to log the http traffic. Anyway it seems that there is a workaround for it. It´t possible to activate the logging for the browser and log there the http trafic. 
https://stackoverflow.com/questions/6509628/how-to-get-http-response-code-using-selenium-webdriver

**Comment by GoebelL** [comment]
The workaround is ok for on-demand investigation outside of CI environment. This is suffient for now. Let's revisit this if issues increase in CI. For the time being the tests are stable.
