### ISSUE TITLE
Cannot edit trigger definition

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1041]
**Version Info**
latest v19

**Describe the bug**
Created trigger definition can be edited not deleted via marketplace UI

**How to Reproduce**
1. Login to marketplace UI as Supplier
2. In **Account > Processes* create a trigger definition
3. Try to edit with the edit pen

**Observed behavior**
Nothing happens. No errors, no dialog.

**Expected behavior**
A popup dialog opens to edit or delete the trigger description.

**Screenshots**
NA

**Additional context**
NA

**Comment by GoebelL** [comment]
I notice that sometimes it's working correctly. But it don't know the conditions. :-(

**Comment by Piotr-K8i** [comment]
I tested the application as a supplier and administrator on Opera, Firefox, Chrome, Explorer and Edge, all of these browsers work fine. The trigger can be edited and its status is remembered. Just in case, I added UI tests to creating and editing trigger. I am closing the task
