### ISSUE TITLE
Repository webhooks are misconfigured

### ISSUE THREAD

**Issue by pkaminski** [servicecatalog/oscm#105]
Hey folks, I see `servicecatalog/oscm` sending a bunch of incorrectly-signed webhooks to reviewable.io.  It looks like the repo was never connected in Reviewable so I'm guessing somebody (perhaps @DawidCh?) tried to create the webhook manually for some reason.  This won't work -- could you please remove the webhook and connect the repo via https://reviewable.io/repositories if you'd like to use Reviewable?  Thanks!

**Comment by GoebelL** [comment]
This has been fixed. Thanks for the note.
