### ISSUE TITLE
Tomcat update

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#1050]
**Summary**
Tomcat should be updated to the latest stable version

**Details**
The Apache Tomcat team announces that support for Apache Tomcat 7.0.x will end on 31 March 2021.

**Acceptance criteria**
- Tomcat version 9 or higher
- Applying HTTP/2 network protocol 
- All Tomcat settings should be saved or their equivalents applied

**Additional context**
N/A

**Comment by GoebelL** [comment]
Apache Tomcat 7.0.x is not used in OSCM.
