### ISSUE TITLE
Set default Provisioning service URL

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#1056]
**Summary**
The current definition of technical service is too complex for new users. 

**Details**
Provisioning service URL field value should not be marked as requirement. If the user does not enter any value, the default value should be entered 
"http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousProvisioningProxy?wsdl"

**Acceptance criteria**
It is possible to define the service without specifying the value of the "Provisioning service URL" field

**Additional context**
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/5fd8140b-bd22-4e49-a9ab-2faaab4a2d14)

**Comment by GoebelL** [comment]
Easy setup will be provided with [sample data](https://github.com/servicecatalog/oscm-approval/issues/46) planned for this for this sprint.
