### ISSUE TITLE
Set default Target URL

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#1057]
**Summary**
The current definition of process trigger is too complex for new users.

**Details**
- Target URL field value should not be marked as requirement. If the user does not enter any value, the default value should be entered
 "http://oscm-app:8880/approval/ApprovalNotificationService?wsdl"
- Checkbox "Suspends the execution of the process" should be checked by default

**Acceptance criteria**
Precise and detailed conditions under which a feature request is considered to be completed.

**Additional context**
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/c2cba154-4dd4-4d4c-8f75-e93ff838535d)

**Comment by GoebelL** [comment]
Although I do see a little usability plus, I am not in favor for implementing this request. 
The process trigger interface shouldn't be tied with this particular approval tool. It's designed as an open framework that allows integration of any default or user provided applications at any location, that implement the notification service endpoint. The oscm-portal must not have dependency and therefore no 'awareness' of oscm-app existence. I rather can image vice versa: In a clean theory the oscm-app could offer endpoint URLs to the portal by registering them somehow to the portal. But in terms of cost-value relation this is not reasonable at all (little convenience improvement for administrators on a setup operation that applies one time only).
