### ISSUE TITLE
Description for deleting a container is wrong

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#106]
Operator's Guide, page 15:
"To delete a container:
docker-compose rm -f docker-compose-oscm.yml <container-name>"

I guess this is wrong. It should be
"docker-compose -f docker-compose-oscm.yml rm <container-name>"

Otherwise the -f is treated as sub command option of rm (meaning "force"), and the docker-compose command will look for the default docker-compose yaml file and ignore the specified one. 

Please check also other manuals.

**Comment by gertipoppel** [comment]
I have changed the doc accordingly. Will be available on Thursday, 28.
