### ISSUE TITLE
Broken modal window layout

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1064]
**Version Info**
latest

**Describe the bug**
Modal window is too large

**How to Reproduce**
E.g.
1. Select a subscription from marketplace 
2. Edit subscription 
3. Click terminate to remove subscription
4. Confirmation modal panel pops up

**Observed behavior**
Dialog has full screen hight. This behavior is new and happens to all modal dialogs in my marketplace - not only to the confirmation panel (!)

**Expected behavior**
 Dialog is proper sized to fit the content

**Screenshots**
![image](https://user-images.githubusercontent.com/14805690/92333281-90911d00-f084-11ea-8080-7c6d41afcf6a.png)

**Additional context**
Fix required by 10.09.2020

**Comment by GoebelL** [comment]
This has been fixed by recent changes and doesn't appear any longer.

**Comment by farmakiG** [comment]
Reopened because modal dialogs still appear fullscreen.
