### ISSUE TITLE
Update technical service failed

### ISSUE THREAD

**Issue by DashThink** [servicecatalog/oscm#107]
Hi Team,

We have CTMG v17.3 with Technical service 'Vmware sync'. We created marketable service based on this technical service. Also we having multiple subscriptions on the same marketable service. Now we want to add one/two more parameters into the existing Technical service. We deactivated the marketable service and tried to import same technical service. But unfortunately we are getting below error. 

![image](https://user-images.githubusercontent.com/32571211/41851562-d76a959e-7877-11e8-9efc-3d0f6d7508fb.png)

Please suggest

**Comment by GoebelL** [comment]
Hi @DashThink 
As the error message says, technical service parameters cannot be not changed if the service is already in use. However, it _is_ possible to add single parameters, with active subscriptions, as long as those parameters are not impacting existing definitions. 
I am not clear which issue you are facing here. Can you give an example?

**Comment by DashThink** [comment]
Hi @GoebelL 

In the current scenario we have deactivated existing marketable service and tried to add one more parameter to Technical service. At the same time we face this issue. In simple words we need to add one more parameter into existing technical service.

**Comment by GoebelL** [comment]
We haven't faced any issues with adding parameters on existing services. We'd need more details about the present definition and about the parameters you try to add.

**Comment by GoebelL** [comment]
Any details? Does the issue still persist?
