### ISSUE TITLE
Sample Data for Reseller Marketing

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1088]
**Summary**
Add a reseller organization to the initial sample data.

**Details**
Make use of the partner model. Add a reseller organization with own reseller marketplace in the sample setup. The reseller has permissions to sell the supplier's sample service with a pro rata price model.

**Acceptance criteria**
When installing with `-SAMPLE_DATA=true`
- [ ] Reseller organization is created 
- [ ] Reseller administrator can login is successfully, with INTERNAL
- [ ] Reseller administrator can login is successfully, with OIDC
- [ ] Pro Rata Sample Service exists on the reseller's marketplace

**Additional context**
N/A

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-jenkinsscripts/pull/19
https://github.com/servicecatalog/oscm-dockerbuild/pull/275
