### ISSUE TITLE
Investigate cause of increasing disk consumption of UI Tests

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1090]
**Summary**
Investigate cause of increasing disk consumption of UI Tests.

**Details**
Lots of data is being accumulated in /var/lib/docker/devicemapper

**Acceptance criteria**
- [ ] Root cause found

**Additional context**
N/A

**Comment by Piotr-K8i** [comment]
@GoebelL ,
To tell you the truth, I have not found clear information why devicemapper uses so much disc, but below I attach steps that we can take to reduce disk consumption:

1. Create .dockerignore - Before the docker CLI sends the context to the docker daemon, it looks for a file named .dockerignore in the root directory of the context. If this file exists, the CLI modifies the context to exclude files and directories that match patterns in it. Details: [dockerignore](https://docs.docker.com/engine/reference/builder/#dockerignore-file )

2. Implement best practices for Dockerfiles [Best practices](https://www.docker.com/blog/intro-guide-to-dockerfile-best-practices/)

3. Move to Overlay2 storage driver ??? - The devicemapper storage driver is deprecated in Docker Engine 18.09, and will be removed in a future release. It is recommended that users of the devicemapper storage driver migrate to overlay2.
[Storage driver](https://docs.docker.com/storage/storagedriver/select-storage-driver/#docker-engine---community)
 [Evaluation](https://users.cs.fiu.edu/~raju/WWW/publications/amlcs2017/paper.pdf)
[Comparison](https://integratedcode.us/2016/08/30/storage-drivers-in-docker-a-deep-dive/)

**Comment by GoebelL** [comment]
The observed behavior looks to me more like a bug, either in our CI test setup or in docker itself. From your list, I suggest to do point 3. I am sure we will avoid this by swtiching the driver, and we also might get more insight into this topic.
