### ISSUE TITLE
Services in landing page are not sorted alphabetically.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1092]
**Version Info**
19.0

**Describe the bug**
The Marketable Services which appear in the landing page are displayed in date creation order (from the most recent to the oldest one). It would make more sense to display them alphabetically based on the Service title.

**How to Reproduce**
1. Create as supplier 1 three Services: Business Solution1, Business Solution3 and Business Solution 5.
2. Create as supplier 2 three more Services: BusinessSolution2, 4 and 6.
3. Publish them all to the same marketplace.
4. Now login to marketplace as any user. 

**Observed behavior**
The services are not displayed in alphabetical order but based on their order of creation.

**Expected behavior**
The services are displayed in alphabetical order.

**Screenshots**
If applicable, screenshots to help explain your problem.

**Additional context**
N/A.

**Comment by Piotr-K8i** [comment]
@farmakiG ,
You can change the way services are displayed in the admin panel. In the "Define featured services" tab, you have a choice:
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/0cde8405-6ea1-420a-8bc0-651165db8bf1)

**Comment by farmakiG** [comment]
Closed as clarified in above comment.
