### ISSUE TITLE
audit log not available

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/oscm#11]
_From @SylviaDehn on October 19, 2017 12:41_

[Version] OSCM 17.5.0 2017/10/19
Docker image with TomEE

[How to reproduce]
1. turn on audit log in configuration settings
2. carry out operations that are normally logged in audit log
3. as platform operator export audit log

[Expected result]
audit log is exported

[Observed result]
error shown: No audit log data available for export.

_Copied from original issue: servicecatalog/development#875_

**Comment by grubskim** [comment]
Fixed with [commit](https://github.com/servicecatalog/oscm/commit/e14d690fa99c6ee0c4fc4afc47f976bdab886dcc).

**Comment by kwodzynski** [comment]
Tested on 17.5 2017/11/29, It works as expected
