### ISSUE TITLE
Unable to add a values to an OperationParameter of type REQUEST_SELECT

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#1108]
**Version Info**
19.0

**Describe the bug**
The TechnicalServices.xsd file contains the operation definition but does not include the possibility to add a values to the OperationParameter
[TechnicalServices.xsd](https://github.com/servicecatalog/oscm/blob/master/oscm-serviceprovisioning/javares/TechnicalServices.xsd)

**How to Reproduce**
1. See TechnicalServices.xsd

**Observed behavior**
Unable to add a values to an Operation Parameter of type REQUEST_SELECT

**Expected behavior**
It is possible to define the value of the Request_SELECT operation parameter in the xml file

**Comment by GoebelL** [comment]
The bug is unclear for me and I doupt that it is valid. This feature is there for long time and schema definition has not changed. I suggest  you to look for examples with this type in our repo.

**Comment by GoebelL** [comment]
To handled with https://github.com/servicecatalog/oscm/issues/1095

**Comment by GoebelL** [comment]
This Bug is invalid. The values of REQUEST_SELECT operation parameters are to be provided by the service implementation. This work correctly as designed. See my comment in #1109.
