### ISSUE TITLE
After installing sample data, create marketplace results in Operation Failed.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1111]
**Version Info**
current master with OSCM_Pull_and_start

**Describe the bug**
Creation of Marketplace with name: MP1 results in Operation Failed message, and this even though marketplace MP1 does not exist yet.

**How to Reproduce**
1. Go to the "Create Marketplace" page.
2. Create Marketplace with name "MP1".

**Observed behavior**
Operation failed message.

**Expected behavior**
Success message for this particular case. 
In case marketplace cannot be saved in general, show Error message and not Operation failed.

**Screenshots**
![Screenshot_2020-11-02](https://user-images.githubusercontent.com/49904723/97867092-76cf2780-1d0d-11eb-80ce-a66ebfa407b2.png)

**Log file**
[system.log](https://github.com/servicecatalog/oscm/files/5475208/system.log)

**Additional context**
N/A.

**Comment by GoebelL** [comment]
Duplicate with #1112.
