### ISSUE TITLE
Columns in configuration settings table are not resizable

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1119]
**Version Info**
OSCM v19

**Describe the bug**
The editing of configuration settings in the UI is unhandy, having narrow input fields that can't be resized.

**How to Reproduce**
1. Log in as platform operator administrator
2. Landing on the configuration settings page check the table column for the value

**Expected behavior**
Value column has a propper default width and resizing is possible.

**Observed behavior**
Value column is too narrow while the key column is too wide. There is no justified need as there still unnecessary space right beneath the longest key name. Furthermore the width is fix so that the user can't adjust it. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14805690/98687776-6a307c00-236a-11eb-96ff-8f589ff70bf0.png)

**Additional context**
Ask me

**Comment by GoebelL** [comment]
I've built and deployed the fix by 2020-11-26. The resizing works well and also the columns have an appropriate width.
Just one thing to be improved, is that after pressing save the row height increases.
 
**How to Reproduce**
1. Log in as platform operator administrator
2. In the configuration settings page resize the table
3. click save

**Expected behavior**
Success message appears in the header and data is saved. The table does not change in any way. Row height and input alignment stays fix.

**Observed behavior**
Success message appears in the header and data is saved. The row height is increased to approximate 150% of original height. In this case the input fields still appear small and vertically wrong aligned.
After reloading the page the rows are back to normal.
![image](https://user-images.githubusercontent.com/14805690/100378767-0a95ca00-3014-11eb-99e3-b570a454606d.png)

**Comment by GoebelL** [comment]
I am using Chrome Version 86.0.4240.198

**Comment by Piotr-K8i** [comment]
**Describe the bug**
The alerts for an empty required field or the wrong value disappear after the form is submitted. The content is loaded 2 times, which extends the page loading time.

**How to Reproduce**
1. Open any page in the administrator portal
2. Submit form
3. Check network load requests

**Expected behavior**
Alerts should load and be visible. Content only needs to be uploaded once
