### ISSUE TITLE
Investigate Discount Billing

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1120]
**Summary**
Discounts for services provided by resellers are not taken into account by the billing.

**Details**
Discounts are customer-organization specific and therefore should be applied to all subscriptions to services, regardless if these are provided by suppliers or resellers.
However, it has been noticed that discounts for customers are applied only to Services provided by suppliers. Investigate if this is the correct behavior. Look if there are already implemented unit tests and IT tests regarding resellers.
Think of similar cases (for example for brokers) and check these cases too.
Notice that the info about the Discount is not only shown in the billing results, but also in the "Price model" tab for the Subscription configuration.

**Acceptance criteria**
- [ ] List of relevant test cases in billing unit tests and integration tests.
- [ ] Link to Past Issues/Bugs/requirements regarding Discounts.
- [ ] If it is a bug, plan a bug fix and correct Reseller guide (Discount section in Appendix).

**Additional context**
Similar cases for brokers etc.

**Comment by GoebelL** [comment]
There is no follow up on testing activities here since the partner model native billing use cases are out of scope for the next release.
