### ISSUE TITLE
VMWare custom tab connection fails

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1121]
**Version Info**
OSCM v19 latest (10/11/2020)

**Describe the bug**
While Shell Adapter custom tab happily provides instance and usage data, the custom tab for the VMware connector doesn't. As part of the custom tab framework the access to the content showing the instance details is protected with a crypted URL token. As I analyzed so far, the connection fails on oscm-app side, because the the [-> token check](https://github.com/servicecatalog/oscm-app/blob/master/oscm-app-common/src/main/java/org/oscm/app/common/ui/filter/AuthorizationFilter.java#L92) is negative.

**How to Reproduce**
1. Create a VMWare Service and subscribe it
2. Login to the OSCM marketplace showing the service offer
3. Open My Subscriptions view from the pull down menu in header bar
4. docker logs -f oscm-app
5. Access the custom tab

**Observed behavior**
The tab remains empty. Errors are logged when accessing the tab, but the messages and stacktraces are not very helpful here.  Obviously the cause context was already lost at this point. Debugging the oscm-app-common AuthorizationFilter has shown that the token check fails. See above bug description.

**Expected behavior**
* Content is displayed successfully
* Token is validated correctly
* Access failures are clearly reported (respective log message)  

**Screenshots**
N/A

**Additional context**
Ask me

**Comment by GoebelL** [comment]
Hi @cworf91 
Updating to the latest OSCM has resolved the issue. It seams to me that there was an inconsistency within the certificates that were deployed in oscm-core and oscm-app.

On the other hand, I've noticed some points to be improved
* There is no feedback when trying to establish the connection. In prior versions there used to be some message in the tab like "Please wait..." and some loading indicator. This is probably gone by the latest UI redesign. I'll create a separate bug issue for this.
* There is some authentication exception that gets logged due to missing authentication header. Note that it's by design that there is no such data for this server information request. The access protection here is implemented with a secure token in the URL and not by user authentication. The exception log is confusion and should be removed for this case.
* Maybe I have overlooked it, but I didn't find a log entry for the certifacte issue. It took us to debug the case to find it out. Please revisit the  [checkToken(...) logic ](https://github.com/servicecatalog/oscm-app/blob/master/oscm-app/src/main/java/org/oscm/app/v2_0/service/APPlatformServiceBean.java#L289) in the APPlatformService and see whether the logging can be improved here. 

Please check.

**Comment by GoebelL** [comment]
I'm lowering the priority since the main issue is resolved. The described leftover is rather a minor topic.

**Comment by GoebelL** [comment]
@uhu133, just fyi

**Comment by GoebelL** [comment]
@cworf91, all,  
I have created bug issue [oscm-app#108](https://github.com/servicecatalog/oscm-app/issues/108) for the first point of above: Missing UI feedback while loading.

**Comment by cworf91** [comment]
Fix is done in
https://github.com/servicecatalog/oscm-app/pull/109
