### ISSUE TITLE
After installing Sample Data, Operation Failed in two pages

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1125]
**Version Info**
master

**Describe the bug**
After installing Sample Data,  there is Operation Failed the first time that you perform "Save" on two pages:
- Manage payment types (Enable "invoice" for a customer).
- Define a Service Price Model.
After the second time, everything operates successfully.

**How to reproduce"
1. Install OSCM with SAMPLE_DATA. 
2. Log-in as supplier and go to "Manage payment types" page.
Enable type INVOICE for "customer1".
3. Go to Price model-> Define for Service page and define "Pro rata" with one time fee: 20 EUros.
4. Click on "Save".

**Observed result**
2. and 4.: Operation failed.

**Expected result**
Successful save and success message appears.

**Comment by GoebelL** [comment]
Hi @KabacinskiPiotr 
Could you have a look into this? Let's discuss it on slack. Thanks.

**Comment by KabacinskiPiotr** [comment]
[Done](https://github.com/servicecatalog/oscm-dockerbuild/commit/20fcfcfb9e16735f6681288ae258ecfe0563fc00)

**Comment by GoebelL** [comment]
Fixed in https://github.com/servicecatalog/oscm-dockerbuild/pull/289
