### ISSUE TITLE
Warnings logged from bootsfacesSelectMenu.xhtml 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#1126]
**Version Info**
19.0 latest

**Describe the bug**
Repeated JSF WARINGS are logged. UI feels slow.

**How to Reproduce**
1. Run `docker logs -f oscm-core` from bash
2. Login to oscm-portal as supplier and open _Marketable Serivces >Activate or Deactivate_
3. See docker logs

**Observed behavior**
1. 23-Nov-2020 16:06:17.049 WARNING [http-nio-8080-exec-8] net.bootsfaces.beans.ELTools.evaluteBaseForMojarra There's no getter to access: #{/WEB-INF/facelets/tags/bootsfacesSelectMenu.xhtml @13,118 value="#{value}"}
2. UI loading feels slow (not sure if this is related)

**Expected behavior**
1. No warning
2. UI loading is normal

**Additional context**
Ask me

**Comment by Piotr-K8i** [comment]
Due to the fact that the bug is probably not on our side, to eliminate WARNINGS we can use directly b:selectOneMenu without facelets tag. Creating dedicated tags is not profitable due to the many different values.

**Comment by GoebelL** [comment]
Todo: Retest the combos in the admin portal.

**Comment by GoebelL** [comment]
Point 2 - "slow UI loading" was probably related with the VPN infrastructure on our site.
