### ISSUE TITLE
Config settings inconsistent https_base_url

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm#1135]
**Version Info**
19.1

**Describe the bug**
When preparing the var.env file for the docker installation, the HOST_FQDN has to be set. This happens without the need to set a Port. Nevertheless, whenn trying to run OSCM with proxy (oscm-proxy), the ports are in the cofing settings and cause problems. 

**How to Reproduce**
1. Install OSCM
2. Set HOST_FQDN in var.env withtout any port
3. Call initdb for core
4. See Config settings with ports. I.e. https_base_url

**Expected behavior**
The operator should be able to set the ports or not.

**Comment by cworf91** [comment]
1. The user should have to enter the HOST_FQDN ONCE, not three times =>
       Modification:
       a) The HOST_FQDN parameter must be mandatory -> The deployer1 call must abort with a readable error message if the parameter was not passed or is invalid
       b) The deployer1 enters this HOST_FQDN in var.env in all places where it is used now.
2. In the deployer1 call, deployed with proxy and started the proxy (default!). Only if "-e PROXY = 'false'" is given in the deployer will the proxy
      not used (-> compatibility) -> the deployer writes the var.env accordingly. The second call starts the proxy with (!) If not switched off by parameter (see above).
3. Further variables in var.env (no ConfigSettings!): OSCM_CORE_URL, OSCM_APP_URL, OSCM_IDENTITY_URL, OSCM_BIRT_URL (every container has a basic URL,
      which is pre-assigned by the deployer. The user can ignore them. These are used in the scripts and ConfigSetting Templates substitution at DbInit instead
      HOST_FQDN. In addition, the settings can be replaced with dbInit.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-dockerbuild/pull/297
https://github.com/servicecatalog/oscm-jenkinsscripts/pull/34

**Comment by GoebelL** [comment]
Hi @cworf91 
The mentioned pull requests have been merged in December. Please update this issue and describe the resoloution here.

**Comment by cworf91** [comment]
The variable HOST_FQDN is now set in the .env file. The var.env file contains now OSCM_CORE_URL, OSCM_APP_URL, OSCM_IDENTITY_URL, OSCM_BIRT_URL which are configsettings and written into the database. These settings contain the HOST_FQDN variable from the .env file. When the deployer is called, this variable does not have to be replaced. The deployer reads the .env file and therefore replaces the variable automatically. If a manual update installation should be carried out, then the .env file should either be activated the automatic export of variables:
set -a
$ {TARGET_PATH} /.env
set +a
Or the variables need to be replaced.

**Comment by SuessI** [comment]
Documentation updated for release 19.1 with all the new settings and places described above.
