### ISSUE TITLE
Service graphics are not loading in the marketplace

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#1142]
**Version Info**
Service graphics are not loaded in the reseller marketplace

**Describe the bug**
After the reseller activates the supplier services in their own marketplaces, the graphics of these servers do not appear on the reseller marketplace index page

**How to Reproduce**
1. Crete service with graphic in supplier
2. Allow reselling service for reseller, select supplier marketplace
3. Activate service
4. Login to reseller
5. Activate previous defined service in reseller marketplace
6. Compare supplier marketplace with reseller marketplace

**Observed behavior**
After the reseller activates the supplier services in their own marketplaces, the graphics of these servers do not appear on the reseller marketplace index page

**Expected behavior**
Graphics should load for the reseller marketplace

**Screenshots**
SupplierOrg:
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/44840276-198b-4822-8b51-0b5a289e4211)

ResellerOrg:
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/450febf8-e3da-4f4e-921a-93574d1544d3)

**Additional context**
Any other context about the problem here.

**Comment by Piotr-K8i** [comment]
@GoebelL,

There are two ways to solve the problem of graphics not loading for marketplaces of Broker and Reseller:
1. Rollback of changes [Get Bulk images #1040](https://github.com/servicecatalog/oscm/pull/1040)
2. Change code in [LandingpageServiceBean](https://github.com/servicecatalog/oscm/blob/master/oscm-internal/javasrc/org/oscm/internal/portallandingpage/LandingpageServiceBean.java). If the service is of the "PARTNER_TEMPLATE" type, download the graphic defined for the parent. Then the code would look like this:
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/25d39d68-d829-4046-85a3-98447b4a32f0)

Please let me know which option should I apply

**Comment by GoebelL** [comment]
@KabacinskiPiotr 
A rollback would reopen the performance issue. Why? 
The point 2 seems to be the proper solution. Please also add respective unit tests.
