### ISSUE TITLE
Published roadmap?

### ISSUE THREAD

**Issue by colineby** [servicecatalog/oscm#1163]
Hi - 

I'm waiting on a bug mapped to 19.1.  Can you tell me when you anticipate that release drop? 

I've not been able to find a roadmap projecting when this release is scheduled to become available. Perhaps I've just missed it. 

Background: 
I need a fix for the 1095 bug.  I'm attempting to implement a parameterised operation.  I'm hoping to do this with oscm-app-shell. I'm running containerised -- so I need the 19.1 RC or GA if that's where this bug is going to land. 

Kind regards, 
Colin Eby

**Comment by GoebelL** [comment]
Hi @colineby 

the bug #1095 is fixed upstream. Just pull from servicecatalog/oscm-core:latest. 
You can use the [soap-mock](https://github.com/servicecatalog/oscm-soap-mock) to test it. Just play the [use case](https://github.com/servicecatalog/oscm-soap-mock#short-use-case) from the readme. 

19.1 GA is targeted for mid February.
