### ISSUE TITLE
marketplace: navbar covered scrollbar and arrow is not visible

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#1166]
**Version Info**
19.0 2021/01/19
**Describe the bug**
navbar covered scrollbar. Arrow is not visible

**How to Reproduce**
1. Go to marketplace page

**Screenshots**
![escm2](https://user-images.githubusercontent.com/15209605/105477528-4068cf00-5ca2-11eb-8822-88dea9905fa5.PNG)

**Comment by elfriedegoetz** [comment]
version 19.1 2021/01/27
It's fine with the Chrome browser, but the problem persists with Firefox

**Comment by Piotr-K8i** [comment]
Tested on:
Internet Explorer,
Google Chrome,
Mozilla Firefox
Opera,
Microsoft Edge

I have not found any problems with covering the scroll bar on any of these browsers. It is possible that the browser had css files in the cache. Please load all files again (Ctr + F5). If the problem persists, please enter your browser version.
