### ISSUE TITLE
on marketplace page a  small layout issue

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#1168]
**Version Info**
19.0 2021/01/19

**Screenshots**
The checkbox is not complete
![escm5](https://user-images.githubusercontent.com/15209605/105482369-90e32b00-5ca8-11eb-814e-fe102d3ac464.PNG)

**Comment by kowalczyka** [comment]
Issue is not reproducable any more.

Version: 19.1 2021/01/27

![assign_users](https://user-images.githubusercontent.com/14541935/106114428-d5127780-614f-11eb-81a1-da381de5b313.jpg)

**Comment by elfriedegoetz** [comment]
It's fine with the Chrome browser, but the problem persists with Firefox

![fox1](https://user-images.githubusercontent.com/15209605/106121213-997bab80-6157-11eb-8d54-0b4e6f584108.PNG)
