### ISSUE TITLE
After update installation proxy can not be started

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#1179]
**Version Info**
27/01/2021

**Describe the bug**
After update installation proxy can not be started.

**How to Reproduce**
1. install oscm version 18.0.2
2. add some data to the oscm-portal
3. update oscm to  the latest daily build:
4.   goto installdir and delete everything except config and data
5.  docker run --name deployer1 --rm -v /docker_v18:/target -e HOST_FQDN=name -e SAMPLE_DATA=true  <host>/oscm-registry/oscm-deployer:test
6. edit .env:

IMAGE_DB=host/oscm-registry/oscm-db:test
IMAGE_CORE=host/oscm-registry/oscm-core:test
IMAGE_APP=host/oscm-registry/oscm-app:test
IMAGE_BIRT=host/oscm-registry/oscm-birt:test
IMAGE_BRANDING=hostoscm-registry/oscm-branding:test
IMAGE_INITDB=host/oscm-registry/oscm-initdb:test
IMAGE_HELP=host/oscm-registry/oscm-help:test
IMAGE_IDENTITY=host/oscm-registry/oscm-identity:test
IMAGE_MAILDEV=host/oscm-registry/oscm-maildev:test
IMAGE_PROXY=host/oscm-registry/oscm-proxy:test

DOCKER_PATH=/docker_v18

HOST_FQDN=host

7.  docker run --name deployer2 --rm -v /docker_v18:/target -v /var/run/docker.sock:/var/run/docker.sock -e INITDB=true -e SAMPLE_DATA=true -e STARTUP=true -e PROXY=true host/oscm-registry/oscm-deployer:test

**Observed behavior**
Network docker_default declared as external, but could not be found. Please create the network manually using `docker ne                                                                                                                     twork create docker_default` and try again.

**Expected behavior**
all container are running 

**Additional context**
There is still a parallel docker installation, but all containers are down

**Comment by GoebelL** [comment]
Hi @elfriedegoetz 
The message `Network docker_default declared as external, but could not be found.` is explainable as follows.
Your command was

>docker run --name deployer2 --rm -v /docker_v18:/target ...

This shows that this second OSCM installation resides in a directory docker_v18 and not in docker. The docker network name is by default the docker project name followed by *_default*. As the project name refers to the host directory, it should be 'docker_v18_default' in the given case.
Thus, modifying the last line in `/docker_v18/proxy/docker-compose-proxy.xml` as follows will resolve the issue:
```
networks:
  docker_default:
    external:
      name: docker_v18_default
```

**Comment by GoebelL** [comment]
Instead of manually editing docker-compose-proxy.xml and for avoiding any subsequent trouble, it is more save to keep all OSCM installation in a directory named "docker". This directory can be located anywhere on the host and doesn't limit the usage.
The agreed solution: OSCM must be installed in a directory named "docker". The install documentation will be updated accordingly.

https://github.com/servicecatalog/oscm-dockerbuild/pull/326

**Comment by SuessI** [comment]
Documentation updated with release 19.1: Name of data directory must be "docker"
