### ISSUE TITLE
Service subscriptions doesn't work at Azure VM

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#1188]
**Version Info**
19.1

**Describe the bug**
Unable to subscribe services for the OIDC mode installed on Azure VM 

**How to Reproduce**
1. Create Azure VM
2. Install OSCM at this VM
2. Subscribe any service
3. Check logs at oscm-core/logs/system.log

**Observed behavior**
Subscribed service is still on pending status. Error logs appear

**Expected behavior**
Subscibed service is in ready status. Error logs don't appear

**Screenshots**
N/A

**Additional context**
[Azure VM Error logs - Access denied, no user found. Evaluating session context failed](https://app.zenhub.com/files/108258123/eb69237e-3a88-4407-85e3-5e51be9d17ee/download)

**Comment by GoebelL** [comment]
@KabacinskiPiotr 
If you have some cause details please share me on slack, before starting on it. Thank you.

**Comment by GoebelL** [comment]
This discovered bug https://github.com/servicecatalog/oscm-dockerbuild/issues/330 on same VM could be related with this. The custom branding there is not the point, rather some configuration issue or combination bug with OIDC, proxy, and firewall.

**Comment by GoebelL** [comment]
Hi @KabacinskiPiotr 

Yesterday @cworf91 made some update and configuration fix on his OIDC mode VM, and then the issue was gone. If needed he can share you his settings. 

Let's close this.
