### ISSUE TITLE
APP vmware controller: wrong browser message appears, if trying to change password

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#119]
[Build]
docker 17.7 2018/07/17

[Steps to reproduce]
login to APP vmware controller
chnage password
click save

[Expected result]
password will be chanded and a vaild message is shown

[Observed result]
a wrong message is shown see attachment
![save](https://user-images.githubusercontent.com/15209605/42812171-0af56f82-89bd-11e8-8928-4398182e1ee9.PNG)

**Comment by GoebelL** [comment]
Duplicate with #114.
