### ISSUE TITLE
Upgrade Bootstrap version

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1190]
**Summary**
Bootstrap is upgraded to version 5.0.

**Details**
Bootstrap is upgraded to the newest version 5.0, since it offers more features, for example more useful color functions, support for CSS variables, etc. 
A useful feature is the runtime customization of the UI (for example the primary and the secondary colors) with CSS variables. See [this link](https://getbootstrap.com/docs/5.0/customize/css-variables/#root-variables) for more information on this topic.

Check also the components that have been renamed in version 5.0. See [here](https://getbootstrap.com/docs/5.0/migration/) for renamed components.

**Acceptance criteria**
- [x] Bootstrap is upgraded to version 5.0.
- [ ] Automatic tests are green
- [ ] UI functionality and customization works exactly as before
- [ ] UI Customizability is preserved

**Additional context**
Add any other context or screenshots about the task.

**Comment by Piotr-K8i** [comment]
After upgrading to Bootstrap 5, the problem is with the popover focusing. After a few appearances, the popover is no longer visible. Probably the bug is connected to [tooltip bug](https://github.com/twbs/bootstrap/issues/32372)

**Comment by GoebelL** [comment]
> After upgrading to Bootstrap 5, the problem is with the popover focusing. After a few appearances, the popover is no longer visible. Probably the bug is connected to [tooltip bug](https://github.com/twbs/bootstrap/issues/32372)

AFAICS, this bug has been fixed in the recent [beta3 release](https://github.com/twbs/bootstrap/releases/tag/v5.0.0-beta3) 

@farmakiG 
Please take over here. Bump this PR to the latest bootstrap 5 release and check this again.
