### ISSUE TITLE
Provide a Light/Dark theme toggler at the UI at runtime

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1191]
**Summary**
Provide at the UI a "light/dark" theme toggler so that the user is able to switch at runtime between a light and dark theme. Extend the toggler to provide a "main-color" for the theme at runtime.
One possible place for configuring the theme is a user-specific setting at the "Account->Profile" page.

**Details**
To fulfill this task, first it must be investigated if the theme variables (or generally speaking a respective "data-theme" set at the "body" CSS element) can be provided: 
a) at Runtime or 
b) as pre-compiled scss files.
The first way can be achieved via the CSS variables mechanism. Then our .scss files contain variables such as : color: var(--secondary-color). 
See [here](https://github.com/twbs/bootstrap/issues/26596) for more details.

A drawback of the first way is potentially large bootstrap libraries files as all theme-colors must be included. 
The second way can include two pre-compiled light/dark theme versions.
In case the dark/light toggler is extended in the future by defining a user-defined "main-color", e.g. in an input field as hexadecimal code, then the scss files can be re-compiled in a page on the server.

**Acceptance criteria**
- [ ] UI Customizability is preserved.
- [ ] Manual tests for: 1) light, 2) dark and 3)main-color themes.
- [ ] UI automatic tests.

**Additional context**
N/A.

**Comment by GoebelL** [comment]
Todo: 
- Expose the variables in the compiled CSS files.
- Enhance main/head marketplace JSF template to read the variables from session and inject in response CSS
