### ISSUE TITLE
app vwmare controller: you have to restart the container, if password was changed

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#120]
[Build]
docker 17.7 2018/07/17

[Steps to reproduce]
login to APP vmware controller
chanage password
click save  (click leave page see bug114, and password is changed in the DB)
create a new Instance

[Expected result]
Instance will be created

[Observed result]
Instance creation failed
the old password is used

[Detail]
to take effect you have to restart the container, after changed the password

**Comment by GoebelL** [comment]
This is adressed in https://github.com/servicecatalog/oscm/pull/139

**Comment by kowalczyka** [comment]
Issue is resolved with https://github.com/servicecatalog/oscm/commit/34cefdd6f5d620892da781341a125e5c36224f3c
