### ISSUE TITLE
Adjust Sass variables with lighten/darken functions.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1207]
**Summary**
The Bootstrap CSS custom variables mechanism does not support Sass functions such as darken and lighten which are used in several places in our .scss files.
Therefore, replace these Sass functions with the rgba function which works with Bootstrap CSS variables, wherever we need lighter or darker versions of a color.

**Details**
Refer to [Bootstrap Github issue](https://github.com/twbs/bootstrap/issues/26596#issuecomment-394140233) for a suggestion on the lighten/darken function replacement.
Alternatively, pre-define some shades of specific colors before hand and switch at runtime only between these values in the maps:  :root[data-theme="dark]" or :root[data-theme="light"]

**Acceptance criteria**
- [ ] UI customizability is preserved.

**Additional context**
N/A.

**Comment by Piotr-K8i** [comment]
@farmakiG 

I believe that these functions is not necessary. The darken function is applied with rgba. And using this feature, it was possible to obtain both a dark and a light mode for the marketplace. The customer can still customize the page with rgba, for example, defining two shades of color.
