### ISSUE TITLE
VMware Instance: marketable service: "user option" for Domain Name has to be set

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#121]
[Build]
docker 17.7 2018/07/17

[Steps to reproduce]
create a marketable service without "user option" for Domain Name 
create a new Instance

[Expected result]
Instance will be created

[Observed result]
Reported problem: Failed to create VM instance 1531901093799.
[Detail]
"user option" for Domain Name is needed, but the value can be empty. This does not make sense

**Comment by elfriedegoetz** [comment]
Make Domain Name as a mandatory parameter is not necessary. 
The problem is that the user option must be set, although the parameter can also be empty.
This does not make sense.

**Comment by ghost** [comment]
> [Steps to reproduce]
create a marketable service without "user option" for Domain Name
create a new Instance
...
[Detail]
"user option" for Domain Name is needed, but the value can be empty. This does not make sense

Making a technical service parameter mandatory requires from user providing a value. If "user option" is not set and someone tries to leave it empty then there is an error. As an example I have used azure service. As you can see it did not allow me to create marketable service as long as required paramter is empty and "user option" is not set.

![image](https://user-images.githubusercontent.com/40793157/47419905-7b0af680-d77d-11e8-9b14-1c5bdd118d9c.png)

Going further if we do check "user option" near required paramter then it will allow to create marketable service, but it will not allow to leave values empty while creating a subscription.

![image](https://user-images.githubusercontent.com/40793157/47420059-dc32ca00-d77d-11e8-94a2-6783c61cac85.png)

I believe this solves the issue.

**Comment by elfriedegoetz** [comment]
I have investigated the problem more closely and found that the domain name is not taken into account. This is always : intern.est.fujitsu.com regardless of how the value is set. 
![domain](https://user-images.githubusercontent.com/15209605/47484952-57a78080-d83d-11e8-8201-5a53f1a54563.PNG)

**Comment by GoebelL** [comment]
Let's keep it simple. Specify the default name given by VCenter as default parameter value in the technical service template and keep the parameter mandatory. The supplier will leave this parameter as non-user- option, so that the customer does have to bother with it.

**Comment by elfriedegoetz** [comment]
okay with build 31.11.2018
