### ISSUE TITLE
Set Theme Colors at runtime

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1219]
**Summary**
Set the basic theme colors at the Profile page. These are: 

1) the primary color, 
2) the theme-background-color 
3) the theme-background-color for input fields, 
4) the theme-foreground-color, 
5) the navigation background color and 
6) the navigation foreground color.

**Details**
List of :root variables that must be affected:

- --oscm-primary: primary color
- --oscm-main: background color
-  --oscm-main-input-color: background color for input fields.
- --oscm-main-font-color: foreground color for text
- --oscm-navbar-color: background color for navigation
- --oscm-navbar-links-color: foreground color for navigation

**Acceptance criteria**
- [ ] All above colors are updated in the UI upon click of "Save" in the Profile page
- [ ] UI Tests
- [ ] UI Screenshots
- [ ] UI Customizability is preserved

**Additional context**
N/A.

**Comment by GoebelL** [comment]
Main work is already done by @KabacinskiPiotr. Left over is:
- Naming of the variables
- Labels on the UI
- UI Tests
