### ISSUE TITLE
Enhance Display Settings - Update Model and DO

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1225]
**Summary**
Enhance Display Settings model and Domain Object with following properties:
- theme-background-color
- theme-foreground-color
- theme-input-color
- theme-navigation-background-color
- theme-navigation-foreground-color

**Details**
If applicapable, detailed information regarding things to be considered, requirements etc.

**Acceptance criteria**
- [ ] Manual tests
- [ ] Unit tests
- [ ] DB Schema tests

**Additional context**
N/A.

**Comment by GoebelL** [comment]
There is no need for enhancing the DO and schema. The data model is enough generic here. Just add respective getters and setters in the UI model [DisplaySetting](https://github.com/servicecatalog/oscm/blob/master/oscm-portal/javasrc/org/oscm/ui/model/DisplaySettings.java). As long as the JSON length is not exeding the limit this should be enough.

**Comment by GoebelL** [comment]
Furthermore this looks to be duplicate with issue #1224. Can we close this?

**Comment by farmakiG** [comment]
Yes we can close it as a duplicate of #1224.
