### ISSUE TITLE
TechnicalService ParameterDefinition id is too short

### ISSUE THREAD

**Issue by fabiorauber** [servicecatalog/oscm#123]
When trying to update a WordPress k8s technical service definition, I stumble upon the maximum number of characters of the ID of a ParameterDefinition, as can be seen below:

> The import failed due to errors in the XML file. Details: 91: cvc-maxLength-valid: Value 'parameters.mariadb.master.persistence.enabled' with length = '45' is not facet-valid with respect to maxLength '40' for type 'StrId'. 91: cvc-attribute.3: The value 'parameters.mariadb.master.persistence.enabled' of attribute 'id' on element 'ParameterDefinition' is not valid with respect to its type, 'StrId'. . Refer to the Technology Provider's Guide for details on the XML file elements a technical service definition consists of.

But I need to define this particular parameter. Am I doing something wrong?

**Comment by GoebelL** [comment]
Hi @fabiorauber 
You are right. These IDs are limited to 40 characters by the technical service schema. This is defined in \oscm-serviceprovisioning\javares\TechnicalServices.xsd. I am not sure about the helm sample case and if there is some workaround on that. Nevertheless I do agree that this parameter id definition might be too tight for some integration cases where are you are bound to certain ID values. Switching this id type to str255 should solve your issue and keep backward compatible. I think it's a valid and painless change. Thus let me see if we can integrate this with next docker build.

**Comment by fabiorauber** [comment]
Thank you! I'll wait and then validate the change.

**Comment by GoebelL** [comment]
@fabiorauber 
The fix is pushed on dockerhub. Just pull the images with tag latest. You'll find a readme on https://hub.docker.com/r/servicecatalog/oscm-deployer/

Let me know if it works for you.

**Comment by fabiorauber** [comment]
OSCM accepted the ID now. Seems to be working fine. Thanks!
