### ISSUE TITLE
Migrate to travis-ci.com for all repositories 

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1235]
**Summary**
travis-ci will be migrated soon from travis-ci.org to .com
We should migrate our repositories to travis-ci-com in order to have the full functionality (restart previous builds, display repository settings etc.).

**Details**
It is not sure whether the migration of the repositories from travis-ci.org  to travis-ci.org has happened already, since the "restart" build functionality as well as the Repository Settings are no longer available. It seems that the repositories are still there but in readonly mode.

Refer to this [link](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) for more details on the migration.

**Acceptance criteria**
- [x] Execute the migration steps included in the link above
- [x] The repositories are successfully migrated and manually tested.
- [x] The whole functionality such as restarting builds, repository settings etc. is available.

**Additional context**
N/A.

**Comment by GoebelL** [comment]
Done.

Related PRs:
https://github.com/servicecatalog/oscm/pull/1239
https://github.com/servicecatalog/oscm-app/pull/123
https://github.com/servicecatalog/oscm-interfaces/pull/59
https://github.com/servicecatalog/oscm-rest-api/pull/254
https://github.com/servicecatalog/oscm-app-shell/pull/91
https://github.com/servicecatalog/oscm-commons/pull/49
https://github.com/servicecatalog/oscm-approval/pull/65
