### ISSUE TITLE
Active list-group-items colors are light

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1236]
**Version Info**
Latest master after merge of branch "clean up root".

**Describe the bug**
As shown in the below screenshots, the color of the selected tab is light, whereas of the non-selected tabs dark.

**How to Reproduce**
1. Login to the Marketplace UI
2. Go to "Account -> Profile" page
3. See the resulting screenshot.

**Observed behavior**
Seleted tab is light green and non-selected dark green.

**Expected behavior**
Selected tab is dark green and non-selected light green.

**Screenshots**
![Screenshot_2021-04-12 Marketplace](https://user-images.githubusercontent.com/49904723/114369128-5d64be00-9b7e-11eb-882d-1256cb72b86b.png)

**Additional context**
N/A.

**Comment by GoebelL** [comment]
Let me check it.
