### ISSUE TITLE
Check test case 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#129]
Take a look to https://github.com/servicecatalog/oscm/blob/master/oscm-app-unittests/javasrc-it/org/oscm/app/v2_0/service/APPTimerServiceBeanIT.java#L1363
Q: Why is the instance parameter NAME1 not rolled back?

**Comment by xusuest** [comment]
The entry key  in the properties of xml for second parameter was wrong. 
It should be set as "param2.*" but not "param1.*".
https://github.com/servicecatalog/oscm/blob/master/oscm-app-unittests/javasrc-it/org/oscm/app/v2_0/service/APPTimerServiceBeanIT.java#L1613

**Comment by GoebelL** [comment]
Good find @xusuest!

**Comment by xusuest** [comment]
Issue fixed and closed. 
https://github.com/servicecatalog/oscm/pull/128/commits/137080c03f76350edfdfb78bcb118dd3b85bc003
