### ISSUE TITLE
Remove deprecated config settings from UI

### ISSUE THREAD

**Issue by shimizuf** [servicecatalog/oscm#13]
Several config settings in the administration portal are deprecated and should be marked as such or removed.
These were found:
* HTTP_PROXY_*: Historic; proxy settings for the application must be implemented in a different way
* LOG_FILE_PATH: Obsolete with Docker images
* LOG_CONFIG_FILE: Obsolete with Docker images
* KEY_FILE_PATH: Obsolete with Docker images

There may be more.

**Comment by shimizuf** [comment]
@GoebelL Please set labels and assign as appropriate.

**Comment by grubskim** [comment]
Removed HTTP_PROXY and HTTP_PROXY_PORT completely.
Following settings are now hidden from the UI:
LOG_FILE_PATH
LOG_CONFIG_FILE
KEY_FILE_PATH

**Comment by GoebelL** [comment]
BASE_URL_HTTP needs to be removed from UI. HTTPS is mandatory for access from different network or host. HTTP is only for internal communication. Therefore BASE_URL_HTTPS needs to be set mandatory. 

The removal of BASE_URL_HTTP maybe risky for the next release in terms of side-impacts and efforts. For this milestone, it shall be sufficient to leave the property empty, read-only and hide it in the operator UI.

**Comment by DawidCh** [comment]
I wouldn't remove anything, just hide from user, as Michał did with LOG_FILE_PATH. It is the safest way.

**Comment by GoebelL** [comment]
Agreed.

**Comment by grubskim** [comment]
Added BASE_URL to the hidden settings. BASE_URL_HTTPS is mandatory.

**Comment by kwodzynski** [comment]
Tested on 17.5 2017/11/29. Deprecated settings are not visible.
