### ISSUE TITLE
Missing IP in vmware access info

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#132]
The marketable service for the vmware connector uses the pattern "{HOST},{IP}" for the access info. After the service provisioning the access info only holds the hostname, not the IP address.
![ip](https://user-images.githubusercontent.com/32158057/43464323-1d684e0e-94db-11e8-9130-8ecea849d374.JPG)
![ip-2](https://user-images.githubusercontent.com/32158057/43464400-56288f7e-94db-11e8-866d-49e3689cb662.JPG)

**Comment by uhu133** [comment]
VMware manual page 25

ACCESS_INFO
Optional. A pattern for the access information for a VM after it has been provisioned. The
access information is sent by email to the subscribing user as well as all users assigned to the
subscription. It is displayed in the details of the subscription.
The instance-specific values of this parameter contain the actual access information for the VM
as soon as the subscription has been created.
The pattern may contain any textual expression. In addition, the following placeholders are
supported:
• ${IP}: IP address of the VM.
• ${HOST}: Host name of the VM.
• ${CPU}: CPU count.
• ${MEM}: Main memory.
• ${DISK}: System and data disk size(s).
Example: ${HOST}(IP:${IP})<br>${CPU} CPUs, ${MEM} RAM, ${DISK} HDD
Default: ${HOST}, ${IP}

**Comment by GoebelL** [comment]
@uhu133 
Did you give a value to NUMBER_OF_NICS?

**Comment by GoebelL** [comment]
@uhu133 
NIC1_NETWORK_ADAPTER is an optional parameter in the technical service. However the network name is needed here for determining the guest IP address. Indeed this behavior is strange. 
Nevertheless it's a workaround: The correct IP should be returned if you give the network name in NIC1_NETWORK_ADAPTER.
Please try.

**Comment by uhu133** [comment]
Jist tried - with the VM network name defined in marketable service it works
