### ISSUE TITLE
Doc: VMware vSphere Integration; everal Parameter are mandatory in Technical service

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#134]
VMware vSphere Integration:
The following Parameter are mandatory in the Technical Service Definition:
TARGET_VCENTER_SERVER, TARGET_DATACENTER, TARGET_CLUSTER

**Comment by gertipoppel** [comment]
Modified the description in the VMware vSphere Integration Guide. Will be available next Thursday (09/08/2018)
Modified sources: 
en/VMwareIntegrationGuide/Appendix/r_ServiceParameters.xml
