### ISSUE TITLE
VMware controller: no helpful error message, if create instance are failed

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#137]
[Build]
docker 17.7 2018/07/17

[Steps to reproduce]
create a Instance with wrong parameter for examples "Target Cluster".

[Expected result]
a useful errer maessage

[Observed result]
Dear user,

The current operation on subscription 'VMware ESS 6.5 17.4' for customer 'PLATFORM_OPERATOR' has been suspended (Instance: '1533798822504').

Reported problem: Failed to create VM instance 1533798822504.

**Comment by GoebelL** [comment]
Sure the error handling could be improved at this point. However it would be good to have a sort of test connection button here that can be used to ping the target cluster. This would be helpful to detect configuration errors before provisioning. Not sure how well this is supported from the VSphere SDK.

**Comment by GoebelL** [comment]
In case of an provisioning error the controller is expected to return an informative error message with the APPlatformException in ´VmwareController#createInstance´. 

@fest-floreks 
Please check if the error information as retrieved from the SDK is properly returned here.

**Comment by ghost** [comment]
I will check that.

**Comment by uhu133** [comment]
I can also confirm that more information on VMware errors is required. I detected more useful information in the oscm-app logfiles which could be used:

[08/06 14:27:45] [EjbTimerPool - 2] ERROR Failed to create VM of instance 1533565594168
com.vmware.vim25.InvalidLoginFaultMsg: Cannot complete login due to an incorrect user name or password.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

**Comment by ghost** [comment]
Indeed it looks like the full error message is logged and the partial message is displayed.

https://github.com/servicecatalog/oscm/blob/34cefdd6f5d620892da781341a125e5c36224f3c/oscm-app-vmware/javasrc/org/oscm/app/vmware/business/statemachine/CreateActions.java#L99-L103

**Comment by GoebelL** [comment]
Please include the given exception details in the error message, same as the composed log message.

**Comment by elfriedegoetz** [comment]
I have tried to create instances with several wrong parameter or wrong user name, but the error message has no more information than before.
In the container log file I get more information:
[2018-10-05 11:51:01] [EjbTimerPool - 1] ERROR Failed to create VM of instance 1538740220610
org.oscm.app.v2_0.exceptions.APPlatformException: The configured vSphere data center, ESTE, could not be found.

**Comment by GoebelL** [comment]
@elfriedegoetz 
I have checked the last QA docker build. It has picked an too early revision bf04650, which doesn't include this fix yet. I have created a new build. Please pull it once more.

**Comment by elfriedegoetz** [comment]
Now it works fine
Dear user,

The current operation on subscription 'VMware ESS 6.5 17.4(3)' for customer 'PLATFORM_OPERATOR' has been suspended (Instance: '1539769178243').

Reported problem: Failed to create VM instance 1539769178243.The configured vSphere data center, ESTd, could not be found.
