### ISSUE TITLE
VMware controller: GUI for Datacenter,Cluster .. are missing

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#138]
[Build]
docker 17.7 2018/07/17

login to APP VMware Conroller. There is no UI to show the values for datacenter cluster vlan IPpool. 
see attachment
![vmwarecontroller](https://user-images.githubusercontent.com/15209605/43884459-743ff182-9bb6-11e8-9611-baa7cba1af6c.PNG)

**Comment by ghost** [comment]
@elfriedegoetz @GoebelL 

I am currently investigating this issue. How should this information be displayed considering the fact that each vcenter can have multiple datacenters defined and each vcenter -> datacenter mapping can have multiple clusters defined. Additionally, there can be ippool, vlan configuration defined per each vcenter -> datacenter -> cluster mapping. This can provide many possible configurations.

**Comment by elfriedegoetz** [comment]
Yes exactly, but therefore it is important to see which values are stored

**Comment by ghost** [comment]
I actually need some guidance about expected UI design and how information should be displayed there considering all the connections and level of information required to display.

**Comment by GoebelL** [comment]
1. Add a new row "cluster" listing configured clusters from the database as comma-separated list.
2. Put links on each listed cluster which can be used to inspect the detail settings within a popup window
![grafik](https://user-images.githubusercontent.com/14805690/54907271-5ca05700-4ee5-11e9-887f-a12d6eb681bc.png)
