### ISSUE TITLE
Attaching to oscm-initdb-core - database not ready - waiting

### ISSUE THREAD

**Issue by Marcelo3384** [servicecatalog/oscm#140]
Hi,

I followed instructions.
Installed Docker and Docker Compose.

Then i Run: docker run --name deployer1 --rm -v /docker:/target servicecatalog/oscm-deployer

It Creates var.env and .env

I configured the data.

Then i run: docker run --name deployer2 --rm -v /docker:/target -v /var/run/docker.sock:/var/run/docker.sock -e INITDB=true -e STARTUP=true servicecatalog/oscm-deployer

and it works till: Attaching to oscm-initdb-core - database not ready - waiting
Its not stoppable and will count till forever ...

What im doing wrong?

**Comment by GoebelL** [comment]
Hi @Dante12345 
Which versions of docker and docker-compose do you use?

**Comment by GoebelL** [comment]
I think to remember that for Ubuntu something shoud be deactivated. But I forgot... 
@uhu133, 
do I rememer well that you have OSCM running on Ubuntu? Can you help here?

**Comment by Marcelo3384** [comment]
Hi, much thanks for helping me.

Im using: vSphere with Cluster, on this Cluster runs a Host. On this Host runs a Network (in DMZ) and an ubuntu VM (Xenial 16.04.5 server LTS)
It has an IP: 195.50.xxx.xx 

My Docker version:  18.06.0-ce
My Docker-Compose Version: 1.18.0, build 8dd22a9

**Comment by uhu133** [comment]
My Unbuntu is
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.0, build 5920eb0


No issues - nothing special settings

**Comment by Marcelo3384** [comment]
Ok, so an upgrade to Ubuntu 18.04 should fix the problem??

Thank you

**Comment by Marcelo3384** [comment]
I upgraded Ubuntu to the same Versions from @uhu133 

still not working..
![adsdas](https://user-images.githubusercontent.com/19793366/44096444-8f62315e-9fdb-11e8-9c9c-75f36972b0d8.PNG)


maybe something is wrong with my configuration, but im sure i got everything i need and also uncommented everything im not using (like vm, openstack etc)

**Comment by Marcelo3384** [comment]
Why did you close this??

**Comment by kowalczyka** [comment]
Hello Dante12345,

did you fill the var.env file with proper values (e.g. those related to the database: DB_***)?

**Comment by shimizuf** [comment]
Hi @Dante12345,

in addition to @kowalczyka's question: The fact that the initdb-core container cannot reach the database points to some problem in your var.env file. Is it possible that you post the contents of your var.env file, redacting passwords?

**Comment by Marcelo3384** [comment]
Hi,

Thank you.

This is my var.env Database Setting:
![database](https://user-images.githubusercontent.com/19793366/44261738-e0d88080-a218-11e8-8ed7-7a50033135ac.PNG)

Here are the other settings.. rest is uncommented

![controller](https://user-images.githubusercontent.com/19793366/44261761-f2218d00-a218-11e8-8ef1-e80135037ff1.PNG)
![ip2](https://user-images.githubusercontent.com/19793366/44261985-a4595480-a219-11e8-95ad-e947f3d0d2e7.jpg)
![log](https://user-images.githubusercontent.com/19793366/44261770-f5b51400-a218-11e8-8e8d-2363c43106a3.PNG)

**Comment by shimizuf** [comment]
Thanks for posting your var.env. The `${PLACEHOLDERS}` are actually in BASH variable format and must be replaced by the actual string. In other words, the `${}` must be removed. For example:

```
DB_PORT_CORE=5432
DB_PWD_CORE=mY_v3rY-53cUr3_p4zZw0rD
```

Could you please change your settings like that and try again? In the setting `REPORT_ENGINEURL`, please only remove the `${}` of the first parameter, where you entered your IP address, not in the others, like `\${reportname}`.

Before starting the deployer2 step again, please make sure to stop and delete any containers that may still be running.

**Comment by Marcelo3384** [comment]
Thank you very much, removing the ${ solved the problem!!

i still cant connect to the https://hostname.fqdn:8081/oscm-portal/ .. but i think this is a firewall/network problem


much thanks !

**Comment by shimizuf** [comment]
Glad to hear that, thank you for your feedback.

I'll close this issue. If you need more assistance, please feel free to create a new one.

Best regards.
