### ISSUE TITLE
oscm-app-vmware writes logfile with wrong name

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#141]
[app-aws.log](https://github.com/servicecatalog/oscm/files/2287162/app-aws.log)
[app-aws.log](https://github.com/servicecatalog/oscm/files/2287165/app-aws.log)

Observed:

if you want to debug the oscm-app-vmware controller you have to create a file<log4j.ess.aws.properties> in <apache/conf> directory and the output goes to  <app-aws.log>

in second installation this was the smae with <app-core.log>

Desired:

create a file <log4j.ess.vmware.properties> and the output goes to <app-vmware.log>

**Comment by GoebelL** [comment]
@fest-floreks 
Not sure if it matters, but I think a root slash is missing in the vmware log file path. 
Please check 
https://github.com/servicecatalog/oscm/pull/154/commits/0e8ffbf0b7d528675ebaef21e2127176e099d412#diff-2acd3bb5ded6921a456e0dac1c2d0303R25

**Comment by ghost** [comment]
Relative path still works as the search starts from the root dir, but just to be sure that some future change will not collide with it I will add the root slash.

**Comment by elfriedegoetz** [comment]
app-vmware.log is ok
app.aws.log does not work: Templet not found
app.openstack.log has entries from azure and vmware

**Comment by ghost** [comment]
Described behavior looks like the one before applying the fix. Is it possible that it was tested on some old build and not latest master?

**Comment by elfriedegoetz** [comment]
tested with build from 19.10.2018:
app-vmware.log is ok
app.aws.log is empty
app.openstack.log is ok
app.azure is ok

**Comment by ghost** [comment]
Logging is set to quite high level so they can be empty unless controller is used.

**Comment by elfriedegoetz** [comment]
Yes, but errors should be logged in any case.

**Comment by ghost** [comment]
They will be logged. WARN level means that warnings, errors and fatal level messages will be logged.

**Comment by elfriedegoetz** [comment]
just for my understanding, I tested with a wrong authentication and received the following mail. But the log file is empty?

Dear user,

The current operation on subscription 'AWS_EC2' for customer 'PLATFORM_OPERATOR' has been suspended (Instance: 'aws-34b5c690-3ec3-4ee8-bbc5-ca523606598c').

Reported problem: AWS authentication failure: AWS was not able to validate the provided access credentials (Service: AmazonEC2; Status Code: 401; Error Code: AuthFailure; Request ID: b3904f7a-f0d5-4b9e-a992-fd2c88878040)

To continue automatic processing, please click the following URL:
https://estst1.intern.est.fujitsu.com:8881/oscm-app/notify?sid=aws-34b5c690-3ec3-4ee8-bbc5-ca523606598c&controllerid=ess.aws&_resume=yes

If the problem cannot be solved and the processing cannot be continued, please terminate the subscription and create a new one.

**Comment by ghost** [comment]
This means that error is thrown in the code but log4j is not used to log it. Only mail is sent.

**Comment by elfriedegoetz** [comment]
I close this bug and create a new bug for oscm-app-aws  #164
