### ISSUE TITLE
Password change for the owner of the VMware controller failed

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#142]
[Build]
docker 17.7 2018/08/28

[Steps to reproduce]
The OSCM installation was done from scratch in clean environment with sample data.
 "docker run --name deployer2 --rm -v ${WORKSPACE}:/target -v /var/run/docker.sock:/var/run/docker.sock -e INITDB=true -e SAMPLE_DATA=true -e STARTUP=true artifactory.intern.est.fujitsu.com:5003/oscmdocker/oscm-deployer:QA-17.7"

step1: login to ...8081/oscm-portal with "supplier@adfs.com" and  password "supplier"
           works fine
step2: login to vmware controller with "supplier@adfs.com" and  password "supplier"
          works fine
step3: login to ...8081/oscm-portal with "supplier@adfs.com" and  password "supplier"
step4: click account and change password to "supplier123"
step5: try to login to vmware controller

[Expected result]
login works fine with password supplier or supplier123 ??

[Observed result]
error occures . The login page is not available see attachement.
![controller](https://user-images.githubusercontent.com/15209605/44708911-9a9ce000-aaa8-11e8-9659-4627ea9e7f95.PNG)

additionally the login to ..8081/oscm-portal with "supplier@adfs.com" and "supplier123" is not possible any more see attachement
![locked](https://user-images.githubusercontent.com/15209605/44708923-a1c3ee00-aaa8-11e8-8e6d-dc8ba8beb005.PNG)

note: I've tested with firefox private mode to avoid caching

**Comment by GoebelL** [comment]
The user credentials for the technical service for the VMWare connector have to be kept in sync with OSCM core. For changing the credentials the required procedure is the other way around. 

1. Set new credentials in VMWare controller UI
2. Login to OSCM portal and change password on the account page.

In practice this technology manager user is a technical user, only internal and doesn't require to have the password frequently changed.  Nevertheless, when executing those steps in reverse order, the above result is not what one would expect. To get out of this error, I guess you need to login with a second administrator who has access to login to the controller UI and correct the stored credentials.

**Comment by GoebelL** [comment]
>To get out of this error, I guess you need to login with a second administrator .... 

As shown in the screenshot, the user is locked. This is probably because of too many failed logins. So, first the platform administrator has to unlock the user's account.

**Comment by elfriedegoetz** [comment]
In reverse order, as described by GoebelL, it works fine.

**Comment by ghost** [comment]
@GoebelL as the steps described by you work fine (confirmed by @elfriedegoetz) and it is the correct way of updating credentials, should this be closed? If not, what would be the expected way of fixing this issue?

**Comment by GoebelL** [comment]
The correct steps are confirmed, but in case of reverse steps the error behavior is improvable.
>If not, what would be the expected way of fixing this issue?

Well, it's not the HTTP 500 page as @elfriedegoetz has posted. I think HTTP 401 would be the correct response in case of such failure, which should give back the user a login prompt. It still leaves the given user  locked out, but allows to recover with credentials from second technology manager*) of same organization. 
*) In fact, if we had a fix of issue #23, the platform administrator should then be able to login and resolve this directly.

**Comment by ghost** [comment]
I have found out that there is an issue with `AuthorizationFilter` logic. Basically, if `loggedInUserId` attribute is found then it always assumes that credentials stored in the session are correct and user is not reauthenticated to check if they are still valid (i.e. password might have changed).

https://github.com/servicecatalog/oscm/blob/00a33b798a290c7d116217a2ed10b75c214f0db2/oscm-app-vmware-ui/javasrc/org/oscm/app/vmware/ui/filter/AuthorizationFilter.java#L65-L68

I will refactor the logic so user is always authenticated before executing any controller related logic.

**Comment by elfriedegoetz** [comment]
[Build]
build from 13.11.2018 13:30 tag QA 

Does still not work in reverse steps

**Comment by elfriedegoetz** [comment]
I have understood that the documented order must be adhered to. But a wrong order must not lead to a blocked account.
![login](https://user-images.githubusercontent.com/15209605/48486772-be0c3700-e81c-11e8-92a5-70a7e8bee665.PNG)

**Comment by GoebelL** [comment]
Feature request #227 is targeted to improve the user experience with changing passwords.
