### ISSUE TITLE
Azure controller - subscription stuck in pending state

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#145]
***Observed behavior***
Controller creates a virtual machine in azure along with other resources properly, however after everything is provisioned and running, subscription stays in a pending state.

***Expected result***
After a successful provisioning of a virtual machine in azure, subscription state should change and allow simple operations on a created machine.

**Comment by elfriedegoetz** [comment]
Controller creates a virtual machine in azure along with other resources properly, however after everything is provisioned and running, subscription stays in a pending state and I get the message:

Dear user,

An error occurred while notifying Catalog Manager about the provisioning process for subscription 'AzureARM_Example' for customer 'PLATFORM_OPERATOR' (Instance: 'azure-627a9f8a-43f5-4eb2-b53c-7493dade2f49', provisioning state: 'WAITING_FOR_SYSTEM_CREATION'). 

Reported problem: Part parameters defined as element {http://oscm.org/xsd}getSubscriptionIdentifiers which is not in the schema.

There may be an inconsistency between Catalog Manager, APP, and the application. Please check if the settings for the corresponding instance of the application were changed. To continue automatic processing, please open the following link:
https://estst1.intern.est.fujitsu.com:8881/oscm-app/notify?sid=azure-627a9f8a-43f5-4eb2-b53c-7493dade2f49&controllerid=ess.azureARM&_resume=yes

**Comment by ghost** [comment]
Technical Service has not changed and I have been testing azure controller yesterday without any issues. There might be an issue with your environment.

**Comment by ghost** [comment]
Tested again based on the latest master and it works.

![image](https://user-images.githubusercontent.com/40793157/47209690-3f44eb00-d391-11e8-8cf7-da2b47633e91.png)

![image](https://user-images.githubusercontent.com/40793157/47209700-466bf900-d391-11e8-9c67-c550f5f14adf.png)

**Comment by elfriedegoetz** [comment]
works fine with build from 19.10.2018
