### ISSUE TITLE
Azure controller technical service template

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#146]
Please enhance the [technical service template](https://github.com/servicecatalog/oscm/blob/azure-adapt/oscm-app-azure/resources/TechnicalService_Azure.xml) for the Azure controller
* Correct value for provisioningUrl without place holders and pointing in the APP container
* Provide default values for TEMPLATE_BASE_URL, TEMPLATE_NAME, TEMPLATE_PARAMETERS_NAME
https://raw.githubusercontent.com/servicecatalog/oscm/master/oscm-app-azure/resources/SampleTemplate.parameters.json
https://raw.githubusercontent.com/servicecatalog/oscm/master/oscm-app-azure/resources/SampleTemplate.json
* Other default values where available

**Comment by ghost** [comment]
Should resource group, virtual network, subnet, etc. be filled with some names also? It could be something like myVnet, mySubnet, etc.

**Comment by GoebelL** [comment]
Good default values add information or make things run out of the box. Just add wherever you can find such. Probably that's not the case for those you mention.

**Comment by elfriedegoetz** [comment]
see #145

**Comment by ghost** [comment]
As mentioned in #145 technical service did not change since 18 days: https://github.com/servicecatalog/oscm/blob/master/oscm-app-azure/resources/TechnicalService_Azure.xml

It is not technical service issue.

**Comment by elfriedegoetz** [comment]
works fine with build from 19.10.2018
