### ISSUE TITLE
Enhance VMWare connector to allow for import of VMs

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#148]
Allow for back importing existing VMs to OSCM when creating respective subscriptions.

**Comment by GoebelL** [comment]
Solution idea is to enhance the technical service for allowing the customer to subscribe to already existing VMs in the OSCM marketplace. 
* Add a Boolean parameter ```IMPORT_VM``` that when passing ```true``` tells the VMWare connector to find specified VM in given VCenter cluster and assign it to the created instance. 
* Further, in this import mode ```IMPORT_VM=true``` the provisioning has to fail with respective error in case the specified VM is not found.
* The parameter default shall be ```IMPORT_VM=false``` in which case the create instance request behaves as it is, meaning creating the specified VM.

**Comment by GoebelL** [comment]
The use cases import and modification of existing VMs shall not be mixed. The default technical service template has many parameter options and therefore might not be suitable for the import use case. 
In order to keep things simple, we should introduce a dedicated service template for this feature. This also allows us to provide it as an operational tool, since the VM import is a technical use case and not a required end user function.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/201
