### ISSUE TITLE
Azure: creating instance, parameter "Template Base URL" does not work

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#157]
[Build]
docker 17.7 2018/10/05

[Steps to reproduce]
step 1: create a azure instance
   -> parameter for Template Base URL:
 https://raw.githubusercontent.com/servicecatalog/oscm/master/oscm-app-azure/resources/
instance is created and running
step2: create an other azure instance
-> parameter for Template Base URL:
 https://github.com/servicecatalog/oscm/tree/master/oscm-app-azure/resources/ 
all required files are stored there

[Expected result]
the instance is created and running

[Observed result]
does not work, I get this error message 

Dear user,

The current operation on subscription 'AzureARM_fr3' for customer 'PLATFORM_OPERATOR' has been suspended (Instance: 'azure-fc850184-a88a-4dd0-abc8-5abe13846775').

Reported problem: Azure returned the following error: Template Deployment failed: The creation of the requested resource group failed. The service provider has been informed about the issue.The creation of the requested resource group failed. The service provider has been informed about the issue.

To continue automatic processing, please click the following URL:
https://estst1.intern.est.fujitsu.com:8881/oscm-app/notify?sid=azure-fc850184-a88a-4dd0-abc8-5abe13846775&controllerid=ess.azureARM&_resume=yes

If the problem cannot be solved and the processing cannot be continued, please terminate the subscription and create a new one.

**Comment by ghost** [comment]
Please provide all parameters used to create the subscription so I can reproduce and investigate the issue.

**Comment by elfriedegoetz** [comment]
I set the parameters the way you wrote me:

1.	Technical service can be found at: https://github.com/servicecatalog/oscm/blob/master/oscm-app-azure/resources/TechnicalService_Azure.xml
	 
3.	Regarding some of the parameters required to create the subscription, here are some hints how to fill them:
a.	Subscription ID – can be found at Cost Management + Billing -> Overview -> Subscription ID 
b.	Azure tenant ID – can be found at Azure Active Directory -> Properties -> Directory ID
c.	Azure client ID – in our case it is Application ID of ST-OSCM app. Can be found at Azure Active Directory -> Enterprise applications -> ST-OSCM -> Properties -> Application ID
e.	Azure region location – it is a region of Resource Group filled in next step. For the test we have “SystemTest” and its’ location is “West Europe”.
f.	Resource group name – either existing or non-existing group can be used here. In case group does not exist, ST-OSCM would need to have privileges to create it. I was using existing “SystemTest” group.
g.	Virtual Network name, Subnet name – non-existing names should be used here. They will be created during provisioning.
h.	Virtual Machine Image ID – it is already pre-filled with correct ID. Azure users should know how to get image ID in case they want to use a different one.
i.	Storage Account name – similar to virtual network and subnet, non-existing name should be used here. Something like “testazure999”. In case it exists user has to make sure that it is in the same region as used Resource Group.

**Comment by ghost** [comment]
The issue here is quite different and it is not related to azure connector. 

> step2: create an other azure instance
-> parameter for Template Base URL:
https://github.com/servicecatalog/oscm/tree/master/oscm-app-azure/resources/

You have provided a wrong base URL. It is different from the one that I have provided and the one used in step 1:
https://raw.githubusercontent.com/servicecatalog/oscm/master/oscm-app-azure/resources/

The thing is that the one you have used in step 2, points to the Github UI, rather than raw JSON data. This can be closed.

**Comment by elfriedegoetz** [comment]
Okay I will close the bug
