### ISSUE TITLE
oscm-app-aws  logfile is empty

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#164]
[Build]
 docker  2018/10/23
[Steps to reproduce]
create a file<log4j.ess.aws.properties> in <apache/conf>
[Expected result]
errors are logging in <app-aws.log>
[Observed result]
logfile <app-aws.log> is empty.

**Comment by ghost** [comment]
In the essence, errors are actually logged, but not in every scenario. Errors usually should only be logged by unexpected/unhandled actions. Actions like providing wrong credentials, etc. should not log errors (at most it should be a debug level).

I think that current behavior is correct and in case we would want to log more information overall then it would be an enhancement/feature.

In example this is the place where errors are logged.
https://github.com/servicecatalog/oscm/blob/dbd251fe61def705bb6a9287c6cf7f03dcabbda0/oscm-app-aws/javasrc/org/oscm/app/aws/controller/AWSController.java#L460-L497

**Comment by Crystalzord** [comment]
Some additional logs and changes to log4j templates that allow info logs to be saved in the .log files merged in commit https://github.com/servicecatalog/oscm/commit/37ebb6b0a1e133219b4f8beb7323deefa659ba9a.
