### ISSUE TITLE
changing parameters fails

### ISSUE THREAD

**Issue by raonadeem** [servicecatalog/oscm#173]
Hi,

I have deployed a sample controller and created a technical service with some configurable parameters.
Then I have subscribed for this service using administrator user and assigned that user to the subscription.

But now, when I try to change the parameters value in Configure, it return me the following error;

The subscription could not be changed because the constraints of subscription SAHABA IaaS would be violated. Details: EXCEPTIONID 1540868827864: The provisioning call returned the error code: 1 The user ID is missing or too short (< 5 characters).

I'm trying to change these parameters with administrator user.

Any suggestions please?

**Comment by GoebelL** [comment]
Hi @raonadeem 
The sample controller is meant to showcase the implementation of the APP interface. On each provisioning step it issues emails to the user specified with the subscription parameters. In this technical service the user parameter is defined as user option. This means, the supplier, who is offering the service on his marketplace, can provide this parameter as option to his customers. Check if user option is ticked 
on for the marketable service. If it is, you should find the field to input the user name when creating or modifying the subscription. The sample service validates the user parameter and throws given exception if the user name is omitted or too short. Adapt [the implementation](https://github.com/servicecatalog/oscm/blob/master/oscm-app-sample/javasrc/org/oscm/app/sample/controller/SampleController.java#L394) as you need it.

**Comment by raonadeem** [comment]
Hi @GoebelL 
I had modified the technical service definitions and now used the default sample technical service definition which is working fine now.
Thanks
