### ISSUE TITLE
Steps to integrate with single sign on

### ISSUE THREAD

**Issue by raonadeem** [servicecatalog/oscm#174]
Hi,

What are the steps to integrate oscm with single sign on application like Keycloak?

**Comment by raonadeem** [comment]
Any update on this please?

**Comment by GoebelL** [comment]
Hi @raonadeem 
There is an option for SSO federation with external ID providers based on SAML 2.0. This is available for prior Glassfish versions only. The steps to integrate can be found in the [17.4 Operator's Guide](https://github.com/servicecatalog/documentation/blob/v17.4.0/Development/oscm-doc-user/resources/manuals/installation%2Boperation/en/Operation.pdf), chapter 5.6.

SSO support with OpenID connect is feature candidate for next release. Current options are remote LDAP or internal authentication.

**Comment by raonadeem** [comment]
Hi @GoebelL 
Can you please confirm if OpenID connect has been integrated in oscm latest release?
