### ISSUE TITLE
Crypted Titel of OSCM Administration page

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#180]
![oscm](https://user-images.githubusercontent.com/32158057/48059828-88cb6d80-e1ba-11e8-9185-1a9030c96cc3.JPG)
![oscm](https://user-images.githubusercontent.com/32158057/48059854-9680f300-e1ba-11e8-8222-33d185f7d100.JPG)
OSCM Titel gets overwritten "by Enterprise Service Catalog Manager"

**Comment by GoebelL** [comment]
@uhu133 
This looks weird indeed. Where does this enterprise branding source from? Did you install OSCM or ESCM containers? Or mixed both?  Does it look same with private browsing? I just think, it might be also a browser caching effect.

**Comment by uhu133** [comment]
no branding source
out of the box oscm:latest
.env:
IMAGE_DB=servicecatalog/oscm-db:latest   
IMAGE_CORE=servicecatalog/oscm-core:latest   
IMAGE_APP=servicecatalog/oscm-app:latest   
IMAGE_BIRT=servicecatalog/oscm-birt:latest   
IMAGE_BRANDING=servicecatalog/oscm-branding:latest   
IMAGE_INITDB=servicecatalog/oscm-initdb:latest   
IMAGE_PROXY=servicecatalog/oscm-proxy:latest   
IMAGE_HELP=servicecatalog/oscm-help:latest

**Comment by uhu133** [comment]
It was an cache issue - closed
