### ISSUE TITLE
Fix BES_MASTER_WS jenkins job

### ISSUE THREAD

**Issue by Crystalzord** [servicecatalog/oscm#190]
Jenkins job http://10.140.16.80:8080/job/BES_MASTER_WS/ is failing after some changes in groovy scripts and oscm-app-shell and this needs to be fixed.

**Comment by GoebelL** [comment]
Remaining test errors, such as 
``` 
unexpected XML tag. expected: {http://oscm.org/xsd}getDefaultPaymentConfigurationResponse but found: {http://oscm.org/xsd}getDefaultPaymentConfiguration 
```

**Comment by GoebelL** [comment]
Thanks @kowalczyka. 
Just some unexpected exception - in this case an issue with a mail server - has caused this weird response.
