### ISSUE TITLE
Branding changes without need to restart the related container

### ISSUE THREAD

**Issue by cklitscher** [servicecatalog/oscm#192]
to avoid service interruption there should be provided a way to update a branding package for the marketplace without being forced to stop and start again the container (oscm-app)

**Comment by GoebelL** [comment]
@cworf91 
Please check and describe if an inotify based solution for docker is applicable here. Same shall be applied to shell adapter triggering script import on file system events.

**Comment by GoebelL** [comment]
Hot deploy has been implemented in OSCM 17.9, for branding packages as well as for scripts for the new shell adapter. Restarting containers is no longer required for deploying any changes.

Please note a minor operational change:  The branding package must now be extracted into the target branding folder. For detailed steps please refer to the [Operator's Guide](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/installation+operation/en/Operation.pdf), chapter 9.5 Customizing the Layout of Marketplaces.

Get the new release from DockerHub [here](https://hub.docker.com/r/servicecatalog/oscm-deployer/).
