### ISSUE TITLE
Strange look of Birt reports

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/oscm#20]
[Version] OSCM 17.5.0 2017/10/30
Docker image with TomEE

[How to reproduce]

1. Login to administration portal and to the marketplace
2. Go to Account -> Create report (portal) and to Account -> Reports (marketplace)
3. Click on any report (portal); choose any report from the list (mktpl)

[Expected result]
Shown reports looks as expected

[Observed result]
The report looks weird (screens below)
1. Portal
![portal_report](https://user-images.githubusercontent.com/18006407/32168905-97dbc49e-bd6e-11e7-846f-54c46dd7772f.PNG)

2. Marketplace
![mktpl_report](https://user-images.githubusercontent.com/18006407/32168908-9c0f02d8-bd6e-11e7-9978-078f02e35d54.PNG)

**Comment by grubskim** [comment]
Seems like a certificate problem... Even when report URL uses http, the browser console still shows that https is used. @shimizuf could you maybe take a look?

**Comment by shimizuf** [comment]
I suspect this might be related to #21. Could you please try the following:
* Access the report engine's example report directly in your browser:
* URL: <PROTOCOL>://<HOST_OR_IP>:<PORT>/birt/frameset?__report=test.rptdesign&sample=my+parameter
* For PROTOCOL, HOST_OR_UP and PORT, please use the same that you set in the REPORT_ENGINEURL setting.
* Do you see the **Congratulations!** message?

Also, can you please list these settings?
* BASE_URL_HTTPS
* REPORT_ENGINEURL
* In the report engine container, the value of base_url in the file viewer.properties

**Comment by kwodzynski** [comment]
If the REPORT_ENGINEURL is set to https, the Birt reports work and look fine.
@GoebelL wrote in #21 "only HTTPS is going to be supported for any kind of OSCM access from external host". Closing

**Comment by kwodzynski** [comment]
Tested on 17.5 2017/12/06. The Birt reports look good.
