### ISSUE TITLE
Enable loadbalancer in VMware controller

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#202]

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/205

**Comment by GoebelL** [comment]
The VM load balancer is enabled and working fine. Following classes are available
* org.oscm.app.vmware.business.balancer.EquipartitionHostBalancer
* org.oscm.app.vmware.business.balancer.EquipartitionStorageBalancer
* org.oscm.app.vmware.business.balancer.DynamicEquipartitionStorageBalancer
* org.oscm.app.vmware.business.balancer.DynamicEquipartitionHostBalancer

However this has to be configured directly in the vmware database at the moment.

The VMWare controller UI provides for importing configurations from CSV files. In order to include load balancer configuration, the cluster import and CSV format has be enhanced with respective column.

New format for the cluster CSV: 
```<VCenter>, <Datacenter>, <Clustername>, <Loadbalancer>```

Where ```<Loadbalancer>``` is the XML content of the balancer configuration, like f.e. [this one](https://github.com/servicecatalog/oscm/files/2812305/loadbalancer_xml.txt).

**Comment by GoebelL** [comment]
@gertipoppel 
The cluster format description needs to be enhanced in the VMWare Guide, chapter 2 and Appendix B.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/211

**Comment by cworf91** [comment]
A new loadbalancer can now be configured via a csv file. This requires the following format:
VCenter, Datacenter, Clustername, Load_balancer
It is important that the loadbalancer configuration is passed in the XML format. You can find a sample loadbalancer.xml config at: /oscm-app-vmware/resources/xml/loadbalancer_config.xml.
In the csv file, make sure that the load_balancer configuration (xml) is passed without line breaks. For example, see /oscm-app-vmware/resources/csv/cluster.csv for a valid sample configuration. However, it is important that you provide a valid loadbalancerconfig in the csv file.
