### ISSUE TITLE
Jenkins job for update installation

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#207]

**Comment by Crystalzord** [comment]
Implemented & merged
http://10.140.19.25/fujitsu-bss/jenkinsScripts/commit/e31cf359bc83bf27444ee747d46470b0f0ba8af1

http://10.140.19.25/fujitsu-bss/jenkinsScripts/merge_requests/8

http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Update_oscm_app/

http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Update_oscm_app_shell/

http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Update_oscm_core/
