### ISSUE TITLE
The Birt reports do not work with https access

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/oscm#21]
[Version] OSCM 17.5.0 2017/10/30
Docker image with TomEE

[How to reproduce]

1.    Login to administration portal and to the marketplace
 2.   Go to Account -> Create report (portal) and to Account -> Reports (marketplace)
 3.   Click on any report (portal); choose any report from the list (mktpl)

[Expected result]
The report is shown

[Observed result]
Nothing happens, the report is not shown

**Comment by GoebelL** [comment]
Do you mean HTTPS not HTTP? Not that only HTTPS is going to be supported for any kind of OSCM access from external host. We have successfully tested the reports recently. If reports are not executable for your tests please check following.

Questions
 * Can you create BIRT sample reports from the browser?
 * Are report configuration settings correct
 * In BIRT application within the container, locate the file viewer.properties and check the value Base URL. This has to match with the HTTPS Base URL in the OSCM portal.

**Comment by kwodzynski** [comment]
Hi @GoebelL 

- I can create report from the browser with http and https
- I think my configuration is correct:
1.REPORT_ENGINEURL: http://10.140.18.123:8680/birt/frameset?__report=${reportname}.rptdesign&SessionId=${sessionid}&__locale=${locale}&WSDLURL=${wsdlurl}&SOAPEndPoint=${soapendpoint}&wsname=Report&wsport=ReportPort
2.REPORT_SOAP_ENDPOINT: http://oscm-core:8080/oscm-reporting/ReportingServiceBean
3.REPORT_WSDLURL: http://oscm-core:8080/oscm-reporting/ReportingServiceBean?wsdl

- In fact, I have different values in those two places.
1.configsetting BASE_URL_HTTPS: https://10.140.18.123:8081/oscm-portal/
2.viewer.properties base_url=https://estessbesci8.intern.est.fujitsu.com:8681

So my question is:
Adress for which container should be in the file viewer.properties, for oscm-core or for oscm-birt?

**Comment by shimizuf** [comment]
@kwodzynski Are you actually accessing the portal and report engine with the host name or with the IP address? I see that in viewer.properties the host name is set. If you access the reporting engine with the IP address this may cause issues.

Can you please try the following:
* If you do not have DNS, please try to create an entry in your system's hosts file so you can use the host name to access portal and report engine.
* Change the BASE_URL_HTTPS and REPORT_ENGINEURL config settings to also use the host name
* Does it work then?

**Comment by kwodzynski** [comment]
Hi @shimizuf 
I added dns to my host file, but our polish proxy cannot resolve that.
Should I change base_url in viewer.properties to IP ?

**Comment by shimizuf** [comment]
It's worth trying, yes. But it's possible that the configuration change requires a restart of Tomcat which will end your running container.

I think this might be easier:
Stop the running containers manually on the Docker system. Then edit the var.env file to have the HOST_FQDN variable contain the IP address instead of the host name. Then use Docker Compose to start the containers again. The viewer.properties should then contain the IP address in the base_url.

**Comment by kwodzynski** [comment]
@shimizuf I followed your instruction and now I have base_url set to IP address. But I still can't generate the Birt reports in https. I think I may be caused by number of port (base_url=https://10.140.18.123:8681)
Shouldn't be there port to oscm-core container?

**Comment by shimizuf** [comment]
In the case of the reporting engine the port is correct. Here, base_url must be set to the base URL of the reporting engine.

Now that you have set the base_url to the IP address, can you please try to access the report engine's example report?
https://10.140.18.123:8681/birt/frameset?__report=test.rptdesign&sample=my+parameter

**Comment by kwodzynski** [comment]
Ok, since I have changed REPORT_ENGINEURL to https, I can generate reports. Thanks for your help. Closing

**Comment by kwodzynski** [comment]
Tested on 17.5 2017/12/06. The Birt reports work good.
