### ISSUE TITLE
Provide a link to the VMware web console in Access Info

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#215]
As part of the access info a link to the VMware web console should appear.

Some URLs for info how to implement

https://www.virtuallyghetto.com/2013/02/how-to-access-vsphere-remote-console.html
https://code.vmware.com/docs/142/vmware-remote-console--vmrc--sdk
https://code.vmware.com/samples/637/generate-html-5-vm-console

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/243

**Comment by cworf91** [comment]
![graphic](https://user-images.githubusercontent.com/14805690/56363538-c06c2600-61ec-11e9-9674-d429d14ebfb6.png)
![ConsoleView](https://user-images.githubusercontent.com/44837963/56359612-58b0dd80-61e2-11e9-8e16-3748d7176107.PNG)
