### ISSUE TITLE
VMWare custom tab 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#216]
AWS, OpenStack and Shell connectors provide for displaying basic server information in the custom tab of subscription details. Same is needed for the VMWare integration.

**Comment by cworf91** [comment]
![vmware_customtab](https://user-images.githubusercontent.com/14805690/55418908-ef8b6200-5573-11e9-84cc-31c2d493344e.png)

**Comment by GoebelL** [comment]
Just ignore the names used. Of course the tab name is configurable by the supplier.

**Comment by GoebelL** [comment]
This has been integrated with OSCM v17.10.
