### ISSUE TITLE
Ping for VMWare

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#217]
Relates to #212 
Relates to [respective branch on oscm-interfaces](https://github.com/servicecatalog/oscm-interfaces/tree/feature/connectivity-tests)

**Comment by adamczykba** [comment]
@GoebelL Can I ask You to provide german and japanese translations for:

- Validate Settings
- Check Connection

**Comment by GoebelL** [comment]
Hi @adamczykba 
Just add the messages in English to all bundles. I'll walk through that later together with @gertipoppel.
