### ISSUE TITLE
SOAP API call getAvailablePaymentTypes() always returns null

### ISSUE THREAD

**Issue by victorhrsilva** [servicecatalog/oscm#22]
[Version]
OSCM Tomee 17.5 2017/10/27 

[How to reproduce]
* Try to save payment configuration via SOAP API call as a Supplier

`savePaymentConfiguration(
                        anySetOf(VOPaymentType.class),
                        anyListOf(VOOrganizationPaymentConfiguration.class),
                        anySetOf(VOPaymentType.class),
                        anyListOf(VOServicePaymentConfiguration.class))`

* For the `SetOf VOPaymentType` use the method  

`Set<VOPaymentType> paymentSet = accountService.getAvailablePaymentTypes();`

[Expected result]
Call of getAvailablePaymentTypes returns the list of payment types for which the customer organization of the calling user can define payment information.

[Observed result]
It is always returning null even if the Supplier already has the payment types set:

![image](https://user-images.githubusercontent.com/24247646/32221958-bf953b5e-be37-11e7-8edd-846944e6f80b.png)

[Error message]
User [10345] response failed: com.sun.xml.internal.ws.fault.ServerSOAPFaultException:Client received SOAP Fault from server: The transaction has been marked rollback only because the bean encountered a non-application exception :org.oscm.internal.types.exception.IllegalArgumentException : EXCEPTIONID 1509440897760: Parameter defaultConfiguration must not be null.
[....]
 while invoking public boolean org.oscm.webservices.AccountServiceWS.savePaymentConfiguration(java.util.Set,java.util.List,java.util.Set,java.util.List) throws org.oscm.types.exceptions.ObjectNotFoundException,org.oscm.types.exceptions.OperationNotPermittedException,org.oscm.types.exceptions.OperationPendingException with params [null, [org.oscm.vo.VOOrganizationPaymentConfiguration@6bbf4f73, org.oscm.vo.VOOrganizationPaymentConfiguration@10cf5fe5], null, [org.oscm.vo.VOServicePaymentConfiguration@72ecbc22, org.oscm.vo.VOServicePaymentConfiguration@64391e19, org.oscm.vo.VOServicePaymentConfiguration@75ec113a, org.oscm.vo.VOServicePaymentConfiguration@1fb64815, org.oscm.vo.VOServicePaymentConfiguration@8acfa6d, org.oscm.vo.VOServicePaymentConfiguration@2449f4b7]]. Please see the server log to find more detail regarding exact cause of the failure.com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(Unknown Source)

**Comment by grubskim** [comment]
The method for retrieving the payment types was ignoring the "Invoice" type. Changed it ot retrieve all types.

**Comment by victorhrsilva** [comment]
[Verified at]
OSCM Tomee 17.5 2017/11/02

[Status]
Issue fixed
