### ISSUE TITLE
Ping - Enhance APP UI to provide for connectivity tests

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#223]

**Comment by GoebelL** [comment]
Display error message in pop-up needed for handling lengthy messages.

**Comment by adamczykba** [comment]
@GoebelL 
Two questions regarding this one:

1. Right now error message is displayed in the following manner"
![obraz](https://user-images.githubusercontent.com/47355402/52940254-6246d200-3366-11e9-8693-f5ddaab50562.png)

Do You think that it is really needed to implement the popup on top of that?

2. If we had to implement the popup, what exactly do You expect to be visible in it? (error message/cause/stacktrace)?

**Comment by GoebelL** [comment]
@adamczykba 
The purpose of this connection tests is to support the user in case if there are problems with setup. On the the other hand, the generic error message cannot provide much help to the user for resolving such. Therefore the UI needs to provide more details information from the causing error. 
In order to keep things simple as possible, the connection button should bring up the result within a text popup. In case of error, this should show the error with exception trace. The message in the header is not necessary. This ping function should be handled locally and instantly, not impacting the surrounding page. 
The buttons layout is probably in progress. They'll look fine, if you adjust the widths with the text labels and leave some space between them.
