### ISSUE TITLE
Remove organizations (and users)

### ISSUE THREAD

**Issue by fabiorauber** [servicecatalog/oscm#231]
I'm probably missing something here, but I can't find out how to remove organizations (and users) from OSCM. The Operator's Guide only shows how to create them, and after some time digging into the interface, I couldn't find a way to do it. Is it possible?

**Comment by GoebelL** [comment]
Yes. Basically everything that is created in OSCM can be deleted again. However, there are a few exceptions. Organizations with roles cannot be removed and their roles cannot be revoked. 
Note that users can be deleted by their administrator and customer organizations can be deleted via API.

**Comment by fabiorauber** [comment]
And how do I delete (or edit) an organization Administrator? Like, when I typed in the wrong e-mail?

**Comment by fabiorauber** [comment]
Hi @GoebelL Is there a way for the PLATFORM_OPERATOR to remove an user from an organization?

**Comment by GoebelL** [comment]
Hi @fabiorauber 
Administrators can delete users of their organization. Any user of the PLATFROM_OPERATOR organization, who has administrator role can do this. OSCM provides multi-tenancy with respective isolation. Therefore the user administration is scoped on organization level. Further questions? I am happy to answer where I can.
