### ISSUE TITLE
Error while trying to refresh :8881/oscm-app configuration page after clicking any submit button.

### ISSUE THREAD

**Issue by Crystalzord** [servicecatalog/oscm#233]
**Version Info**
17.9
 
**Describe the bug**
After clicking "Check connection" button or save configuration button I am unable to refresh the page using f5 (due to re-submit request). If I try to do so, it ends up in error and to get back to https://10.140.18.99:8881/oscm-app/default.jsf page I have to re-enter this in the browser's address tab.

**How to Reproduce**
1. Go to https://10.140.18.99:8881/oscm-app/default.jsf
2. Change any text field
2. Click on any save configuration button
4. Try to refresh the page.

**Observed behavior**
Browser asks if I would like to retry to submit the form. If I click yes than I end up with error page.

**Expected behavior**
A page refresh works and I get the https://10.140.18.99:8881/oscm-app/default.jsf page.

**Comment by adamczykba** [comment]
Closed as being redundant with more generic #234
