### ISSUE TITLE
Improve ping functionality related UI

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm#240]
**Summary**
Currently, UI related to check connection for specific controller is a little bit confusing. It should be enhanced so that user understand what issues is he facing of.

**Details**
Check connection button should be visible for every controller definition - it should be enabled/disabled depending on the canPing method result.
Additionaly message which is now displayed for every controller when Check connection button is unavailable shoud be moved from the top of the page next to the button (warning icon displaying the details of the problem when clicked).
Messages related to Check Connection button result should stay in the top part of the page.

**Acceptance criteria**
1. No error message related to checking connection possibility in the top of the page.
2. Check Connection button displayed (enabled/disabled) for every controller configuration.
3. In case of button is disabled, warning icon displayed next to it - clicking on warning icon should open the popup with detailed message describing the issue 

**Additional context**
Exemplary screen: 
![acceptance](https://user-images.githubusercontent.com/14541935/54027504-1b4c3f80-41a2-11e9-8049-29078600da85.jpg)

**Comment by GoebelL** [comment]
Ok, but instead of disabled buttons and warning icons just put a label here "Not configured.".

**Comment by adamczykba** [comment]
@GoebelL But what if controllers is configured, but exception will be thrown during checking the settings? Should it also display this 'Not configured' label in this case?

**Comment by adamczykba** [comment]
Closed with #245
