### ISSUE TITLE
Oscm-app buttons look and feel

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm#241]
**Version Info**
v17.10

**Describe the bug**
Buttons in main oscm-app configuration looks and behaves differently than in oscm-portal. There is no mouseover effect and clicking them looks like nothing has happened.

**How to Reproduce**
1. Go to oscm-app main page
2. Move cursor over and click the 'Save Configuration' button

**Observed behavior**
No cursor change, no button change, clicking leads to dispalying frame inside the button for a while.

**Expected behavior**
Go to oscm-portal and check any single button look and feel.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by adamczykba** [comment]
@kowalczyka 
As discussed earlier, this task will include unifying button styling throughout oscm-app module only.
