### ISSUE TITLE
Split off OSCM external interfaces to seperate repository

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#25]
A prerequisite for mavenizing the REST API and Provisioning adapters, dependencies like external interfaces need to be put on maven as well. 

First tasks (please complete)
1. Copy projects in separate repository oscm-external-interfaces
2. Maven build project artifacts
3. Artifacts as releases
4. Adapt OSCM build
5. Adapt docker build
6. Adapt jenkins jobs, CE and EE
...

x. Clean-up: Remove copied projects and obsolete build source from oscm
y. Create oscm-external-interfaces readme cross-linked with oscm readme

**Comment by DawidCh** [comment]
Done
https://github.com/servicecatalog/oscm-interfaces
