### ISSUE TITLE
Reintroduce SonarQube support

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm#255]
**Summary**
It would be helpfull to check is SonarQube actually works, and if not - reimplement it so it could be of use.

**Details**
Aside from simply implementing sonar support, it would be good to enforce that quality gate has to pass for PR to be merged. That will ensure proper code quality on new code.

**Acceptance criteria**
- [ ] SonarQube is performed after every push (TBD: all branches, or master only?)
- [ ] PR is not allowed to be merged if quality gate of Sonar does not pass

**Additional context**
- it could be as well replaced with SonarCloud (OS version of SonarQube)

**travis.yml**

![obraz](https://user-images.githubusercontent.com/47355402/54695270-eccb4e80-4b29-11e9-9cb3-bca2c22c2c68.png)
![obraz](https://user-images.githubusercontent.com/47355402/54695235-e210b980-4b29-11e9-8196-082ffa7575e7.png)

**Comment by GoebelL** [comment]
Not in focus.
