### ISSUE TITLE
Ping button for OpenStack not enabled

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#258]
**Version Info**
17.10+

**Describe the bug**
Ping button for OpenStack doesn't enable although all settings have been provided.

**How to Reproduce**
* Install OSCM with sample data
* Open _https://&lt;FQDN&gt;:8881/oscm-app-openstack_ and
* Login with default service manager (supplier@adfs.com) 
* Configure required OpenStack settings
* Re-login as administrator to  _https://&lt;FQDN&gt;:8881/oscm-app_

**Expected behavior**
Settings are retrieved with credentials from DB. Ping button for OpenStack is enabled.  

**Observed behavior**
Attempt is made to retrieve settings with credentials from current user session. This fails for admininstrator, respectively any user other than supplier@adfs.com. Ping button for OpenStack remains disabled.

**Additional context**
From docker logs:
03/22/2019_14:58:21.775 FSP_INTS-BSS: ERROR: ThreadID https-jsse-nio-8881-exec-10: AppConfigurationCtrl: 70320: This controller does not support ping functionality
org.oscm.app.v2_0.exceptions.ConfigurationException: Unable to get controller settings
        at org.oscm.app.v2_0.service.APPAuthenticationServiceBean.authenticateUser(APPAuthenticationServiceBean.java:196)
        at org.oscm.app.v2_0.service.APPAuthenticationServiceBean.getAuthenticatedTMForController(APPAuthenticationServiceBean.java:116)
        at org.oscm.app.v2_0.service.APPAuthenticationServiceBean.authenticateTMForController(APPAuthenticationServiceBean.java:97)

**Comment by Crystalzord** [comment]
This issue applies also to VMWare controller, since we used the same logic. That function takes the authentication data from current user session, so canPing() works only for user that provided settings for the controller. Should we have the same controller settings for every user or should the settings be individual and unique for each user?

![Controller-get-settings](https://user-images.githubusercontent.com/19170783/55076846-b5632180-5096-11e9-897f-83e64dcbcfa2.PNG)

**Comment by GoebelL** [comment]
**Fix Summary**

1. The session user dependency has been removed. The functionality is available to the platform administrator now. 
2. The logging has been fixed. On each access to APP UI many error stack traces were written in the log file. However it's a very valid case that connections are not configured - f.e. because respective controllers are not used. In such a case the logging is very misleading for the operator - the file must not be blown with error entries. 
Now respective errors are logged only when the connection is requested by the user - using the `test` button in the APP UI.

3. The `canPing` method is no longer querying database settings. The the settings completeness check is performed in the `ping` method. 
4. Error handling was less helpful as given message were not adding information. Now the message include names of settings which are missing and stack trace of causing exception of connection errors.
