### ISSUE TITLE
Customer menu entries do not work for administrator (with supplier/tech provider role)

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#26]
[Version] OSCM 17.5.0 2017/11/02
Docker image with TomEE

[How to reproduce]
1.    log in as platform operator 'administrator', 
      who is Supplier/Tech Provider 
      (this is necessary due to issue https://github.com/servicecatalog/oscm/issues/23)
2.   select menu 'Manage VAT rates' or any other 'Customer' menu item
     ('Customer' menu is visible because of role change)

[Expected result]
VAT rates can be managed

[Observed result]
error 'You do not have sufficient authorities to view the requested page.'

[Details]
This would normally not be a problem, but since the 'administrator' is forced to be Technical Provider as well as Supplier, these menus are shown.
Nonetheless, authorities should be correct, if 'administrator' is service manager and technology manager. So the error message should not happen

**Comment by grubskim** [comment]
It seems to be working fine:
![issue26](https://user-images.githubusercontent.com/14539765/32337210-a3c190d8-bff1-11e7-832d-8976c5fee442.PNG)
Please check if you have the proper roles for the administrator user in the "manage users" menu (after you set the proper organization roles)
