### ISSUE TITLE
AWS Subscription in pending state forever when wrong AMI ID given.

### ISSUE THREAD

**Issue by Crystalzord** [servicecatalog/oscm#263]
**Version Info**
Open Service Catalog Manager 17.10

**Describe the bug**
When creating a subscription to AWS EC2 service with wrong AMI ID the subscription stays in pending state forever, giving no logs and no e-mail updates about its status (only create subscription log and email is received)

**How to Reproduce**
1. Login as Technology Provider
2. Import TechnicalService AWS template
3. Define the AWS service and publish on marketplace.
4. Subscribe to AWS but give a non existing AMI ID.

**Observed behavior**
The subscription is created and stays in pending state forever.

**Expected behavior**
Some validation is performed (for example check if the specific AMI ID is available for selected Region) and the subscription is not created / terminated and proper e-mail with information is sent.

**Comment by GoebelL** [comment]
Please check what are the options to improve the error handling on the controller side.

**Comment by Crystalzord** [comment]
This issue appears, as many other pending forever issues only when controller is not configured correctly (different user running aws service and different user configured as AWS controller owner).

Closing as not relevant.
