### ISSUE TITLE
Azure controller: status tab does not work

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#272]
**Version Info**
docker build 4.4.2019

**Describe the bug**
![azure](https://user-images.githubusercontent.com/15209605/55617864-5b004a00-5795-11e9-8b55-bfb8e26eba64.PNG)

the table is empty
For VMware it looks fine

![vmware](https://user-images.githubusercontent.com/15209605/55618177-2a6ce000-5796-11e9-8e7c-d316e3b8c117.PNG)

**Comment by GoebelL** [comment]
The feature is not implemented for azure controller yet.

**Comment by GoebelL** [comment]
Added feature request https://github.com/servicecatalog/oscm/issues/274
