### ISSUE TITLE
AWS Subscription is in pending state forever even when instance is provisioned properly!

### ISSUE THREAD

**Issue by Crystalzord** [servicecatalog/oscm#273]
**Version Info**
OSCM 17.10

**Describe the bug**
As the tittle says - even when the instance is up and running with checks completed on AWS EC2 Service console, the subscription still stays in pending state!

**How to Reproduce**
1. Login as Technology Provider
2. Import TechnicalService AWS template
3. Define the AWS service and publish on marketplace.
4. Subscribe to AWS and give properly working parameters.

**Observed behavior**
See the subscription: in logs the create instance is triggered, on aws ec2 the instance is being created. After it is up and running there is no further information in the logs and subscription stays in pending state forever.

**Expected behavior**
Subscription changes it's status to ready after the EC2 instance is up and running.

**Screenshots**
Example working configuration for me:
![Example working config](https://user-images.githubusercontent.com/19170783/55624589-bdae1180-57a6-11e9-8baf-b4174d4f339b.PNG)

Logs from instance creation:
![Creation logs](https://user-images.githubusercontent.com/19170783/55624608-c9013d00-57a6-11e9-835f-fd388ec63879.PNG)

AWS Console shows that instance is finally up and running:
![Aws console running instance](https://user-images.githubusercontent.com/19170783/55624619-d1597800-57a6-11e9-9e78-c7498618af45.PNG)

In the OSCM, the subscription stays in pending state anyway.
![Pending anyway](https://user-images.githubusercontent.com/19170783/55624648-e6cea200-57a6-11e9-8d24-288a7c1edc30.PNG)

**Additional content**
in the app-core.log there are more information about this.
![obraz](https://user-images.githubusercontent.com/19170783/55624880-8855f380-57a7-11e9-8311-1a1483b476b0.png)

**SEE FULL LOG** [app-core.log](https://github.com/servicecatalog/oscm/files/3047676/app-core.log)

**Comment by GoebelL** [comment]
@Crystalzord 
Usually the information can be found from causing exceptions of such log entries. Please check the unauthorized access entries and if the AWS controller connection is properly configured: Does the configured user have the required roles as administrator, service manager and technology manager?

**Comment by Crystalzord** [comment]
You were right Lorenz, I did not configure the controller settings properly...
Closing as not relevant.
