### ISSUE TITLE
Status tab for azure controller

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#274]
**Summary**
Provide custom tab with status information for Azure instances in the My Subscription page, in they way like it's provided for VMWare service subscriptions.

**Acceptance criteria**
Basic informaton is displayed in the table 
* Name
* Instance ID
* Instance Type
* Status
* IPs (private and public IPs if present)
* Server Information
* Technical Details

**Additional context**
See VMWare service subscriptions as reference.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-app/pull/119
