### ISSUE TITLE
Chrome busy cursor with many marketplace operations

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#28]
[Build] 17.5 2017/11/02

[Steps to reproduce]
Using Chrome only:
1.   log in as customer to marketplace
2.   click on ACCOUNT/Subscriptions or any other menu item in ACCOUNT

[Expected result]
Subscriptions are listed and curser goes from turning to pointing hand

[Observed result]
Cursor keeps turning unless moved

[Details]
This happens during many other operations too. It is confusing, and makes user think that operation is still executing.
moved from https://github.com/servicecatalog/development/issues/803

**Comment by Crystalzord** [comment]
Tested on 17.9 2019/11/22. This issue still exists on chrome.

**Comment by GoebelL** [comment]
The marketplace UI has been redesigned in OSCM v19. This issue doesn't exist anymore.
