### ISSUE TITLE
VMware csv upload failed

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#287]
**Version Info**
docker build 10.4.2019

**Describe the bug**
the sample csv file ...oscm/tree/master/oscm-app-vmware/resources/csv/cluster.csv does not work.

**How to Reproduce**

1. Go to ..oscm-app-vmware
2. upload the cluster.csv file of the sample

**Observed behavior**
Error message:
"Error during CSV configuration file upload. Incorrect data format. Expected: 4 columns, got: 3."

**Expected behavior**
upload works fine

**Additional context**
Samples missing for the other csv files in ...oscm/tree/master/oscm-app-vmware/resources/csv/

**Comment by cworf91** [comment]
Example works as expected.
