### ISSUE TITLE
where are the licenses found for docker version of oscm?

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#29]
[Build] 17.5 2017/11/02

We used to provide license files with the install pack. Where is this information found with docker containers?

**Comment by grubskim** [comment]
@SylviaDehn Currently it is not packaged anywhere. If you think it should be, please let us know the proper location for it.

I guess you mean [this](https://github.com/servicecatalog/development/blob/master/LICENSE) license ?

**Comment by GoebelL** [comment]
We won't package those files as before. The target delivery path is the docker registry.
We will place a respective note at the end of the full description on the registry page. 

Example:

**License**
This software is provided under [Apache 2.0 License](https://github.com/servicecatalog/oscm/blob/master/LICENSE). View the [NOTICE file](https://github.com/servicecatalog/oscm/blob/master/NOTICE.txt) for the third party software contained in this image.

**Comment by GoebelL** [comment]
See #31
