### ISSUE TITLE
Sort list by service names in admin portal

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#309]
**Summary**
Item lists needs to be sorted in order to find the items if you have more than 10 of them

(A) customers  and organizations

1. manage suppliers
2. export billing data
3. manage customer
4. manage VAT rates
5. view subscription
define price model for customer

(B) marketable services
1. update service 
2. copy service 
3. delete service 
4. define up/downgrade
5. define publishing
Activate or deactivate
define price for service
define price model for customer
delete for customer

(C) technical services
1. update service definition
2. delete service definition

**Comment by farmakiG** [comment]
Closed all subtasks.

**Comment by elfriedegoetz** [comment]
sorting is missing for:
Marketable service
    -define service
    -define publishing options
