### ISSUE TITLE
Wrong encoding of "umlaute"

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#311]
German "Umlaute" are displayed wrong at

1 Profil name, first name
2. Subscription Name
3. Subscription Reference

**Comment by GoebelL** [comment]
Related with https://github.com/servicecatalog/oscm/issues/247

**Comment by GoebelL** [comment]
**How to Reproduce**
Steps to reproduce the behavior:
1. Login to marketpalce portal
2. Go to 'Home>Account>Profile'
3. Open tab 'Organization Data'
4. Change address containing non-ASCII chars (ä, ü, ö, ß)
5. Save 

**Expected result**
All characters are correctly displayed as entered.

**Observed result**
Text is garbled with broken encoding for special characters.

**Comment by GoebelL** [comment]
I debugged a little in the portal and found that the encoding already brakes in the UI. The model backing beans already retrieve garbled values from the JSF views. The HTML header in rendered output does contain respective directive to use a UTF-8 charset.
``` <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">```
It might be necessary to add information to use UTF-8 encoding on every request. This could be implemented with a servlet filter that is added in the filter chain configured in the descriptor of the oscm portal web application.

@farmakiG 
Please also check APP and the controller UIs.

**Comment by farmakiG** [comment]
Ok, thank you, I have already reproduced it. I will check your suggestion

**Comment by farmakiG** [comment]
Hallo Lorenz,

Ich kann aus einem Grundn noch nicht debuggen, aber ich habe gemerkt dass es nur bei der profile.jsf von marketplace auftritt.
Im Classic portal profile.jsf das Speichern mit Umlaute funktioniert, so wie die Umlaute in anderen Seiten beim Marktplatz, zB wenn man eine neue billing address mit Umlaute definiert, das funktioniert auch im Marktplatz. Ich werde weiter analysieren.

**Comment by elfriedegoetz** [comment]
"Umlaute" for Subscription Name does not work, if try to subscribe to a vm

**Comment by elfriedegoetz** [comment]
![umlaute](https://user-images.githubusercontent.com/15209605/59030107-4eb16f80-8860-11e9-810d-3e42b77920da.PNG)

**Comment by elfriedegoetz** [comment]
for Profile data it works fine

**Comment by farmakiG** [comment]
The corrupted error message in the screenshot of Elfriede, has been fixed in the oscm-commons repository in commit: 
https://github.com/servicecatalog/oscm-commons/commit/705eef6da174b2949c5a1abd4520061a1c2ac460
