### ISSUE TITLE
Delete Customer menu has a wrong help link

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#316]
**Version Info**
v18.0

**Describe the bug**
In the administrator portal the online-help context link for the delete customer page is boken.

**How to Reproduce**
1. Login to the administrator portal
2. Select `Pricemodel>Delete for Customer` from menu
3. Click "?" 

**Expected Result**
Clicking on the "?" leads to the context help page. Link points to `.../oscm-portal-help/help/en/help/tasks/priceModel_customer_delete.htm` which exists. 

**Observed Result**
Clicking on the "?" gives a 404. Link points to ```.../oscm-portal-help/help/en/help/tasks/priceModel.customer_delete.htm``` which does not exist (note, there is a dot in the URI after 'priceModel').

**Comment by elfriedegoetz** [comment]
tested ok with Build 18.06.2019
