### ISSUE TITLE
Possibility of update database on Docker image

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/oscm#33]
When we run new Docker image with OSCM, we have new, pure database.
What if client has a database with a lot of data and he cannot "clean" his db?
We need possibility to update instead of purge the Database.

**Comment by GoebelL** [comment]
Databases are not purged by updating OSCM. Only the schema is upgraded to latest model version from the init scripts invoked on container start. The user mounts his persistence volumes in the database container at a defined location. For an update he pulls the containers from the registry and starts them or runs the provided deployer script for this purpose. In any case the contained data is preserved throughout the OSCM life-cycle.

**Comment by GoebelL** [comment]
See https://github.com/servicecatalog/oscm-dockerbuild.

**Comment by shimizuf** [comment]
Correct. initdb does not overwrite or purge data. It updates the database schema and - this is the only exception - overwrites the config settings. The latter is intended. I think this can be closed.
