### ISSUE TITLE
Operation failed upon service selection in Service Price Model page.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#336]
**Version Info**
OSCM v18.0

**Describe the bug**
In the "Price Model-> Define for Service" page, an "Operation failed" message appears if the user first selects a Service and then switches again to the default option "--Select one--". The page is not accessible anymore. Exactly the same behavior appears upon service selection in the "Price Model->Define for Customer" page. 

**Screenshots**
![Screenshot Operation Failed.png](https://images.zenhubusercontent.com/5cde81448d9e9e5f0d4a7541/066cad6b-29b1-4881-8164-39b3d8a3b41c)

**How to Reproduce**
1. Go to 'Price Model->Define for Service' page in the classic portal. The dummy option "--Select one--" is displayed.
2. Select a service, e.g. "AService" from the Service ID dropdown menu.
3. Re-select "--Select one--". 

**Observed behavior**
 "The operation failed" message appears and the page is no longer accessible.

**Expected behavior**
The option "--Select one--" gets selected and the page is accessible.

**Additional context**
"Price Model ->Define for Customer" page.

**Log file in oscm-core:/logs**
[juli.2019-06-12.log](https://github.com/servicecatalog/oscm/files/3281717/juli.2019-06-12.log)

**Comment by elfriedegoetz** [comment]
tested ok with Build from 18.06.2019
