### ISSUE TITLE
operation failed when updating aws managing organization id

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#35]
[Build] 17.5 2017/11/07

[Steps to reproduce]
1. log in to aws controller as administrator (who is also technology provider and service manager)
2. change UserID, key and password
3. save configuration (this results in java.lang.reflect.UndeclaredThrowableException, but ignore this)
4. as platform administrator change organization id for aws in
http://estst1.intern.est.fujitsu.com:8880/oscm-app/

[Expected result]
change is carried out

[Observed result]
operation failed

[Details]
This step is necessary to update the controller manager.

**Comment by GoebelL** [comment]
Related with issue #23. Consider a combined fix.

**Comment by ghost** [comment]
[Build] 2017/11/09 seems to work now. Or this only happens sometimes. Closing with worksforme
