### ISSUE TITLE
Register customer with existing administrator user data

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#359]
**Summary**
Much same as #358 but for the register customer case.
For registering a new customer the initial organization admin is created with an existing user in the OP by overtaking his user data.
 
**Details**
It's only UI implementation (rest is part of #358)
* When creating a new customer  in SSO mode, the administrator only provides a User ID for the initial customer administrator user. Other fields are removed from Administrator data section in the customer registration page.
* User details are retrieved from the oscm-core IdentityService (mocked):
``` VOUserDetails IdentityService#loadUserDetailsFromOIDCProvider(String userId, String tenantId) ```

**Acceptance criteria**
- [ ] No user data input on create oranization page
- [ ] Initial organization admin is created successfully with JSON data from TenantService
- [ ] email is sent out the configured administrator email address
- [ ] User details are validated and user-friendly messages are returned

**Additional context**
Later

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/364

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/367
