### ISSUE TITLE
string for version Info is wrong

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#361]
**Version Info**
PRIVATE-BUILD-ON-20B07902D6082019/07/09
![about](https://user-images.githubusercontent.com/15209605/61281454-f43df400-a7b9-11e9-9bf0-f282f84982a5.PNG)

**Comment by GoebelL** [comment]
@elfriedegoetz 
I am not facing such effect right now. Does this appear permanently or only in the first time after deployment when logging into the portal? Note that it might take a few seconds until the OSCM logo image shows up.

**Comment by elfriedegoetz** [comment]
It happens after deployment the first time you log on to the portal. The problem persists. I have noticed that when I log off and log on again, the OSCM logo appears correctly.
