### ISSUE TITLE
Test SSO with multiple tenants

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm#363]
**Summary**
Current SSO development (using OIDC) adapted OSCM to work with default tenant. Multiple tenant scenario should be investigated , verified and impoved if necessary.

**Details**
Multiple tenants scenario should be tested considering:
- sending tenant information (tenantId) within the requests to oscm-identity
- using different tenants when creating organization
- using different tenants when creating marketplacte

**Acceptance criteria**
TBD

**Additional context**
N/A

**Comment by GoebelL** [comment]
See https://github.com/servicecatalog/oscm/issues/365

**Comment by GoebelL** [comment]
Fixed OSCM portal filters to handle the tenantID. 
https://github.com/servicecatalog/oscm/pull/384

Status: Issue on token validation remains: https://github.com/servicecatalog/oscm-identity/issues/23

Todo: Retest authentication with custom tenant user after this bug is fixed.

**Comment by GoebelL** [comment]
1. Retest with custom tenant

**Comment by GoebelL** [comment]
**Tested**
1. Basic operations with different tenants, login, logout from oscm portal and marketplace. 
2. Create organization and register customer with non-default tenant

**Result**
Basic operations work fine. Issues detected: [oscm#524](https://github.com/servicecatalog/oscm/issues/524) and [oscm-identity#66](https://github.com/servicecatalog/oscm-identity/issues/66).
