### ISSUE TITLE
Retrieve user data for existing user

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#366]
**Summary**
Retrieve the user data from user info endpoint for given user specified with user and tenant id.

**Details**
* Implement 
``` VOUserDetails IdentityService#loadUserDetailsFromOIDCProvider(String userId, String tenantId) ```. Integrate call to oscm-identy to retrieve user data for the given user.

* Integrate identity service based on in issue [#8 Retrieve user data for existing user](https://github.com/servicecatalog/oscm-identity/issues/8) in oscm-identity repo.

**Acceptance criteria**
- [ ] User data is retrieved and valid
- [ ] Mandatory settings are validated (e.g. Email address)
- [ ] Error cases handled properly (e.g. HTTP errors 404, 500 etc. retruned from oscm-identity endpoint are mapped in OSCM exceptions with user-friendly messages and logging)

**Additional context**
[oscm-identity issue #8](https://github.com/servicecatalog/oscm-identity/issues/8)

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/410
