### ISSUE TITLE
Clean up SAML2 related source code

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#372]
**Summary**
Clean up SAML2 related source code.

**Details**
E.g. remove 
* oscm-saml2-api
* IdPLogoutFilter
* IIdPResponseFilter
* SAMLCredentials

**Acceptance criteria**
- [ ] SAML related source code is removed.
- [ ] Build is green
- [ ] Tests are green (Unit, IT and WS)

**Additional context**
N/A

**Comment by cworf91** [comment]
I guess this task is done. 
See pr:
https://github.com/servicecatalog/oscm-commons/pull/40
https://github.com/servicecatalog/oscm-dockerbuild/pull/222

**Comment by GoebelL** [comment]
Yes, I agree.
