### ISSUE TITLE
Reimplement google code formatter + auto copyright headers

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm#385]
**Summary**
Auto code formatting/auto copyright headers were introdueced in #242 , but due to various problem it was disabled entirely. Now it's time to reintroduce it properly

**Details**
After several discussions about how formatting workflow should look like, we've come to an agreement that resulted with undermentioned resolutions:
- code formatting must be triggered only **after** merge to master. This is considered basically the last step
- code formatting must be triggered only once for each merge to master
- *post-merge* actions have to be executed by *technical user account*
- technical user mentioned above is the only user that has permission to make changes on master branch without need of conducting PR flow

**Acceptance criteria**
- [ ] code formatting mechanism is reenabled
- [ ] code formatting process is triggered **only once** and **only after merge to master**
- [ ] code formatter causes the code to be formatted with Google Java Formatting style
- [ ] code formatter causes missing copyright headers to be automatically prepended 
- [ ] code formatter uses technical user to commit changes to the master branch

**Additional context**
- [How to create machine users @ GitHub](https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users)
- implementation should be simmilar as in https://github.com/servicecatalog/oscm-rest-api/issues/122

**Comment by GoebelL** [comment]
I think this was done already. Code formatting is active and working well. Reopen if you consider any issues.
