### ISSUE TITLE
Set UP issue

### ISSUE THREAD

**Issue by divz1010** [servicecatalog/oscm#389]
Hi,
   I tried to run this code(i am new to java) added all files into my eclipse workspace it showing all jar files missing, let me know how to solve

**Comment by GoebelL** [comment]
Hi,
Run the ANT task BUILD.LIB as described in the [Readme fo this repo](https://github.com/servicecatalog/oscm/blob/master/README.md#building-the-application) to fetch the dependencies from central maven.

**Comment by divz1010** [comment]
thanks
