### ISSUE TITLE
WebService authentication for OIDC integration

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#394]
**Summary**
Investigate WebService authentication Implemented with access token.

**Details**
* Target is to use resource owner password grant to authenticate with OSCM. See https://tools.ietf.org/html/rfc6749

* Investigate what is necessary to adapt for token based authentication with OSCM Web Services. See ```org.oscm.webservices.handler.LoginHandler``` 

**Acceptance criteria**
Todo

**Comment by GoebelL** [comment]
Related with #405

**Comment by GoebelL** [comment]
Basically the OSCM SOAP API idenitity relies on OASIS' Web Service Security standard. It usesusername token based authentication. This is handled at two sides. 
* Clients have to include user key and password credentials in the SOAP message. 
* Login service that is configured with the JAAS context has to hande the authentication to the realm.

Client handler:
org.oscm.app.v2_0.BSSWebServiceFactory

Login module
* WSValidator is configured in openejb-jar.xml to handle login at login service obtaining the username token  
* Authentication

**Comment by GoebelL** [comment]
Basically the OSCM SOAP API idenitity relies on OASIS' Web Service Security standard. It usesusername token based authentication. This is handled at two sides. 

* Clients include user key and password credentials in the SOAP message. 
* Login service that is configured with the JAAS context (jaas.config file) handes the authentication to the BES realm.

Client handlers:
* org.oscm.app.v2_0.BSSWebServiceFactory
* org.oscm.app.dao.BesDAO
* org.oscm.test.ws.WebServiceProxy (SSO testing needed later)

Login module
* See org.oscm.security.WSValidator configured in openejb-jar.xml files to handle login at login service obtaining the username token  
* See org.oscm.security.ADMLoginModule#login implementing the login service

The implementation already includes user key and password. This is unique also in OIDC mode. 

Ideas: 
* Extend the [UserQuery](https://github.com/servicecatalog/oscm/blob/sso/oscm-security/javasrc/org/oscm/security/UserQuery.java#L24) to load the tenant ID for the platform user given by the key.
* Extend [AdmRealmImpl#authenticateUser(final String userKey, String password)](https://github.com/servicecatalog/oscm/blob/sso/oscm-security/javasrc/org/oscm/security/ADMRealmImpl.java#L141) for OIDC mode to perform the authentication client credentials grant using the oscm-identity endpoint and the tenant ID of the user. 
The required function to handle respective oscm-identity client endpoint and validating the token shall be offered as library modules that are separatly unit tested and can be shared with other clients. Maybe the oscm-common repo could be a canditate to host this implementation.

**Comment by kowalczyka** [comment]
As this is investigation issue which is now completed, it will be closed. All necessary improvments will be    proccessed within following issue https://github.com/servicecatalog/oscm/issues/474
