### ISSUE TITLE
war file issue

### ISSUE THREAD

**Issue by divz1010** [servicecatalog/oscm#395]
Step3:Run targets Build.LIB---Build successfully

Build.BES---its failed to find wsdlsei issue we are facing kindly help me to resolve this

**Comment by GoebelL** [comment]
Hi @divz1010 

You need a JDK 1.8 and &lt;JDK HOME&gt;\lib\tools.jar on the ANT classpath. This is required from the wsgen tasks. 
In eclipse you can add it via
*Window > Preferences > ANT > Runtime > Global Entries -> Add external Jars*.

**Comment by divz1010** [comment]
still, issue same please let me know if any specific logs required

**Comment by javed-d1** [comment]
@GoebelL  build is failing with error. Could you please help
oscm-master\oscm-build\defaultprojectbuild.xml:141: Error starting wsgen: null


oscm-master\oscm-devruntime\javares\build-oscmaas.xml:25: The following error occurred while executing this line:
\oscm-master\oscm-build\build.xml:273: The following error occurred while executing this line:
\oscm-master\oscm-build\build.xml:146: The following error occurred while executing this line:
\oscm-master\oscm-build\defaultprojectbuild.xml:141: Error starting wsgen: null

**Comment by GoebelL** [comment]
@javed-d1 
Still seems to me that ANT is not configured with JDK tools.jar. Please check the ANT classpath before running the BUILD.BES target. 
![grafik](https://user-images.githubusercontent.com/14805690/62765447-6db2c480-ba90-11e9-9b3a-2e6cf923dc62.png)

**Comment by javed-d1** [comment]
![ant-config](https://user-images.githubusercontent.com/53929729/62780491-74166000-bad3-11e9-8472-2adcb330b441.PNG)

@GoebelL  It is configured, for reference attached the screen shot.

**Comment by GoebelL** [comment]
@javed-d1 
Please check your JRE configuration on ANT. The build needs to run in seperate JRE process. 
![grafik](https://user-images.githubusercontent.com/14805690/62936034-0024d200-bdc9-11e9-9508-3cdd6734c442.png)

Therefore set JAVA_HOME and ANT_HOME 
![grafik](https://user-images.githubusercontent.com/14805690/62936181-6f022b00-bdc9-11e9-9c2a-979d6faa6072.png)

This should resolve it.

**Comment by javed-d1** [comment]
@GoebelL  Thanks, it resolved the build issue, got build successfully.

**Comment by javed-d1** [comment]
@GoebelL what are the jars looking from jdk for ant build , as it was failing from jre.

**Comment by GoebelL** [comment]
@javed-d1 
> what are the jars looking from jdk for ant build , as it was failing from jre.

AFAIK, it's only tools.jar from JDK, as it contains the wsgen tool. This is needed to generate the WSDL files from classes that implement the OSCM WebService endpoints. 
See the [Oracle documentation](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/wsgen.html#CHEEIICI) for details on wsgen. 
Not sure about JDK internal references. But I think, the classloader requires the ANT task using tools.jar to run in the JRE process from same JDK it belongs too. This is appearently not the case if you run ANT in same process of your eclipse workspace.
