### ISSUE TITLE
New Development Repository

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/oscm#4]
_From @GoebelL on September 21, 2017 13:46_

_Copied from original issue: servicecatalog/development#833_

**Comment by DawidCh** [comment]
_From @GoebelL on October 24, 2017 10:41_

New repository name "oscm".
Following tasks come into my mind. Please add if you have more.

Todo:
1. tag development master and TomEE branches
2. mirror copy develepment->oscm
3. Put TomEE branch on master and delete all unneeded branches
4. Shift Jenkins jobs, ee jobs checkout scripts
5. travis CI
6. reviewable
7. codecov 
8. zenhub 
9. other webhooks
10. docker build
11. users and teams
12. copy/move open tomee issues? Howto? 
13. oscm webpage links (later)

**Comment by DawidCh** [comment]
_From @grubskim on October 25, 2017 14:0_

> 1. tag development master and TomEE branches

Done - created tag v17.5.0-RC1 in development, oscm, oscm-dockerbuild and ops repositories.

> 2. mirror copy develepment->oscm

Done - new repository: https://github.com/servicecatalog/oscm.git

> 3. Put TomEE branch on master and delete all unneeded branches

Done - the tomee code has been merged to the respective master branches of oscm (mirrored development), oscm-dockerbuild, and ops repositories. Tomee branches deleted.

**Comment by DawidCh** [comment]
_From @grubskim on October 26, 2017 8:9_

> 11. users and teams

Done, copied from development repository.

**Comment by DawidCh** [comment]
> 12. copy/move open tomee issues? Howto? 

Done

**Comment by grubskim** [comment]
> Shift Jenkins jobs, ee jobs checkout scripts
travis CI
reviewable
codecov
zenhub
other webhooks
docker build

Done.
