### ISSUE TITLE
Implicit group assignment for initial administrator

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#403]
**Summary**
Create access group together with organization and assign the initial organization administrator.

**Details**
Enhance implementations in OperatorServiceBean#registerOrganization and AccountServiceBean#registerCustomer to create group and assign the initial administrator, using the respective groups endpoint from oscm-identity.
This task can be implemented independently when mocking the oscm-identity endpoints (verify with unit tests). 

**Acceptance criteria**
- [ ] Unit tests
- [ ] Platfrom Operator admin registers an organization: Same named access group is created for the Open ID Provider tenant
- [ ] Supplier admin registers a new customer organization: Same named access group is created for the Open ID Provider tenant
- [ ] Info to @SuessI for handling documentation 

**Additional context**
N/A

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/414#pullrequestreview-280776303
