### ISSUE TITLE
error while building the project how to fix this please let me know

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#404]
**Summary**
error while building the project

**Details**
i have imported the projected and when i try to build and its building when i try to run it is giving errors (faild to buils)
followed steps:-
1. downloaded the source 
2. Imported to my IDE
3. set preference to ant build
4.tried to compile and its compiling
5. but when i try to run the application getting bellow errors 

**Additional context**
Add any other context or screenshots about the task.
[
![Untitled](https://user-images.githubusercontent.com/49364041/62854576-58969980-bd0d-11e9-8387-12991fb09679.png)
](url)

could you please help and suggest what could be the wrong .

**Comment by GoebelL** [comment]
Hi @bharath7394 
Follows steps make the projects to compile in eclipse:
1. Ensure all projects have been imported including `libraries` (`Import > General > Existing Projects into Workspace` and select the oscm folder from your local Git Repo as root directory)
2. In `Window -> Preferences -> Java` set 
     - Installed JREs ->JDK 1.8.0 (131 or higher)
     - Compiler -> Compile compliance level > 1.8 (user default compliances settings)
3. In `Window -> Preferences ->Validation select` "Suspend all validators" and tick off all other options
4. Delete all content in `${workspace_loc}\oscm-build\result`, run `BES.LIB` and `BES.BUILD` from `build-oscmaas.xml`
5. Clean all projects (`Project > Clean...`)

All errors should have vanished. If still projects showing errors, try refreshing the folders in the Package Explorer.
