### ISSUE TITLE
VMware vlan.csv upload failed

### ISSUE THREAD

**Issue by arata-i** [servicecatalog/oscm#408]
**Version Info**
Open Service Catalog Manager 18.0
PRIVATE-BUILD-ON-64780ea032492019/07/09

**Describe the bug**
Unable to upload vlan.csv
the sample csv file ...oscm-app/oscm-app-vmware/resources/csv/vlan.csv does not work.
(Header is "VCenter,Datacenter,Cluster,Name,Gateway,SubnetMask,DNSServer,DNSSuffix,Enabled")

**How to Reproduce**
1. Go to '..oscm-app-vmware' and download the sample vlan.csv file.
2. upload the vlan.csv file of the sample

**Observed behavior**
it shows below error message.
Error during CSV configuration file upload. Mandatory column missing. Required columns: [VCenter, Datacenter, Cluster, Name, Gateway, SubnetMask, DnsServer, DnsSuffix, Enabled]

**Expected behavior**
Success to upload

**Additional context**
If I changed header as "VCenter,Datacenter,Cluster,Name,Gateway,SubnetMask,DnsServer,DnsSuffix,Enabled",
(I modified "DnsServer,DnsSuffix" using small character)
it showed another error message as below.

Error during CSV configuration file upload. ERROR: more than one row returned by a subquery used as an expression

**Comment by GoebelL** [comment]
@cworf91 
Please check this and answer to @arata-i.

**Comment by cworf91** [comment]
Hi @arata-i,

did you insert some data into the vlan.csv template? If not, have a look at the portgroup.csv. There you can see an example, how to structure the data. Importend for the vlan.csv is, that the VCenter Datacenter and Cluster are existing. You can import them through the technical service or through the interface you are using for the import of the vlan.csv. Please let me know if that solve your problem.

**Comment by arata-i** [comment]
Yes, I added below data in vlan.csv but still have error.

VCenter,Datacenter,Cluster,Name,Gateway,SubnetMask,DnsServer,DnsSuffix,Enabled
dxcvc1,CEC Datacenter,CEC-Cluster,VLAN XXX Network,10.6.X.XXX,255.255.255.XXX,10.6.X.XX,XXXX.com,true
(I masked data using X)

**Comment by cworf91** [comment]
Hi @arata-i,
you are right, I was investigating your issue. The correct header looks like:
VCenter,Datacenter,Cluster,Name,Gateway,SubnetMask,DnsServer,DnsSuffix,Enabled
I will correct the Template. 

The error you get when using this header seems to me like an SQL error. Maybe the identifier for your VCenter, Datacenter or Cluster isn´t unique?

**Comment by arata-i** [comment]
Hi, cworf91
Thank you for your confirmation.
Currently, OSCM has 3 cluster settings.(Please refer attached image.)
I tried to combine vlan setting with CEC-Cluseter in vlan.csv but had error.
How can I delete cluster setting from "vSphere API settings"?

<img width="492" alt="Capture" src="https://user-images.githubusercontent.com/54135577/63256617-800bda00-c2aa-11e9-9fa4-84791a66a222.PNG">

**Comment by cworf91** [comment]
Hi arata-i,

Unfortunately there is no possibility to delete the settings in the current version of OSCM. As a workaround, however, you can simply delete the entry directly from the database with a database tool (eg pgAdmin).

**Comment by arata-i** [comment]
Hi, cworf91

Does ESCM support multiple cluster?(Several clusters can be defined in cluster setting according to the manual(VMWareIntegration.pdf)) 
If yes, how can I configure Vlan and IP Pool settings with multiple cluster?

**Comment by cworf91** [comment]
Hi arata-i,

yes it´s possible. Please have a look at the VMWareIntegration.pdf Appendix B (page 21). Here you will find a more detailed description.

**Comment by arata-i** [comment]
Hi, cworf91

I have read manual(P.21-P26) and still have below error.
Could you let me know what I should do if ESCM support multiple-cluster?

Error during CSV configuration file upload. ERROR: more than one row returned by a subquery used as an expression

**Comment by cworf91** [comment]
Hi arata-i,

that look like an SQL problem. Is it possible that you have an doublicate entry in the database?

**Comment by arata-i** [comment]
Hi, cworf91

How can I investigate the duplicate entry in database?
(e.g. How can I connect to database? Which table should I check?)

**Comment by cworf91** [comment]
Hi arata-i,

Use a tool like pgAdmin. Connect to the databases. Open the vmware database and access it with your assigned credentials (default credentials are User: "vmwareuser" and Password: "secret"). Then check the tables cluster, vcenter and datacenter if there is a duplicate entry.

**Comment by arata-i** [comment]
Hi, cworf91
Thank you for your support.
I could register vlan.csv after I deleted duplicated entry via pgAdmin directly.
Once again, thank you very much!

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-app/pull/46
