### ISSUE TITLE
running the project without docker

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#409]
**Summary**
How to run this project without docker please help me with the procedure.

**Details**
As you have mentioned after the successfull build of targets Build.LIB & Build.BES the deployable artifacts in/oscm-build/result/package are found and the next step is mentioned as "copy or replace your build artifact into the respective container" i dont want to run this in docker container please help me with the procedure to run this without docker(ie normal run)

**Comment by cworf91** [comment]
Hello bharath7394,

May I ask why you want to run it without Docker? It was a conscious decision to provide OSCM in a docker network as it greatly simplifies the installation and operation. Therefore, there is no reason for the community to make an installation without Docker possible again at the moment. However, it should be possible to install OSCM outside of a Docker network, but this requires a lot of work.

**Comment by bharath7394** [comment]
Hi, @cworf91 
 Am a final year student working on OSCM as my project, Docker manage container to deploy if it can run in Docker why can't i run without docker. I want to know the flow and exception handling so please help me what are all the changes to be done to run without docker

**Comment by cworf91** [comment]
Hi @bharath7394,
good look with your thesis first. Have a look at the Dockerfiles and the start.sh scripts of the container. Also have a look at the prepare.sh and the docker-compose templates. Try to understand what happen there. The variables which are set cames from the var.env template.
