### ISSUE TITLE
error occuring while building(ALL.BUILD)

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#411]
**Summary**
Hi,
 Am facing with the below error earlier i was getting "GC overhead limit exceeded in Eclipse"error and i increased the size of Xmx and now am facing the this error please help me to overcome with this. 

**Details**
wsdl:
    [wsgen] error: compilation failed, errors should have been reported
    [wsgen] Command invoked: wsgen"C:\Program Files\Java\jdk1.8.0_40\jre\bin\java.exe" -d C:\Users\bharathmc\OSCM_new_repo\oscm\oscm-build\result\work\oscm-extsvc\classes -keep -s C:\Users\bharathmc\OSCM_new_repo\oscm\oscm-build\result\work\oscm-extsvc\src-gen -classpath C:\Users\bharathmc\OSCM_new_repo\oscm\oscm-extsvc\javares -wsdl -portname {http://oscm.org/xsd}OrganizationalUnitServicePortBASIC -r C:\Users\bharathmc\OSCM_new_repo\oscm\oscm-build\result\package\oscm-extsvc\BASIC internal.OrganizationalUnitServiceImpl

BUILD FAILED
C:\Users\bharathmc\OSCM_new_repo\oscm\oscm-devruntime\javares\devscripts\build-dev-PackageDeploy.xml:80: The following error occurred while executing this line:
C:\Users\bharathmc\OSCM_new_repo\oscm\oscm-build\build.xml:269: The following error occurred while executing this line:
C:\Users\bharathmc\OSCM_new_repo\oscm\oscm-build\build.xml:146: The following error occurred while executing this line:
C:\Users\bharathmc\OSCM_new_repo\oscm\oscm-build\defaultprojectbuild.xml:148: wsgen failed

Total time: 1 minute

again i tried by restarting IDE then again am facing "java.lang.OutOfMemoryError: GC overhead limit exceeded" error please help to resolve this

**Comment by GoebelL** [comment]
Hi,
the mentioned ANT target is not needed. Please use the targets Build.LIB and Build.BES to build OSCM as described in the readme of this repository.
You also need to run ANT in a separate JRE process. You can specify VM arguments there to increase heap space, although it shouldn't be necessary. The VM arguments for running the IDE workspace, such as contained in the eclipse.ini file, are  not relevant here.

**Comment by GoebelL** [comment]
See also #395.
