### ISSUE TITLE
where to get the database connectivity and how the database looks

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#412]
**Summary**
how to see the database structure 

**Details**
I want to know how the database looks and what are all the fields present, where the db is present and how the data is storing and retriving please help me to understand this

**Comment by Crystalzord** [comment]
If you have OSCM deployed, you can use pgAdmin program to connect to it and see the database. Credentials to the database are defined via template in the oscm-dockerbuild repository:
https://github.com/servicecatalog/oscm-dockerbuild/blob/master/oscm-deployer/templates/var.env.template#L9
The default password is set in the Dockerfile of oscm-db:
https://github.com/servicecatalog/oscm-dockerbuild/blob/master/oscm-db/Dockerfile#L3

**Comment by cworf91** [comment]
Hi bharath7394,

look at this Issue, maybe it is helpfull for you: https://github.com/servicecatalog/oscm/issues/408
