### ISSUE TITLE
Error while deployed in docker container 

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#415]
Hi,
 As you mentioned both builds(build.LIB & build.BES) are successful and if i deploy the artifacts in docker container it working fine. But if i change logo or some image and build again, then will get successful but when i deploy the artifacts to container its not working, am not getting the portal view but the tomee server is running.

**Comment by cworf91** [comment]
Hi bharath7394,

to use your indidvidual branding you should use the oscm-branding container. Look at the operators guide page 42 (Customizing the Layout of Marketplaces
