### ISSUE TITLE
Responsive navigation bar

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#420]
**Summary**
The marketplace navigation bar of CT-MG can be implemented with bootstrap in order to become responsive.

**Details**
The header area can be implemented as a bootstrap (or alternatively Bootsfaces) navigation bar.

**Acceptance criteria**
The navigation bar is responsive and well-designed on all marketplace UI pages.

**Additional context**
N/A

**Comment by GoebelL** [comment]
Prototype looks fine so far.

Discussed todos
1. Vertical alignment
2. Search input field beneath menu
3. Logout redirect to playground

**Comment by GoebelL** [comment]
@farmakiG 
Please raise a pull request to master when above points are ready. I'd like to push it on dockerhub.
