### ISSUE TITLE
Error while creating organization

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#426]
Hi sir,
 I have login to the portal with administrator id and password as mentioned in documentation and if i try to create organization under operation it is showing operation failed. How to resolve this please let me know

Thank you
![org error](https://user-images.githubusercontent.com/49364041/64619337-8c91d700-d3ff-11e9-883f-3d3efd52fbfc.png)

**Comment by GoebelL** [comment]
Hi @bharath7394 

this should not appear. Probably something is missing or mismatching in your environment configuration. Check the log files for oscm-core. The detailed error trace should be found there.
try `docker logs oscm-core`
If nothing is there you should find it in system.log.
```
docker exec -it oscm-core bash
cat /logs/system.log
```
Kind request to please use the bug template and provide the requested information next time.

**Comment by GoebelL** [comment]
Duplicate with #429.
