### ISSUE TITLE
[SSO] Improve error message for user not found when registering customers

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#427]
**Version Info**
18.1 SSO

**Describe the bug**
The identity service returns 404 if initial organization admin user is not found at the OIDC provider. 

**How to Reproduce**
1. Deploy with sample data in OIDC mode and login as supplier user
2. Select register custmer and provide a user id for the initial administrator that does not exist.
3. See error

**Expected behavior**
A clear message that user xxx was not found

**Observed behavior**
Operation failed

**Screenshots**
N/A

**Additional context**
Map HTTP 404 result from getUserinfoFromIdentityService(...)

**Comment by GoebelL** [comment]
@cworf91 
Also HTTP status is not handled properly at [AccessGroup#createGroup](https://github.com/servicecatalog/oscm/blob/sso/oscm-identitymgmt/javasrc/org/oscm/identityservice/rest/AccessGroup.java#L42)
It expects status code HTTP 201 (Created) and throwing a runtime exception in other case. It should better check for 2xx. In my case HTTP 200 (OK) was returned, which should not result in an error.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/445
https://github.com/servicecatalog/oscm-commons/pull/12

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/446

**Comment by cworf91** [comment]
The error messages must be made more concrete in the future.
