### ISSUE TITLE
Infinite loop to change password after user creation and first login

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#428]
Version: OSCM 18.0
Browser: Chrome
Country: BG

Actual >(wrong) behaviour:

1. create a new user
2. login as the new user with pwd from mail
3. user changes pwd in change dialog
4. pwd is changed but user asked to change pwd again and again (inifinite loop)

workaround: close browser completely and login again

**Comment by uhu133** [comment]
[system.log](https://github.com/servicecatalog/oscm/files/3600655/system.log)

system.log

**Comment by elfriedegoetz** [comment]
tested okay with build from 13/09/2019
- portal: register new user, new organization
- marketplace. add user

**Comment by elfriedegoetz** [comment]
tested with firefox and chrome

**Comment by GoebelL** [comment]
@uhu133 
The fix release OSCM 18.0.2 is available DockerHub. Just pull all [servicecatalog/oscm-*](https://hub.docker.com/u/servicecatalog) images with tag `latest`.
