### ISSUE TITLE
Error while Registering user

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#429]
**Version Info**
master v17

**Describe the bug**
when i try to register new user and creating organization am getting 'operation failed' error i checked the log but i dint understand and also i tried by importing users from csv file the import is getting started but its not getting finish please help me to resolve this  

**How to Reproduce**
1. Go to 'login'
2. Click on 'account'
3. Scroll down to 'register new user'
4. operation failed

**Observed behavior**
operation failed to register user

**Expected behavior**
want to register user
![logerror](https://user-images.githubusercontent.com/49364041/64704752-68e89280-d4cc-11e9-90b3-76107298fa64.png)

**Screenshots**
when i register new user and creating organization showing operation failed and logs are uploaded and also if i import users from csv file also not working

**Additional context**
Any other context about the problem here.
![org error](https://user-images.githubusercontent.com/49364041/64704754-69812900-d4cc-11e9-9335-cdeb56217287.png)

![regerror](https://user-images.githubusercontent.com/49364041/64705204-355a3800-d4cd-11e9-993b-9481b43c2399.png)

**Comment by GoebelL** [comment]
Hi @bharath7394 
Thanks for using the template. You are really using OSCM v17? This is an older glassfish version.  
Please confirm the OSCM version. In the oscm portal simply click on the logo "Open Service Catalog Manager" and write the version info that is shown in the popup dialog.
 
It's same as #426. This looks to be a configuration issue. Not sure about the jms errors. 
Both operations register user and register organization are sending email notification. Did you configure the email server correctly?  Please also attach the system.log file.

**Comment by bharath7394** [comment]
Thank you for your fast reply 
Am using v18 ,am lagging some where setting up mail server so kindly help me to setup the mail server properly .
and if possible kindly provide your skype ID to communicate directly.

**Comment by GoebelL** [comment]
Hi @bharath7394 

You can use a local mail server or public service. Just put the mail properties in var.env file.
 Example:
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_FROM=myemail@gmail.com
SMTP_USER=myuser
SMTP_PWD=mypassord
SMTP_AUTH=true
SMTP_TLS=true
APP_ADMIN_MAIL_ADDRESS=myemail@gmail.com
APP_TRUSTSTORE_BSS_ALIAS=1

>and if possible kindly provide your skype ID to communicate directly.

Yes sure, but not here. Please mail me to lorenz.goebel@est.fujitsu.com.

**Comment by cworf91** [comment]
Seems to be working now.
