### ISSUE TITLE
error while login to portal

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#431]
**Version Info**
v18

**Describe the bug**
Am trying to login to portal with id-"administrator" password-"admin123" as mentioned ,it was logging in earlier i dint know what has happened now it is showing "account is locked please contact administrator" please help me out of this

**How to Reproduce**
1. Go to 'https://<fqdn>:8081/oscm-portal/'
2. Click on 'login'
4. account is locked please contact administrator

**Observed behavior**
Not able to login as administrator.

**Expected behavior**
want to login to the portal.

**Screenshots**
when i try to login with the ID-"administrator" and password-"admin123" it is showing "account is locked please contact administrator"
![locked](https://user-images.githubusercontent.com/49364041/64780751-d7862880-d57e-11e9-8fcb-88ed4be05ee1.png)
.

**Additional context**
Any other context about the problem here.

**Comment by GoebelL** [comment]
Hi @bharath7394 

By default OSCM locks the user account after three failed login attempts. In such case the platform administrator can unlock the user's account in the oscm portal. Pity if the platform administrator has locked out himself ... &#128518; 
Don't worry. This can be solved quickly with a small hack from the docker host command-line. Just connect your database with PSQL by starting a second oscm-db container and fire an SQL query to reset the status and failedlogincounter for the platform user 1000.

```
docker run -it --name secdb --rm --network docker_default servicecatalog/oscm-db:latest bash
PGPASSWORD=secret psql -h oscm-db -U postgres -d bss -c "UPDATE bssuser.platformuser SET failedlogincounter = 0, status = 'ACTIVE' WHERE tkey = 1000;"
exit
```
This should fix it.
