### ISSUE TITLE
Requesting for paid help

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#434]
**Version Info**
v18

Am facing problem with setting up, is there any paid service available to help me .please provide me the link to get that. 
Am facing with following issues
1.Creating users(Operation failed)
2.Creating organization(Operation failed)
3.Defining service
4.Integrating application
please help me to resolve my issues and provide the link for paid service

**Comment by GoebelL** [comment]
@bharath7394 
I can help you with setup. First, please let me know what is your goal. Are you interested in hybrid cloud provisioning, infrastructure, platform or software as a service? Which kind of applications do you like to integrate?
This is not the place here to discuss such things. Please write me at lorenz.goebel@est.fujitsu.com.
