### ISSUE TITLE
Webservicetest fail

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm#436]
**Version Info**
18.1 SSO

**Describe the bug**
Webservicetest AccountServiceBeanNullArgumentTest and testLogInjectionForBillingServiceWS  fail

the test will be set to ignore and should be fiexed later. 

logs available at: https://api.travis-ci.org/v3/job/581174525/log.txt

travistests:
    [mkdir] Created dir: /home/travis/build/servicecatalog/oscm/oscm-build/result/work/oscm-webservices-unittests/test
[jacoco:coverage] Enhancing junit with coverage
    [junit] WARNING: multiple versions of ant detected in path for junit
    [junit]          jar:file:/home/travis/build/servicecatalog/oscm/libraries/apache-ant/javalib/ant.jar!/org/apache/tools/ant/Project.class
    [junit]      and jar:file:/home/travis/build/servicecatalog/oscm/libraries/apache-ant/apache-ant-1.10.5/lib/ant.jar!/org/apache/tools/ant/Project.class
    [junit] Testsuite: org.oscm.webservices.AccountServiceBeanNullArgumentTest
    [junit] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.329 sec
    [junit] 
    [junit] Testcase: testNullArguments took 0.256 sec
    [junit]    FAILED
    [junit] Unexpected exception while calling removeSuppliersFromTechnicalService with null for parameter technicalService: java.lang.reflect.InvocationTargetException
    [junit] junit.framework.AssertionFailedError: Unexpected exception while calling removeSuppliersFromTechnicalService with null for parameter technicalService: java.lang.reflect.InvocationTargetException
    [junit]    at org.oscm.test.NullArgumentTestBase.verifyArgument(NullArgumentTestBase.java:133)
    [junit]    at org.oscm.test.NullArgumentTestBase.verifyMethod(NullArgumentTestBase.java:102)
    [junit]    at org.oscm.test.NullArgumentTestBase.testNullArguments(NullArgumentTestBase.java:88)
    [junit] 
    [junit] TEST org.oscm.webservices.AccountServiceBeanNullArgumentTest FAILED

**Comment by GoebelL** [comment]
This is fixed in sso branch. See https://travis-ci.org/servicecatalog/oscm/builds/586030494.
