### ISSUE TITLE
Error while starting the container for initializing the database

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#438]
**Version Info**
v18

**Describe the bug**
Am trying to start the container for initializing the database by the following command
"docker-compose -f docker-compose-initdb.yml up -d oscm-db"
  but it showing "ERROR: pull access denied for services.oscm-db.image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
"
I even tried by login into docker with my account and tried again still the same error
please help me to resolve this

**Observed behavior**
root@docker:/docker# docker-compose -f docker-compose-initdb.yml up -d oscm-db
Pulling oscm-db (services.oscm-db.image:latest)...
ERROR: pull access denied for services.oscm-db.image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Expected behavior**
Want to pull oscm-db (services.oscm-db.image:latest)

**Screenshots**

![pull error](https://user-images.githubusercontent.com/49364041/65021686-3bc53580-d94d-11e9-8ef6-a206ea04baaa.png)

**Comment by GoebelL** [comment]
Hi @bharath7394 
Seems you are using wrong image location, or how is your docker setup supposed to resolve 'services.oscm-db.image'? Check your .env file. 
Unless you have installed OSCM in a custom registry, all image variables should point to servicecatalog/oscm-*
`IMAGE_INITDB=servicecatalog/oscm-initdb:latest`
Check also docker-compose-initdb.yml if you have modified that.

Proceed as described in the [Operator's Guide](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/installation+operation/en/Operation.pdf), chapter 3.1, point 6 on page 20.
