### ISSUE TITLE
[SSO] Improve error message when the communication with the oidc service fails

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm#448]
**Summary**
When the communication with the oidc provider fails, a clear error message should be shown. Like "User is already assigned to a group" or "User is alredy exist".

**Comment by GoebelL** [comment]
See https://github.com/servicecatalog/oscm-identity/issues/48.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/516
