### ISSUE TITLE
Make organization a required field

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm#454]
**Summary**
Make organization a required field in "Register costumer". 

**Details**
When SSO mode is used, it is necesarry to register a organization for this costumer. Therefore the field has to be a required field. Changes should be done in the addCustomer.xhtml page. Futhermore, the Organization name should be checked if it´s already existing.

**Comment by GoebelL** [comment]
Check for existance is not needed at this place.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/461
