### ISSUE TITLE
changing password for controller managers

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#46]
[Build] 17.5 2017/11/16

[Details]
Please add documentation (online is important here), on the order of changing password for controller managers.  
You have to change the password first in APP UI and then in portal. Otherwise you cannot log in to the controller to change it there (the reason for this is that you have 2 way authentication here, for a reason that I do not remember). A hint for the user if you did it wrong, would be to change the password back to the original using portal, and then to do it in the correct order.

In my opinion this is a bug, but it has always been like this. But it now becomes more important since sample data with sample password is supplied. You used to be able to run updateDatabase to get you "_crypt" password into the app db again.

**Comment by gertipoppel** [comment]
A respective comment has been added to 
- DocSources/en/help/tasks/user_pwd.xml  and
- Section "Updating APP and Controller Settings" in the Technology Provider Guide

Fix available as of January 2018
