### ISSUE TITLE
 Wrong encoding is used when copying the name from Azure AD.

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#466]
Version Info
18.1 SSO
Describe the bug

How to Reproduce
1.	Setup with OIDC mode
2.	Login as platform administrator
3.	Create Organization "XY"
4.	type "Desired user ID" "abc" from Azure AD with Last name e.q. Götz
5.	Login as user "abc"
6.	Goto edit profile

**Observed behavior**
wrong encoding see attachment

**Expected behavior**
correct last name: Götz

**Comment by elfriedegoetz** [comment]
![NoUtf8](https://user-images.githubusercontent.com/15209605/65944484-17c82080-e432-11e9-8ad9-6ff0c8396608.PNG)

**Comment by GoebelL** [comment]
1. Use user language returned for OIDC provider
2. Use organization language as fallback if user language is unknown.

**Comment by adamczykba** [comment]
@elfriedegoetz @GoebelL 
I've tried to reproduce it on my Azure organization, but everything seems to work just fine. Maybe this is some issue with the browser/system encoding? 
![obraz](https://user-images.githubusercontent.com/47355402/67666110-63a3b200-f96b-11e9-9d89-d6b8865fa99d.png)

**Comment by elfriedegoetz** [comment]
works fine now tested with sso build from 25.10.2019
