### ISSUE TITLE
error while activating service 

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#467]
**Version Info**
v18

**Describe the bug**
I have created services and am trying to activate the services but is not working, and is there any inbuilt services are available if any how to enable that please help me out of this

**How to Reproduce**
1. Go to 'marketplace services'
2. Click on 'activate or deactivate services'
3. select service to activate click activate 
4. Operation failed

**Observed behavior**
operation failed

**Expected behavior**
the services should be activated

**Screenshots**
![activate error](https://user-images.githubusercontent.com/49364041/65694320-4d1be980-e093-11e9-9621-d6795cc57467.png)

**Comment by GoebelL** [comment]
Hi @bharath7394 
Not clear of what's your goal and which kind of services you attempt to integrate there. Nevertheless I've got  three hints for you:
* Start quick and lean to explore OSCM capabilities. I suggest to begin with the [APP Sample Controller service](https://github.com/servicecatalog/oscm-app/blob/master/oscm-app-sample/README.md).  
* Check out the [Technology Provider's Guide](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/integration/en/TechProv.pdf) and the [Developer's Guide](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/integration/en/Developer.pdf) for building own integrations
* Whenever "Operation failed" comes up in the UI,  there is something unexpected with the setup or configuration. To find out what's actually wrong, check the OSCM system log by entering oscm-core container and listing the /logs/system.log file. 

Let me know if you have further questions.
