### ISSUE TITLE
Getting start with OSCM OpenStack integration

### ISSUE THREAD

**Issue by jarunkumarb** [servicecatalog/oscm#470]
**Version Info**
18

**Describe the bug**
 Am trying to provide SAAS in application but the services are not visible, as i see in demo application services are showing and i don't know how to enable in this application i even tried with importing xml file but not working, in marketplace how to enable that and also if i try to create users r organization am getting operation failed error please help me out of this.  

**How to Reproduce**
1. Go to 'market place'
2. Click on 'all services'
3. 0 services found 

**Observed behavior**
0(zero) services available and operation failed when created user and organization 

**Expected behavior**
should create users and organization also service should be enabled 
![zero service](https://user-images.githubusercontent.com/13447493/65885354-1fe37a00-e3b8-11e9-9688-c34dc83cbf34.png)

**Comment by GoebelL** [comment]
Hi @jarunkumarb 
This is correct. The initial catalog is empty. You'll need to configure the services you want to use.  
Refer to the [Technologies Provider's Guide](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/integration/en/TechProv.pdf) for details and usage of OSCM technical services. For the clould adapters you find separate manuals [here](https://github.com/servicecatalog/documentation). 

There are technical service templates for various cloud adapters: 
* [Amazon AWS EC2](https://github.com/servicecatalog/oscm-app/blob/master/oscm-app-aws/resources/TechnicalService_AWS.xml)
* [OpenStack](https://github.com/servicecatalog/oscm-app/blob/master/oscm-app-openstack/resources/TechnicalService_OpenStack.xml)
* [MS Azure](https://github.com/servicecatalog/oscm-app/blob/master/oscm-app-azure/resources/TechnicalService_Azure.xml)
* [VMWare](https://github.com/servicecatalog/oscm-app/blob/master/oscm-app-vmware/resources/TechnicalService_VMware.xml)
* [Generic integration](https://github.com/servicecatalog/oscm-app-shell/blob/master/src/main/resources/TechnicalService.xml)
* [Dev Sample](https://github.com/servicecatalog/oscm-app/blob/master/oscm-app-sample/resources/TechnicalService.xml)

**Comment by jarunkumarb** [comment]
Thanks for the reply @GoebelL 
kindly help me how to setup openstack and configuring var.env file for openstack.

**Comment by GoebelL** [comment]
Hi @jarunkumarb 

you might want to explore the OSCM OpenStack integration. If you haven't got an OpenStack environment yet, I suggest you install DevStack with Heat. 

Checkout following pages:
* [Installing DevStack](https://docs.openstack.org/devstack/latest/)
* [Enabling Heat](https://docs.openstack.org/heat/latest/getting_started/on_devstack.html)

For any issues on OpenStack, please find respective ressources online or contact the community if you got stuck.

Get OpenStack with Keystone, Heat and Nova components running. To prepare some data, login to horizon, create a project in identity and an image in compute. Note the project id and image.

You don't need to give OpenStack settings in var.env. You can configure OpenStack connection in the OSCM web UI. Install OSCM and enable it for login to APP (see [Quick Start Guide](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/installation+operation/en/QuickStart.pdf), chapter 4.2). 

Refer to [OSIntegration.pdf](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-app-openstack/doc/en/OSIntegration.pdf) for details on configuring the OpenStack controller. 

To get started:
1. Login to `https://<FQDN>:8881/oscm-app-openstack` as service manager (in this case it's administrator) 
2. Provide the connection information in the section `controller specific settings`: 
    - API User and API Password (the admin credentials from your OpenStack project)
    - Keystone API URL: `http://... :5000/v3/`
    - Tenant ID: Above mentioned project id
    - Domain Name: `Default` 
    - Template Base URL: Leave `http://oscm-core:8080/templates/`
    - Event timer interval (ms): 86 400 000
3. Import a heat template as described in chapter 4.4. F.e. the samples [template.json](https://github.com/servicecatalog/oscm-app/blob/master/oscm-app-openstack/resources/template.json) and [template.yaml](https://github.com/servicecatalog/oscm-app/blob/master/oscm-app-openstack/resources/template.yaml) in the oscm-app repo to be used with the [sample service template](https://github.com/servicecatalog/oscm-app/blob/master/oscm-app-openstack/resources/TechnicalService_OpenStack.xml).  
4. Login in oscm-portal and import technical services from previous mentioned template.
5. Define marketable services, price models and publish them.
6. Login to the marketplace and subscribe them.

Hope it was helpful. Have fun.

**Comment by jarunkumarb** [comment]
Hi Sir,
    User also not getting any email using oscm. I am using postfix mail
server. SMTP configuration also I need. Can u help me out.

Regards,
      Arun

**Comment by GoebelL** [comment]
@jarunkuarb 
If you have a running mail server in your network that is usable with plain SMTP, there is not much to be done. You need to provide SMTP configuration of your mail server in the mail settings section in var.env.  
Example : 
`SMTP_HOST=...

SMTP_PORT=25

SMTP_FROM=user@oscm.com

SMTP_USER=none

SMTP_PWD=none

SMTP_AUTH=false

SMTP_TLS=false
`
It's generally recommended to read _all_ comments in this file very carefully to avoid subsequent issues in OSCM.

If you set up the mail server yourself, you will find out required settings from the mail server host, e.g. something like /etc/postfix/main.cf for PostFix.  If you did not setup in your privat owned network, contact your network administrator.
