### ISSUE TITLE
Operations with mail notification have failed

### ISSUE THREAD

**Issue by jarunkumarb** [servicecatalog/oscm#473]
**Version Info**
v18

**Describe the bug**

Steps followed:

Step 1.
	We have cloned the project to Eclipse through the below link
	“https://github.com/servicecatalog/oscm.git”

Step 2.
	Setup the java preferences from jre to jdk. Then started building the project with.
	Firstly run the target
	Build.LIB then Build.BES. 
	The deployable artifacts in/oscm-build/result/package are successfully generated.

Step 3.	
	The Artifacts are deployed in the respective container 
	Example:
	docker cp /workspace/oscm-build/result/package/oscm-portal/oscm-portal.war 		oscm-core:/opt/apache-tomee/webapps/

	Docker setup:

	1.
		Installed Docker & Docker Compose.
		Created directory docker with following command:

		mkdir /docker

	2.	
		Then run the deployer 1 with the below command:

		“docker run --name deployer1 --rm -v /docker:/target servicecatalog/oscm-deployer”

		After this two files are created (ie .env & var.env) and we have edited the var.env file  
	
		Then deployer 2 with the below command:

		“docker run --name deployer2 --rm -v /docker:/target -v 						/var/run/docker.sock:/var/run/docker.sock -e INITDB=true -e STARTUP=true 			servicecatalog/oscm-deployer”

Step 4.
	Then we log in to the portal with through 
		”https://hostname.fqdn:8081/oscm-portal/ ”
	
	with the given credentials

      Username: administrator
      Password: admin123
Step 5.	
	 
i) Then we created the marketplace from the below steps
	Go to Service catalog Manager->Under that Market place-> Inside that Create market place

ii) Registering new users
	Go to Account->Register New Users
	Here We are Facing the issue Operation Failed.
	Here newly register user also Not Getting Email.

iii) We try to create organization from the following steps
	Go to service catalog Manager->Under operation->create organization
	Here We are Facing the issue operation Failed 

iv) Adding currency to oscm
	Go to service catalog Manager->Under operation->Create Payment Service Provider	

v) We created Technical Service
            Go to Technical Service -> Register Service Definition
				        -> Import Service Definition
				        -> Update Service Definition
				        -> Export Service Definition

             Above Service Definitions are working fine.

vi)Defining price model
	 Go to service catalog Manager->Under Price model->define for service 
	working fine 
vii)Assigning Marketplace
	 Assigned the marketplace

vi) When i go to Marketable Service -> Activate Or Deactivate Services
	I Tried to activate the Service but facing operation failed issue.

vi) After that Go to Market Place -> Select Market Place
           Here I clicked the Browse All Services But it displaying
                 Services Not Found

Problem Facing:

1. Operation Failed
2.We Setup and configured var.env files but email is not getting.
3. Services also not Found.

As i saw in architecture and documentation the default services are available in marketplace,
 currently we are not using any cloud adapters we just need to see the default services.     

Please help me where am facing the problem and what am missing .Is that cloud adaptor is mandatory to enable the default services also? 
  
**Screenshots**
If applicable, screenshots to help explain your problem.
![activate error](https://user-images.githubusercontent.com/13447493/66122359-1eef5a00-e5fd-11e9-8519-21f7515f03bb.png)

![archetecture](https://user-images.githubusercontent.com/13447493/66123057-cfaa2900-e5fe-11e9-82cb-697574d9b178.png)

![org error](https://user-images.githubusercontent.com/13447493/66123098-e486bc80-e5fe-11e9-84a7-dbd6d31b46e0.png)

![regerror](https://user-images.githubusercontent.com/13447493/66123120-f0727e80-e5fe-11e9-857a-9af5993656f6.png)

![zero service](https://user-images.githubusercontent.com/13447493/66123136-f700f600-e5fe-11e9-8695-7baf13c6b02b.png)

**Comment by GoebelL** [comment]
Hi @jarunkumarb 
Whoops! This is a long description. Basically, you are on the right track. However, the mail service is absolutely mandatory for OSCM. Thus, if the mail settings are incorrect or the service is not fully functional, OSCM will fail to send mail notifications and show such general error message. In the given case it's the login email to the new user, containing the initial credentials and login URL. You'll find details about the failed operation in the log files (login to oscm-core with docker command and view the files under /logs. In most cases error details can be found in System.log) 

So, let's shorten the story. Actually, the mail settings you have set in var.env would be more interesting here than the stuff you have put here. There is better chance that I can help you, if you'd just share me the values of the SMTP settings you have given in var.env. Just mask the parts that should not be disclosed here.

See also the final comment in https://github.com/servicecatalog/oscm/issues/470

**Comment by GoebelL** [comment]
Duplicate to #477.
