### ISSUE TITLE
Make online portal help location configurable

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm#48]
Portal help is reachable by portal itself indirectly through the link which poin to the same host as portal itself.

As portal help will be delivered in the separate container, portal must be adapted so that the location of online help is configurable.

**Comment by grubskim** [comment]
It is now configurable with the HELP_URL configuration setting.

- HELP_URL should end with oscm-portal-help, and point to the deployed application.
- if left empty, URL is the current context
- as the base of the help URL is cached, logout/login is required after changing it

**Comment by kwodzynski** [comment]
Tested on 17.5 2017/12/06. Now online help is configurable.
