### ISSUE TITLE
End-to-end testing: Prepare Selenium tests for CI

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#481]
**Summary**
Make selenium tests run in head-less mode.

**Details**

**Acceptance criteria**
- [ ] One test running auto-scheduled in Jenkins 

**Additional context**

**Comment by farmakiG** [comment]
Further tasks to be done:

- Restructure projects: oscm-portal-integrationtests and oscm-webtest-base to be included in a parent project. Implement a parent pom.xml which executes both maven targets for oscm-webtest-base and oscm-portal-integrationtests one after another.

- Refactor webtest.properties and move it to oscm-webtest-base. 

- Create a new pipeline with groovy scripts for executing all three jobs at once:
OSCM_Docker_Build_and_push, OSCM_Docker_pull_and_start and OSCM_Integration_Tests.

- Fix separate test cases failures.
