### ISSUE TITLE
How to Enable Services in OSCM

### ISSUE THREAD

**Issue by jarunkumarb** [servicecatalog/oscm#486]
**Version Info**
v18

**Describe the bug**
**Version Info**
v18
**Describe the bug**
Thanks for your great support. Email also working Fine.
    could you help on how to enable the Technical Services in OSCM ( like- User Management, Subscription, Branding, Billing, Service Management, Provisioning, Event Management), how to configure Wsdl files?  and also where we can find that.

Looking forward for your help on this...

**Comment by GoebelL** [comment]
Hi @jarunkumarb 

The question is not clear for me. What it is your goal with OSCM? Do you want to use OSCM WebService APIs?  

Note that OSCM Technical Services and these Web Services you named here are different things. See also my answer to [your similar issue-4](https://github.com/servicecatalog/oscm/issues/477#issuecomment-538516419). 
1. The Web Services you listed are standard interfaces and already part of the OSCM platform. Respective endpoints are available by default when starting the oscm-core container. These are offered for developing applications that integrate with OSCM and are hosted externally. Some documentation can be found [here](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/integration/en/Developer.pdf). Note that we are going to deprecate these interfaces in OSCM and replace with a RestFull API.

2. OSCM Technical Services belong to the OSCM business domain. They are defined and configured by the service manager _within_ OSCM to integrate customer applications and services (SaaS, IaaS or PaaS). This is a key feature of OSCM.
Details can found in the [Technolgy Provider Guide](https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/integration/en/TechProv.pdf)
