### ISSUE TITLE
Failed to find the default services

### ISSUE THREAD

**Issue by jarunkumarb** [servicecatalog/oscm#488]
**Version Info**
v18

**Describe the bug**
Sir,
we are providing saas in our application.
For services we are just copying the wsdl link to create services and the default service are not available in marketplace(ie billing,event management,calendar,etc) because i saw the services in videos in there these services are available, is these are default services are we need to define ?
if default how to enable that please provide the steps.
and am not using any cloud adapters like openstack,aws,azure,Vmware is cloud adapter mandatory to run the services.

and also am facing the below error 
"Synchronous provisioning operations are not supported by the asynchronous provisioning proxy"
what to do and where to change the provisioningType from ASYNCHRONOUS to SYNCHRONOUS

**Comment by GoebelL** [comment]
Hi @jarunkumarb 

I feel you are repeating questions though I have tried to answer them a few times. 
Please _read_ my answers in https://github.com/servicecatalog/oscm/issues/486.
What is your application doing? If you want to integrate your SaaS application with OSCM, the Technogy Provider Guide is your starting point. For example, read there about synchronous and asynchronous provisioning types, which access type is useful for your case, what are possibe endpoints and service parameters that match your needs and find out how to define them within your technical service XML template.
For a loose integration, you have the choice of using f.e. Direct or External as access type. This is fairly quick to implement and might be a good exercise for getting started. However, if you like to use the rich features of OSCM, to benefit from user and subscription management, or charging capabilities you'll need a more tight integration on the API level. 
If you are interested in developing with OSCM APIs, then the [point 1](https://github.com/servicecatalog/oscm/issues/486#issuecomment-539021670) is your answer. Check out the document I have linked there. Get started with implementation of the [Provisioning Service](https://github.com/servicecatalog/oscm-interfaces/blob/master/oscm-extsvc-provisioning/src/main/java/org/oscm/provisioning/intf/ProvisioningService.java). See it's javadoc and [WSDL files](https://jitpack.io/com/github/servicecatalog/oscm-interfaces/oscm-extsvc-provisioning/master-SNAPSHOT/oscm-extsvc-provisioning-master-SNAPSHOT-sources.jar).
