### ISSUE TITLE
oscm developing and debugging with intelij idea

### ISSUE THREAD

**Issue by rmros** [servicecatalog/oscm#498]
@GoebelL  i imported oscm project as eclipse to in intellij idea,
what are your debugging/compiling method for developing oscm modules?

i know how to use ant and ivy to compile and produce war , ear file for deploy those ,
but i need t know how you developing those modules in intellij idea

thanks

**Comment by GoebelL** [comment]
Hi @rmros ,

Well, some guys here are using IntelliJ, some are using Eclipse. I am of the latter. Nevertheless, OSCM is a Java EE application, so these tasks are pretty much similar with IntelliJ, I think.

@adamczykba, 
I remember you are using IntelliJ. Do you have some hints here for debugging and configuring the workspace with ANT in this IDE? Maybe you can share @rmros some screenshots of your settings.

**Comment by adamczykba** [comment]
@rmros 
Here is a detailed guide, how to develop and debug OSCM on IntelliJ:
1. Import the project by selecting **New -> Project from existing sources**
2. Select **Create project from existing sources**
![obraz](https://user-images.githubusercontent.com/47355402/67267472-a4ef1a00-f4b2-11e9-95bc-d5c1b4967e29.png)
3. Click **Next** on every other screen that appears (make sure that all the modules are selected to import though)
4. Open main repository directory in the command line and run
``ant -f oscm-devruntime\javares\build-oscmaas.xml BUILD.LIB``
5. Create **oscm_libs** directory somewhere outside of the GIT repository dir
6. Search main repository dir (recursively) for **.jar** files and copy all of them to the directory created in previous step (**IMPORTANT:** don't copy **jcl-over-sl4j-1.7.7.jar** as IntelliJ compiler marks this as conflicting library when running the tests!). I prefer to use *Total Commander* for it.
7. Open **File -> Project Structure** dialog
8. On the Libraries tab, add the libraries directory to the projecy and close the window by clicking on **Ok**
![obraz](https://user-images.githubusercontent.com/47355402/67269940-ef26ca00-f4b7-11e9-9270-9bf3f34f98f4.png)
9. When pop-up appears, select all the modules using *CTRL+A* combination
![obraz](https://user-images.githubusercontent.com/47355402/67269850-c1418580-f4b7-11e9-8b38-8c204cb241be.png) 
9. Create the configuration for debugger using settings shown below (I assume that You have OSCM deployed already):
![obraz](https://user-images.githubusercontent.com/47355402/67266538-bd5e3500-f4b0-11e9-92d7-7de9662bd0c8.png)
10. For **oscm-core container**:
![obraz](https://user-images.githubusercontent.com/47355402/67266708-1e860880-f4b1-11e9-9621-a9f6e7e61595.png)
11. For **oscm-app container**:
![obraz](https://user-images.githubusercontent.com/47355402/67266854-73c21a00-f4b1-11e9-9fbe-8eb8287a4cb2.png)

**As for some more tips and tricks:** Most of all, remember that if You're using Community edition of the IntelliJ, all files related to JEE (xmls, jsps, jsfs etc.) will make Your code invalidated by the IDE linter.
You'll be also not able to use IntelliSense feature. This however doesn't impact the debugger - it's working regardless.

After performing those steps, You should be able to use oscm with IntelliJ pretty freely.
Feel free to contact us in case of any futrher problems

**Comment by adamczykba** [comment]
@GoebelL 
Can we consider this issue closed?

**Comment by GoebelL** [comment]
yes.
