### ISSUE TITLE
Uncomment two tests

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/oscm#5]
_From @DawidCh on September 29, 2017 10:4_

Fix and uncomment the tests.
7a6045817ca8290f77183f186154fc511f658c0c

_Copied from original issue: servicecatalog/development#843_

**Comment by DawidCh** [comment]
Functionality works. Link to custom tab is generated properly.

**Comment by grubskim** [comment]
Uncommented two tests and added missing libraries:
cxf-rt-rs-client-3.1.10.jar
cxf-core.jar
cxf-rt-frontend-jaxrs.jar
geronimo-javamail_1.4_mail-1.9.0-alpha-2.jar

to:
oscm-portal\.classpath
oscm-triggerservice\.classpath

These libraries come with fresh TomEE installation, so it should not break any functionality.
