### ISSUE TITLE
Finding difficulty with integrating application with OSCM  

### ISSUE THREAD

**Issue by jarunkumarb** [servicecatalog/oscm#502]
**Version Info**
v18

**Describe the bug**
my goal is to provide Saas in OSCM as i saw the below platform services are available
• Account management service
• Billing service
• Categorization service
• Discount service
• Event management service
• Identification service
• Marketplace management service
• Organizational unit service
• Reporting service
• Review service
• Search service
• Service provisioning service
• Session service
• Subscription management service
• Tag service
• Trigger service
• Trigger definition service
• VAT service
The APIs of the platform services are available in the OSCM integration package

also i have downloaded the oscm integration pack zip folder but i didn't understand what to do next and how to integrate these services with OSCM and also help me how and where to deploy and how to integrate any application with oscm ,is it necessary to have a cloud adapter to run these application to integrate with OSCM please help me to resolve my confusions.

**Comment by GoebelL** [comment]
@jarunkumarb 
Once again, please stop multiplying same issues here. Just _Read_ my [answer on #488]( https://github.com/servicecatalog/oscm/issues/488#issuecomment-541147006) and get started with manuals on GitHub I have linked there. 
The latest platform API can be found in oscm-interfaces repo. The "cloud adapters" are pre-defined services for IaaS. They are not needed in your case. 
Get some introduction from the _Technology Provider's Guide_. If then you'll have concret questions there, or in case you need help with certain implementations, then let me know. In this case please describe your need in detail in the issue.

**Comment by jarunkumarb** [comment]
sir am finding difficulty with importing platform service please provide steps to how to do that, because am bit confused in services and integration part please help me with providing steps what to be done for importing the service
currently i have deployed the application in docker and is running successfully the product is good but the services part is bit confusing could u please make it simple for me by providing steps.
