### ISSUE TITLE
Adapt OSCM Identity Service to use the IdentityClient when creating the groups

### ISSUE THREAD

**Issue by adamczykba** [servicecatalog/oscm#503]
**Summary**
As IdentityClient was implemented in OSCM commons, it is needed to adapt classes like AccessGroup to use it instead of their own methods.

**Details**
TBD

**Acceptance criteria**
- [ ] creating the groups in AzureAD is done via IdentityClient

**Additional context**
- https://github.com/servicecatalog/oscm-identity/issues/54
- https://github.com/servicecatalog/oscm/pull/487/files#diff-b5fa01617cb98d621ed08d4a7914eb53

**Comment by cworf91** [comment]
close https://github.com/servicecatalog/oscm/pull/514
