### ISSUE TITLE
Application displaying not available when registered service defination

### ISSUE THREAD

**Issue by karthik2189** [servicecatalog/oscm#506]
**Version Info**
v18

**Describe the bug**
Hi Sir/madam, 
   Thanks to the team for providing such a good product, am happy after experiencing the OSCM it is user friendly and very useful.
   When I try to register service definition under technical service it is showing as "is not available  | Cannot connect to the provisioning service". Am testing an application which has been already hosted in my network, am just copying the URL of that application and pasting at"Provisioning service URL" while register service definition under technical service.

Hosting Application:
    I have created an virtual machine(vm) in my network and i have deployed the application in that vm and from using the URL of the application am trying to register the service definition.
  
Also while configuring i have seen openstack and VMware  settings in var.env file because i dont know that i have left blank is that mandatory to configure for Saas also please let me know.  
   
**How to Reproduce**
1. Go to 'Technical service'
2. Click on 'Register service definition'
3. Select 'Direct access' 
4. In Provisioning service URL' pasting the URL of the application'
5. Save
6. Go to 'Import service definition '
7. Select the service posted and is showing "service is not available  | Cannot connect to the provisioning service"

**Observed behavior**
service is not available  | Cannot connect to the provisioning service

**Expected behavior**
The service should be available and want to subscribe 

**Screenshots**
![integration error](https://user-images.githubusercontent.com/56634876/66920162-6388e580-f040-11e9-9c76-f05d784cbdca.png)

**Comment by GoebelL** [comment]
I believe the service should be defined with access type external not direct. For a tight integration with all subscription, billing, reporting and user management etc. you need to provide an implementation of the provisioning service. 
Looks same as https://github.com/servicecatalog/oscm/issues/525#issuecomment-548364168
