### ISSUE TITLE
[SSO] Test APP integration

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#513]
**Summary**
Test provisioning and operations of APP controllers in OIDC mode. 

**Acceptance criteria**
-[ ] Instance creation and modification tested and issues reported if found
-[ ] Operations tests (e.g. Snapshot of VMWare adapter)
-[ ] Usage data billing events tested

**Additional context**
Not yet

**Comment by GoebelL** [comment]
Tested APP Sample Controller on latest SSO build (Open Service Catalog Manager 18.0PRIVATE-BUILD-ON-83C9C9B325AD2019/10/23) using Azure AD supplier user.

The provisioning works fine 
![grafik](https://user-images.githubusercontent.com/14805690/67473448-fafac380-f652-11e9-9bc5-20dd023a2ffe.png)

**Comment by farmakiG** [comment]
**Build Number**
Tested on jenkins SSO build (31/10/2019): a9d0e178f771f58e34f6d7dc825f43ecbcda703e

**Summary**
Tested App-Vmware Controller with default tenant. The APP Integration works fine.
Found issue #198 on oscm-dockerbuild. 

**Acceptance criteria**
-[X] Instance creation and modification tested and issues reported if found
-[X] Operations tests (e.g. Snapshot of VMWare adapter)
-[ ] Usage data billing events tested

 **Additional context**
Also test: 
- Billing events
- Openstack Controller
- Multiple tenants.
