### ISSUE TITLE
Create new pipeline for running Maven Selenium End-To-End Tests.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#519]
**Summary**
Create a new pipeline in Jenkins with groovy scripts for running the maven goals of Selenium IT Tests.

**Details**
The Maven job currently configured in Jenkins (OSCM_Integration_Tests) has two major drawbacks:

- The job runs in the maven installation located on jenkins itself, which is different from the maven installation located in the docker container, where all other build scripts are executed.

- The execution of the maven goals in this way is not stable, since the downloading of specific dependencies from the maven central repository often fails. 

Therefore the execution of the maven goals can be implemented in a pipeline with groovy scripts similar to the other jobs, such as OSCM_Build_And_Push and so on.
**Acceptance criteria**
The execution of the pipeline is stable.

**Comment by Crystalzord** [comment]
Done and merged to jenkins scripts master branch.
