### ISSUE TITLE
OIDC login redirect for marketplace not working properly

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#524]
**Version Info**
OSCM 18.1, SSO branch 28.10.2019

**Describe the bug**
After successful OIDC login started from a public marketplace, the user is redirected back to this marketplace, but it appears as logged out.

**How to Reproduce**

1. Ensure that you are logged out from SSO OIDC provider
2. Open a public marketplace in a new (!) browser window (e.g. sample marketplace from sample data) with URL https://FQDN:8081/oscm-portal/marketplace/index.jsf?mId=959c9bf7
3. On public marketplace page click login
4. When OIDC provider prompts for login, authenticate with user configured for this marketplace
5. After redirected back on the marketplace look at the page header

**Expected behavior**
After successful login the protected marketplace view is expected. The user is shown as logged in (the logout link is shown in the header). 

**Observed behavior**
Even login was successful, still only the public marketplace content is shown. The user appears as logout (the login link remains visible). Clicking login again only causes screen flashing but marketplace view remains appearing as logged out.

**Additional context**
Ask me if you need.

**Comment by GoebelL** [comment]
@elfriedegoetz please retest the fix

**Comment by elfriedegoetz** [comment]
works fine with  sso build from 12/11/2019
