### ISSUE TITLE
Asking to make the content more understandable

### ISSUE THREAD

**Issue by jarunkumarb** [servicecatalog/oscm#525]
**Version Info**
v18

**Describe the bug**
As i mentioned earlier am providing Saas and am trying to integrate my own application but not able to understand the content in the documentation please help me with this

	Before you begin, make sure that the following prerequisites are met:

	• The application to be integrated is **installed and operational**.
	• An application server is installed and operational.
	• You have access to the OSCM integration package.

in the above mentioned content am confused with the following line i found this in the technology provider document under chapter 3

The application to be integrated is **installed and operational**

i didn't understand where to be installed and operational please help me to understand.

**Comment by GoebelL** [comment]
Hi @jarunkumarb 

Let's say, you have a web application that you like to integrate in OSCM. What is meant here, is, that this has to be deployed in some webserver and accessible from OSCM via HTTP or HTTPS. In fact, it can reside outside the docker-compose network, staying loosly coupled with an independent lifecycle, or even inside same docker network bound to OSCM. This depends on how tighly you want to integrate it and whether you want to maintain it together with OSCM.
For example, you could setup a Tomcat container on the docker host, deploy your application in there and include this container in the OSCM docker compose network by adding it in the docker-compose-oscm.yaml file. Your provisioning service acts as an adapter for OSCM. You needed to implement such web service endpoint and expose it to OSCM by adding this in the technical service template that you import in OSCM.

**Comment by jarunkumarb** [comment]
Thank you for your fast response 
Sir, please let me know how to post my application as a service in oscm marketplace also am bit confused with access type while registering technical services definition if i choose direct access i found 
"Provisioning service URL: "  
which URL should be given for this attribute please let me know .

please provide procedure to enable at least one service eg. Account Service or Billing Service 
i have gone through with the documentation but am getting bit confusing please help me to resolve this.   
one last thing after deploying my application am just registering the technical service under technical service, i have given the application URL in the **Provisioning service URL:**   it is showing **not available  unable to connect to the service** is this the procedure or did i missed anything please let me know next to that am just exporting the technical service XML file of that service and edit that then again import the XML file.

**Comment by jarunkumarb** [comment]
Sir i tried by deploying my application in docker host but still showing **not avilable** i have created a tomcat container deployed my application is working fine and included that container in oscm-compose-oscm.yaml file still am facing the same issue please help to resolve the issue.  


![cmd error](https://user-images.githubusercontent.com/13447493/67949075-0890ea00-fc0d-11e9-84cc-a1c1f34fc852.png)
![not avilble error](https://user-images.githubusercontent.com/13447493/67949076-09298080-fc0d-11e9-952b-4817246931ee.png)
![running](https://user-images.githubusercontent.com/13447493/67949077-09298080-fc0d-11e9-810d-8703a064ba38.png)

**Comment by GoebelL** [comment]
I am revisiting your issue again. I guess this request is obsolete meanwhile. Nevertheless, as my hint - your technical service should not use _Direct Access_ if your integration is external. Use the access type _External_.
 
![image](https://user-images.githubusercontent.com/14805690/101647890-8db61780-3a39-11eb-988e-9ae33fd82793.png)


Overall, I still think that there is plenty of detailed [documentation and manuals](https://github.cm/servicecatalog/documentation), that describe the usage and how to integrate your services in OSCM - by far better than I could within my instant answers on this issue request.
