### ISSUE TITLE
Email for OIDC Provider

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#532]
**Summary**
The OIDC provider used for end-to-end testing, doesn't provide for specifying custom email addresses that are usable for OSCM tests. The task is to implement a workaround and set alternative email address field as needed for the end-to-end tests.

**Details**
Ask me.

**Acceptance criteria**
The required OSCM test users are created in with an email addresses that this accessible for OSCM tests.

**Additional context**
Ask me.

**Comment by kowalczyka** [comment]
As investigated and discussedd following changes would be needed:
- [ ] https://github.com/servicecatalog/oscm-identity/issues/69

**Comment by GoebelL** [comment]
The REST endpoint is available in the oscm-identity repository. This task is to implement the oscm-commons client for updating user email addresses (for test purposes for the time being)
