### ISSUE TITLE
Unable to connect to the OpenStack Controller

### ISSUE THREAD

**Issue by bharath7394** [servicecatalog/oscm#558]
**Version Info**
v18

**Describe the bug**
I have installed openstack but not able to connect with the oscm, I have give credentials in the oscm-app-openstack/ UI but if i get into the oscm-app/ and test the connection am getting "Unable to connect to the OpenStack Controller" error please help me out of this

**How to Reproduce**
1. Go to 'https://172.16.1.178:8881/oscm-app-openstack/'
2. Fill the credentials
3. Go to 'https://172.16.1.178:8881/oscm-app/'
4. Click on 'Test connection'
5. Unable to connect to the OpenStack Controller

**Observed behavior**
Unable to connect to the OpenStack Controller
**Expected behavior**
Test connection should get success
**Screenshots**
![Screenshot from 2019-11-13 17-32-53](https://user-images.githubusercontent.com/49364041/68763548-b86b4c00-063e-11ea-8dfa-9ba2f73e14de.png)

**Comment by GoebelL** [comment]
Hi @bharath7394 
did you set the correct keystone URL? 

> Steps to reproduce the behavior:
>    1. Go to 'https://172.16.1.178:8881/oscm-app-openstack/'
>    2. Fill the credentials
 >   3. Go to 'https://172.16.1.178:8881/oscm-app/'

Above credentials in step 2, you need to set the keystone connection and tenant credentials for your OpenStack server in 'https://...:8881/oscm-app-openstack/'.

**Comment by bharath7394** [comment]
Hi @GoebelL ,

Yes i have set correct keystone URL, i'll share details below for the same
![image](https://user-images.githubusercontent.com/49364041/68825433-1b50f780-06c0-11ea-868e-be58c61e826d.png)

API User=admin
API Password=**********
Keystone API URL=http://172.16.1.128:5000/v3
Tenant ID=a8821612ce1048caa93158ba0ef4ff41
Domain Name=Default

After that i have saved the configuration, and test it. Then i got same error which i have shared above.
Please let me guide, if i am miss something.
also please let me know,if any other configuration or any command output you want from my end.

Thanks

**Comment by GoebelL** [comment]
Hi @bharath7394 
ok, that looks like configuration is complete. However login to keystone is failing. Could you share the full stack trace shown above? 
Q:
1) How about your network: do you have direct connection to this OpenStack server or is there some HTTP proxy in between?  
2) How is the result if you curl keystone from inside the oscm-app container? 

```
docker exec -it oscm-app /bin/bash
curl -u ... http://...:5000/v3
```

**Comment by bharath7394** [comment]
I tried with above solution but am still facing the same issue and i have direct connection to this OpenStack server, I entered into container with the following command "docker exec -it oscm-app /bin/bash" and run the command  "curl -u ... http://172.16.1.128:5000/v3" after its asking for host password "***Enter host password for user '...':***" if i enter the openstack's admin(currently used project) password its showing "curl: (7) Failed connect to 172.16.1.128:5000; No route to host" error please help me to resolve this issue.

Below is the screenshots for your reference.

![Screenshot from 2019-11-20 11-34-35](https://user-images.githubusercontent.com/49364041/69213373-dd554700-0b89-11ea-988d-a9b590c1e146.png)


![Screenshot from 2019-11-20 13-07-50](https://user-images.githubusercontent.com/49364041/69218525-e8fb3a80-0b96-11ea-8dae-e0fa0a26fc20.png)

**Comment by GoebelL** [comment]
Seams that in your network this keystone server is not reachable. Can you ping the server from the oscm host? From inside oscm-app? Probably you need an HTTP Proxy to access it?

**Comment by bharath7394** [comment]
Dear,

Yes, I can able to ping my keystone server from oscm host and oscm-app docker container also.

oscm host output:
XXXX@docker:~# ping 172.16.1.128
PING 172.16.1.128 (172.16.1.128) 56(84) bytes of data.
64 bytes from 172.16.1.128: icmp_seq=1 ttl=64 time=0.735 ms
64 bytes from 172.16.1.128: icmp_seq=2 ttl=64 time=0.591 ms

oscm-app container:
[XXXX@6cf85b10766a /]# ping 172.16.1.128
PING 172.16.1.128 (172.16.1.128) 56(84) bytes of data.
64 bytes from 172.16.1.128: icmp_seq=1 ttl=63 time=0.778 ms
64 bytes from 172.16.1.128: icmp_seq=2 ttl=63 time=0.846 ms
64 bytes from 172.16.1.128: icmp_seq=3 ttl=63 time=0.787 ms

Below is the output of ifconfig and containers IP details:
ifconfig output:
br-722064b9caf6 IP
inet addr:172.18.0.1

docker0 IP
inet addr:172.17.0.1

**Host machine IP:
inet addr:172.16.1.178**

virbr0 IP
inet addr:192.168.122.1

**oscm-app Containers IP:
"IPAddress": "172.18.0.7",**

Kindly suggest how can I setup or configure HTTP proxy to access my keystone server via oscm

Thanks

**Comment by GoebelL** [comment]
HI @bharath7394 
Not sure you if you are using an HTTP proxy. If yes, you'll also need to configure this in the var.env file.
However, if you  can ping it, I believe something particular is missing on this endpoint. You can use some tools inside the app-container to debug such network issues. For example, you can use tcpdump. Let me clear this with our ops specialist. I'll get back to you.

**Comment by bharath7394** [comment]
Hi @GoebelL 
we are waiting for your response please help me to resolve the issue.

**Comment by bharath7394** [comment]
Dear @GoebelL 

We are waiting for valuable input from your side. Kindly suggest to fix this issue.

Thanks

**Comment by GoebelL** [comment]
Hi @bharath7394 
Sorry for late answer. I couldn't reach anyone for this issue so far. Strange is, if you get the error already from curl command in the oscm-app base image then I don't think that it's related to OSCM configuration. I rather believe, there is something specific on your network between your host and 172.16.1.128, like for instance some special routing for port 5000 HTTP requests, or similar.
Could you try to curl your keystone server on port 5000 from the OSCM Docker host? I mean, just try the same curl command outside the oscm-app container.
```
curl -u <your admin user>  http://<your keystone server>:5000/v3
```

**Comment by GoebelL** [comment]
Hi @bharath7394 
I'm just curious to hear about this keystone network issue. Did you get any progress here? Have you already tried with FQDN for this keystone server, e.g. adding a respective DNS entry?
