### ISSUE TITLE
HeaderUserId is not displayed into controllers

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/oscm#56]
[Version] OSCM 17.5.0 2017/11/29

[How to reproduce]

Login to controllers:

- /oscm-app/

- /oscm-app-openstack/
- /oscm-app/controller/?controllerid=ess.openstack

[Expected result]
In right top corner:
User ID : name_of_logged_user

[Observed result]
HeaderUserId is not displayed into controllers

[Details]
![no_name](https://user-images.githubusercontent.com/18006407/33430256-354511a8-d5d0-11e7-87b2-f613950bc67a.PNG)

**Comment by grubskim** [comment]
Works in the current version.
