### ISSUE TITLE
Two integration tests are failing

### ISSUE THREAD

**Issue by Crystalzord** [servicecatalog/oscm#560]
**Version Info**
18.1

**Describe the bug**
Integration tests are failing because they are unable to allocate two elements - login and logout forms.

**How to Reproduce**
1. Download oscm repository
2. use maven to install webtests base
3. use maven to run portal-integrationtests

**Observed behavior**
```
Tests run: 15, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 310.111 sec <<< FAILURE! - in org.oscm.portal.PlaygroundSuiteTest
org.oscm.portal.MarketplaceSubscriptionWT  Time elapsed: 23.194 sec  <<< ERROR!
org.openqa.selenium.WebDriverException: 
com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot read property "fn" from undefined (https://localhost:8081/oscm-portal/bootstrap/js/bootstrap.min.js#6)
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'estessbesci9.intern.est.fujitsu.com', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.21.1.el7.x86_64', java.version: '1.8.0_232'
Driver info: driver.version: HtmlUnitDriver
Caused by: com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot read property "fn" from undefined (https://localhost:8081/oscm-portal/bootstrap/js/bootstrap.min.js#6)
Caused by: net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot read property "fn" from undefined (https://localhost:8081/oscm-portal/bootstrap/js/bootstrap.min.js#6)

org.oscm.portal.MarketplaceSubscriptionWT  Time elapsed: 23.195 sec  <<< ERROR!
org.openqa.selenium.NoSuchElementException: 
Unable to locate element with ID: formLogout:logout
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'estessbesci9.intern.est.fujitsu.com', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.21.1.el7.x86_64', java.version: '1.8.0_232'
Driver info: driver.version: HtmlUnitDriver
	at org.oscm.portal.MarketplaceSubscriptionWT.cleanUp(MarketplaceSubscriptionWT.java:44)


Results :

Tests in error: 
org.oscm.portal.MarketplaceSubscriptionWT.org.oscm.portal.MarketplaceSubscriptionWT
  Run 1: MarketplaceSubscriptionWT.org.oscm.portal.MarketplaceSubscriptionWT ? WebDriver
  Run 2: MarketplaceSubscriptionWT.cleanUp:44 ? NoSuchElement Unable to locate element ...


Tests run: 15, Failures: 0, Errors: 1, Skipped: 0

```

**Expected behavior**
All elements should be visible/accessible and therefore the tests would not be failing.

**Additional information**
I suspect that **first** thing to be fixed should be this _TypeError: Cannot read property "fn" from undefined_ error.
I have googled a bit and there are quite a lot of similar problems. Most of the topics suggest that this might happen when either:
  - bootstrap library is loaded before jquery OR
  - some code is executed before the necessary library is loaded

I tried to put jquery library loading before bootstrap on my _fix_integration_tests_ branch, however it did not help. But i have done this only in two files, because the bootstrap library is only in two files. Those are from the oscm-portal module :
  - WebContent/marketplace/templates/head.xhtml
  - WebContent/marketplace/bootstrapLandingpage.xhtml
So maybe the problem is somwhere else? I do not know.

**Comment by GoebelL** [comment]
Let's reinvestiage this issue if it reoccurs in SSO mode. For now closed.
