### ISSUE TITLE
[SSO] It is possible to create organizations with the same name for one tenant.

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#565]
**Version Info**
SSO build from 2019/11/12

**Describe the bug**
It is possible to create organizations with the same name for one tenant.
In azure only one group with this name exists and contains the customers of both ctmg organizations.

**How to Reproduce**
1. create a organization  "TEST" for the default tenant
2. create a second organization  with the same name "TEST" for the default tenant
   ( set a different user as administrator )

**Observed behavior**
The second organization is created

**Expected behavior**
An error should be occur:  Organization already exist

**Comment by GoebelL** [comment]
Regarding the implementation of required fix:
Central domain level checks in AccountServiceBean#registerOrganization have to be enhanced checking for uniqueness of given names. Existing unique contraints and business keys on given domain objects (organization and tenant) must not be changed. As OIDC mode support is not released yet, database migration is out of scope.
