### ISSUE TITLE
can not log in oscm-app-vmware

### ISSUE THREAD

**Issue by Ivaylo68Ma** [servicecatalog/oscm#566]
I have installed OSCM.  I logged in oscm-app, but it is not possible to log in oscm-app-vmware. It constantly asks for username and password.

**Comment by GoebelL** [comment]
Hi @Ivaylo68Ma 

Please check the section "controller settings" in your 'var.env' file, which credentials you have given there.

**Example:**
```
CONTROLLER_ORG_ID=PLATFORM_OPERATOR
# Numerical user key of the controller administrator
# Please set to 1000 if you do not use the sample data
# Please set to 10000 if you  use the sample data (-e SAMPLE_DATA=true at oscm-d                                                                                                             eployer call)
CONTROLLER_USER_KEY=1000
# User name of the controller administrator
# Please set to administrator
CONTROLLER_USER_NAME=administrator
# Password of the controller administrator
# Please set to admin123
CONTROLLER_USER_PASS=admin123
 ```

**Comment by GoebelL** [comment]
In case you use 'administrator' you need to enable the organization and user roles. See [here](https://github.com/servicecatalog/oscm-dockerbuild#enable-login-to-app-and-controllers).

**Comment by Ivaylo68Ma** [comment]
Hi Lorenz,
Thank you for the responce! these are the setting in the var.env file:
"#######################
"# Controller settings #
"#######################
"# Organization ID for controller authentication
"# Please set to PLATFORM_OPERATOR if you do not use the sample data
"# Please set to 959c9bf7 if you use the sample data (-e SAMPLE_DATA=true at oscm                                                          -deployer call)
"CONTROLLER_ORG_ID=959c9bf7
"# Numerical user key of the controller administrator
"# Please set to 1000 if you do not use the sample data
"# Please set to 10000 if you  use the sample data (-e SAMPLE_DATA=true at oscm-d                                                          eployer call)
"CONTROLLER_USER_KEY=10000
"# User name of the controller administrator
"# Please set to administrator
"CONTROLLER_USER_NAME=administrator
"# Password of the controller administrator
"# Please set to admin123
"CONTROLLER_USER_PASS=admin123 "

Just to clarify - I can log in https://X.X.X.X:8081/oscm-app but it doesn't allow me to log-in https://X.X.X.X:8081/oscm-app-vmware. Repeatedly asks me for username and password.

**Comment by GoebelL** [comment]
Hi @Ivaylo68Ma 
Please fix the values of CONTROLLER_USER_KEY and CONTROLLER_ORG_ID in your var.env. First should be set 1000. And second is PLATFORM_OPERATOR in your case.

**Comment by Ivaylo68Ma** [comment]
Hi Lorenz,
Yes, it is fine now. 
Thank you!
