### ISSUE TITLE
[SSO] user Synchronization does not work

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#568]
**Version Info**
sso build from 12/11/2019

**Describe the bug**
user synchronization does not work

**How to Reproduce**
1. create a new organisation XXX
2. A new group is created in Azure with name OSCM_XXX
3. In Azure assign members to group OSCM_XXX
4. Go to "Mange timers" and click "reinitialize timers"

**Observed behavior**
nothing is happened

**Expected behavior**
The member of the Azure Group are created for this organization in CTMG

**Comment by cworf91** [comment]
Does not work because the id token has expired. Look at:
https://github.com/servicecatalog/oscm-identity/issues/77
