### ISSUE TITLE
[sso] "register new users" : wrong error message

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#569]
**Version Info**
sso build from 12/11/2019

**Describe the bug**
"register new users" : A wrong error message is generated if the user does not exist in azure.

**How to Reproduce**
1. Go to "register new users"
2. choose a new  User Id that does not exist in azure
3. click register

**Observed behavior**
error message: "The user ID Hans9 already exists. Please choose another ID."

**Expected behavior**
... "does not exist in Azure" or something like this

**Comment by cworf91** [comment]
This errormessage occures when a NonUniqueBusinessKeyException is thrown. Please check if the user is already registered in OSCM. If not, please append the logfiles.

**Comment by elfriedegoetz** [comment]
the user doesn't exist in oscm

**Comment by elfriedegoetz** [comment]
![user1](https://user-images.githubusercontent.com/15209605/69793166-36475f80-11c8-11ea-98fe-bd5e354fc8f3.PNG)

**Comment by elfriedegoetz** [comment]
![user2](https://user-images.githubusercontent.com/15209605/69793201-4101f480-11c8-11ea-9b8f-a7ec9e4b68c3.PNG)

**Comment by elfriedegoetz** [comment]
[oscm-core.txt](https://github.com/servicecatalog/oscm/files/3900846/oscm-core.txt)

**Comment by elfriedegoetz** [comment]
[oscm-identity.txt](https://github.com/servicecatalog/oscm/files/3900847/oscm-identity.txt)

**Comment by cworf91** [comment]
In the latest update the "Register new user" field was removed from the Portal. 
![1](https://user-images.githubusercontent.com/44837963/70241842-0d970b00-1770-11ea-9293-13505157d94a.PNG)
To register new users in SSO mode, they must be created in the OIDC provider. For registration in OSCM, there is a new feature under "Manage useres"
![2](https://user-images.githubusercontent.com/44837963/70241997-4f27b600-1770-11ea-81f9-3cea527cee2f.PNG)
