### ISSUE TITLE
Unable to activate or deactive service

### ISSUE THREAD

**Issue by srikanthsanivarapu** [servicecatalog/oscm#570]
Hi Team,

I have an issue with activating a published service. When I try to  Activate, I get Operation Failed message and no clear information. Could you please guide me the place where can I see the logs for this issue and also what could be the possible cause of this issue occurrence.

Regards,
Srik

**Comment by GoebelL** [comment]
Hi @srikanthsanivarapu 

Please send the stacktrace from the operation failed error. Therfore scroll the system.log file from the oscm-core container and copy the section with the timestamp matching  this error. Note that the time in the docker containers refer to GMT timezone.
Run following commands 
```
docker exec -it oscm-core bash
cat /logs/system.log | more
```
