### ISSUE TITLE
VMware Connector: root password not set correctly for new Linux VM provisioned

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#577]
**Version Info**
OSCM 18.0

**Describe the bug**
We set an value, e.g. test123 as password for a Linux VM (provisioned by VMware connector).
This password is not taken for the new VM. The original password of the template remains.
**How to Reproduce**
**Expected behavior**
use root password as specified on service booking

**Comment by GoebelL** [comment]
Duplicate with https://github.com/servicecatalog/oscm-app/issues/55.
