### ISSUE TITLE
Organization Chooser Sorting

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#579]
**Summary**
List sorting of the "Organization ID" input field in the admin portal Operation Pages.

**Details**
Operation Menu:
   * Billing data preview: “Organization ID” field.
   * Manage Users: “Organization ID” field.
   * Manage organization: “Organization ID” field.

Marketplaces Menu:
   * Create marketplace: Select a marketplace owner
   * Update marketplace: Select a marketplace owner

**Comment by GoebelL** [comment]
This has been implemented for v19.
