### ISSUE TITLE
[sso] bad info message in log file during user synchronize

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#583]
**Version Info**
sso build from 29/11/2019

**Describe the bug**
system.log of  oscm-container:
00.700 FSP_INTS-BSS: INFO: ThreadID EjbTimerPool - 14: OidcSynchronizationBean: ?? key 'ERROR' not found ??

**How to Reproduce**
1. start timer for user synchronization 

**Observed behavior**
?? key 'ERROR' not found ?? in system.log

**Additional context**
the user synchronization works fine

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-commons/pull/30
https://github.com/servicecatalog/oscm/pull/595
