### ISSUE TITLE
[SSO] incompatibility with Guava versions

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm#598]
**Version Info**
18.1 SSO

**Describe the bug**
When I try to login at host/oscm-app/, I get the following exception:
[https-jsse-nio-8881-exec-7] - ERROR - doFilter: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class org.richfaces.component.DataTableDataChildrenIterator
Therefore, it´s not possible to log into app or a controller. 

**How to Reproduce**
1. Go to https://host:8881/oscm-app/
2. Fill out the form
3. Try to login
4. See loginscreen again

**Observed behavior**
The login is not possible.

**Expected behavior**
The login works

**Additional context**
The solution could be to use an older guava version (below 20.0):
https://bugs.eclipse.org/bugs/show_bug.cgi?id=509791
Currently in the oscm-commons package the version 28.1 is used.

**Comment by GoebelL** [comment]
Fyi, the new guava version was introduced in oscm-commons on Nov 26th ->
https://github.com/servicecatalog/oscm-commons/commit/1e752dcadaff6cfb647f0197d007a3e3cf3484b4
This lib also gets packaged into oscm-app-startup.war which causes the issue with richfaces.

**Comment by kowalczyka** [comment]
Resolved within: https://github.com/servicecatalog/oscm-app/commit/cb292b2cba5fcaae274a88fa0e64a5c45bab5b44
