### ISSUE TITLE
Approval Tool: Show subscription parameters

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#599]
**Summary**
when opening an approval task in the approval tool selected/configured subscription parameters shall be visible to the approver. This allows him to decide to approve or reject.

The list of parameters shall be configurable as one list of parameters for all technical services,

e.g. [AMOUNT_OF_RAM, NUMBER_OF_CPU, RESOURCE_GROUP_NAME]

**Comment by GoebelL** [comment]
Done. Added new technical service parameter DISPLAY_PARAMS, accepting a comma separated list of parameter IDs, for configuring the subset of displayed service parameters.
