### ISSUE TITLE
Chrome: Service Instance Details of controller instance looks weird

### ISSUE THREAD

**Issue by DawidCh** [servicecatalog/oscm#6]
_From @SylviaDehn on October 17, 2017 11:38_

[Version] OSCM 17.4.0 2017/10/16
Docker image with TomEE
Chrome ONLY

[How to reproduce]
1. go to controller service instances url
e.g. 
http://estst1.intern.est.fujitsu.com:8880/oscm-app/controller/?controllerid=ess.openstack
2. double click on an instance and page down in dialog box

[Expected result]
dialog box looks normal

[Observed result]
you can read the dialog box but there is a funny moving pixel background s. attachment 

[Details]
see attached file

_Copied from original issue: servicecatalog/development#863_

**Comment by DawidCh** [comment]
_From @SylviaDehn on October 17, 2017 11:39_

![serviceinstancedetails](https://user-images.githubusercontent.com/15086024/31662914-8b14dc1a-b340-11e7-8ddf-3518d4f0fcb9.png)

**Comment by grubskim** [comment]
Cannot reproduce the error.

Tested with Chrome 62.0.3202 (latest version), everything appears fine:
![openstack_popup](https://user-images.githubusercontent.com/14539765/33136333-413d4362-cfa5-11e7-96c1-306e6bc92e22.PNG)

**Comment by kwodzynski** [comment]
I cannot reproduce the problem as well. Version of Google Chrome: 62.0.3202.94
