### ISSUE TITLE
Error while starting the container for initializing the database

### ISSUE THREAD

**Issue by thinkerw** [servicecatalog/oscm#602]
description:
1、images from https://hub.docker.com/r/servicecatalog/oscm-deployer
2、run the   "   docker run --name deployer2 --rm -v /docker:/target -v /var/run/docker.sock:/var/run/docker.sock -e INITDB=true -e STARTUP=true servicecatalog/oscm-deployer  "

then I can't visit https://ip:8081/oscm-portal，but I can visit the tomcat console https://ip:8081/
screenshot:
![error](https://user-images.githubusercontent.com/4736058/70795227-4bcca400-1dda-11ea-90e8-c7412c5a9cd6.png)

**Comment by GoebelL** [comment]
Hi @wuweilue 
Please check the value of BASE_URL_HTTPS you have given in the var.env file. Seems the it has an invalid syntax.

**Comment by thinkerw** [comment]
Hi @GoebelL 
     I get the docker images again and 
      run the " docker run --name deployer2 --rm -v /docker:/target -v /var/run/docker.sock:/var/run/docker.sock -e INITDB=true -e STARTUP=true servicecatalog/oscm-deployer "

      then I Encountered the following problem
![image](https://user-images.githubusercontent.com/4736058/70960091-00a3e100-20b9-11ea-93fb-535401b6dcb2.png)
      
       Can you tell me, which version, I can run up?  Thank you.  or have  Complete deployment documentation, just follow the steps and Run smoothly。

        Think you!

**Comment by GoebelL** [comment]
Hi @wuweilue 
This looks like some issue with openssl generating private keys on your host. In order help you we need more information. Please answer following questions.
a) Check var.env again. Is HOST_FQDN set correctly?
b) What is the name and version of your Linux distribution? 
c) Which versions of docker do you use?  
d) Which containers are running after executing deployer2 with above command? Check with `docker ps`. 

OSCM setup documentation can be found [here](https://github.com/servicecatalog/documentation).

**Comment by thinkerw** [comment]
Hi @GoebelL
Think you very much !
1、CentOS Linux release 7.4.1708 (Core)
![image](https://user-images.githubusercontent.com/4736058/71011986-4f895f00-2129-11ea-9dce-67f34718482a.png)
2、Docker version 19.03.5, build 633a0ea
![image](https://user-images.githubusercontent.com/4736058/71012099-83648480-2129-11ea-9567-cff658081160.png)
3、I check again the HOST_FQDN in var.evn，look like no problem. and  no any more BASE_URL_HTTPS errors
![image](https://user-images.githubusercontent.com/4736058/71013115-1c47cf80-212b-11ea-86b6-3e0522d3c8f1.png)
4、Run docker ps command, the results are as follows 
![image](https://user-images.githubusercontent.com/4736058/71014288-acd2df80-212c-11ea-9812-724af7f88cd6.png)

Think you!

**Comment by thinkerw** [comment]
Hi @GoebelL
I want to ask a quesiton please. Look at the error message，Is there a place to configure the certificate？ which key in var.env？   Because run the last version I didn't see the problem。

**Comment by GoebelL** [comment]
Hi @wuweilue
Yes there was a small change on the oscm-deployer recently, that configures default certificates for new identity service. 
Not totally sure, but I imagine that openssl fails to create the certificate CN name here, because the IP is beeing given instead of the full qualified domain name of the host. If not yet existing, I suggest to set a static full qualified hostname for your docker host and adapt the var.env accordingly. On CentOS 7 this should be possible from command-line - something like `hostnamectl set-hostname ...`.
This could help to get OSCM starting up.

**Comment by thinkerw** [comment]
Hi @GoebelL
      I  reinstalled the version for v18.02, the OSCM Started。
![image](https://user-images.githubusercontent.com/4736058/71140069-1d701e00-224b-11ea-8fb8-a508e266bf5c.png)
      But it still doesn't work
![image](https://user-images.githubusercontent.com/4736058/71140142-54463400-224b-11ea-99f1-83c008be23d2.png)

**Comment by thinkerw** [comment]
Hi @GoebelL 
        I tried many times, but the problem still couldn't be solved.

1、hostnamectl
![image](https://user-images.githubusercontent.com/4736058/71166147-0d792e00-228d-11ea-8daf-1d88492aa0de.png)
2、var.env
![image](https://user-images.githubusercontent.com/4736058/71166249-41545380-228d-11ea-9077-7c5f8c1aa0b2.png)
3、hosts
![image](https://user-images.githubusercontent.com/4736058/71166329-706ac500-228d-11ea-9e94-19d7a301efb9.png)

![image](https://user-images.githubusercontent.com/4736058/71166408-a0b26380-228d-11ea-9a74-9511623898dd.png)

**Comment by thinkerw** [comment]
Hi @GoebelL
      I found that errors is very likely to run the script of "openssl req -new -passin ".
     So I look the script of oscm-deployer/start.sh,find the script "openssl req -new -passin file:/tmp/passphrase.txt -key /tmp/ssl.key -out /tmp/ssl.csr -subj "/CN=${HOST_FQDN}"" . Try to run alone it. But I cann't find erros.
![image](https://user-images.githubusercontent.com/4736058/71223287-62a95400-230e-11ea-8f25-6203cd9dbbf4.png)

![image](https://user-images.githubusercontent.com/4736058/71223268-58875580-230e-11ea-9f71-81b0c5963bd7.png)

**Comment by GoebelL** [comment]
Hi @wuweilue 
Ok, I see there is a different issue now. I am looking to the first screenshot you posted yesterday. As shown there, the application containers are all running except for oscm-identity. The Tomee is up as well, but the oscm-portal is not getting deployed. I also see that the oscm-deployer has pulled all containers from latest tag. Please note that latest OSCM also includes and requires the identity service and a few new settings. I fear you have a mixture of different versions in your environment now. 
I suggest to install from scratch:
1. backup your var.env file 
2. pull oscm-deployer from latest again 
3. run deployer1 as described [here ](https://github.com/servicecatalog/oscm-dockerbuild#prepare-configuration-files)
You can copy all env values from your backup file, except for may be three or four new settings. But the default values described in the comments inside the file should work well.

**Comment by thinkerw** [comment]
Hi @GoebelL 
     Thank you! I try again according to your method, The Result As Follow:
1、The application containers are all running  include oscm-identity.
2、But  run docker logs -f oscm-core，I find some errors，Var.env and docker-writer-initdb.yml key value have been modified。
      The complete screenshot  is as follows，Could you tell me  How do I configure these incorrect keys in the tomcat log。
      I've got to get the oscm running，thanks!

![image](https://user-images.githubusercontent.com/4736058/71281428-d2fcb780-2398-11ea-8afe-70d879367a94.png)
![image](https://user-images.githubusercontent.com/4736058/71281441-e019a680-2398-11ea-97c5-58cce03cfb79.png)
![image](https://user-images.githubusercontent.com/4736058/71281458-ea3ba500-2398-11ea-806e-19b18d1e2bb1.png)
![image](https://user-images.githubusercontent.com/4736058/71281485-f4f63a00-2398-11ea-9da2-ae247c54742f.png)
![image](https://user-images.githubusercontent.com/4736058/71281502-02132900-2399-11ea-94ef-67fc21256577.png)
![image](https://user-images.githubusercontent.com/4736058/71281524-135c3580-2399-11ea-93db-85f833d09fb8.png)

![image](https://user-images.githubusercontent.com/4736058/71281744-98dfe580-2399-11ea-83da-84da010da0db.png)
![image](https://user-images.githubusercontent.com/4736058/71282734-e6f4e900-2399-11ea-9d68-ff4629107f3d.png)
![image](https://user-images.githubusercontent.com/4736058/71282920-f4aa6e80-2399-11ea-9166-1a0cff83b000.png)
![image](https://user-images.githubusercontent.com/4736058/71283040-00963080-239a-11ea-989c-03029ff7251f.png)
![image](https://user-images.githubusercontent.com/4736058/71283092-29b6c100-239a-11ea-8ff0-e7b73f44030c.png)

**Comment by thinkerw** [comment]
Hi @GoebelL
     Continue to the previous question，Check the code to find the reason, and find that the key value is taken from the database, and the data source is configured in tomcat. var.env has been configured with key values, I don't know why the configuration setting table of the bss database has no data, and the writable in docker-compose-initdb.yml has been changed to true during initialization.

![image](https://user-images.githubusercontent.com/4736058/71302025-5d690980-23e1-11ea-9ac6-e57684bfc51a.png)

**Comment by thinkerw** [comment]
Hi @GoebelL
         After trying many times, the reason why oscm-portal cannot be accessed is that the following key cannot be found in the tomcat log, but in fact var.env has been configured. Help. This needs to be resolved as soon as possible.
         Thank you very much！
BASE_URL_HTTPS=https://192.168.0.96:8081/oscm-portal
LOG_FILE_PATH=/opt/logs
PSP_USAGE_ENABLED=false
TAGGING_MAX_TAGS=50
TAGGING_MIN_SCORE=10
WS_TIMEOUT=60000
AUDIT_LOG_ENABLED=false
AUDIT_LOG_MAX_ENTRIES_RETRIEVED=10
MAX_NUMBER_ALLOWED_USERS=100
TIMER_INTERVAL_USER_COUNT=100
AUTH_MODE=INTERNAL

**Comment by thinkerw** [comment]
Hi @GoebelL
     thank you very much！
     The problem has been solved, by looking at the code, insert the missing key into the database.
![image](https://user-images.githubusercontent.com/4736058/71402023-b3021800-2666-11ea-9213-63034295656f.png)
