### ISSUE TITLE
[SSO] update marketplace:the tenant must not be changed, otherwise login is no longer possible

### ISSUE THREAD

**Issue by elfriedegoetz** [servicecatalog/oscm#606]
**Version Info**
Open Service Catalog Manager 18.1

**Describe the bug**
update marketplace: the tenant must not be changed, otherwise login is no longer possible for customer

![Tenant](https://user-images.githubusercontent.com/15209605/71244160-31328780-2312-11ea-81e6-56d170fda142.PNG)

**Comment by GoebelL** [comment]
Solution is to make the tenant ID field read-only in  the update marketplace dialog.
