### ISSUE TITLE
Update log4j

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#607]
**Summary**
Upgrade log4j libs is indicated by reported CVEs.

**Details**
https://github.com/servicecatalog/oscm/network/alert/oscm-webtest-base/pom.xml/log4j:log4j/open
https://github.com/servicecatalog/oscm-app/network/alerts

**Acceptance criteria**
-[ ] CVE is fixed

**Additional context**
Not needed.

**Comment by kowalczyka** [comment]
Closing as the task will be continued within:
- https://github.com/servicecatalog/oscm-commons/issues/41
- https://github.com/servicecatalog/oscm-app/issues/74
