### ISSUE TITLE
UI tests are failing

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm#622]
**Version Info**
Latest

**Describe the bug**
After latest UI changes, some of related UI tests are failing with:
`com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "RichFaces" is not defined.`

**How to Reproduce**
1. Configure UI tests environment
2. Run PortalMarketServiceWT test suite

**Observed behavior**
Tests are failing with descibed exception

**Expected behavior**
Tests are passing

**Additional context**
The tests were passing before following changes: https://github.com/servicecatalog/oscm/commit/d4e78523bc05e13b7a7c442dba69a9da22b915fe

Related Jenkins job: http://10.140.16.80:8080/view/Docker_OSCM/job/OSCM_Integration_Tests_Upgrade/

**Comment by mchudy-fujitsu** [comment]
There seems to be an issue with RichFaces and BootsFaces compatibility, even adding empty <b:selectOneMenu> causes mentioned issue. On web browser it seems working fine however inside developer console you can see two errors which are causing selenium tests to fail:
ReferenceError: RichFaces is not defined
TypeError: $ is not a function

![jsf](https://user-images.githubusercontent.com/58510012/72731046-1f533700-3b93-11ea-817e-d44aac950514.png)

**Comment by GoebelL** [comment]
Hi @farmakiG
@mchudy-fujitsu is right here. Looks that these controls are missing some adaption for bootsfaces. Do you have any replacement idea? Since this is a UI test blocker, any workaround to overcome that could be appreciated.

**Comment by farmakiG** [comment]
A workaround would be to remove the Richfaces namespace: **xmlns:rich="http://richfaces.org/rich"**, in the pages with b:selectOneMenu where Richfaces is not used.

**Comment by mchudy-fujitsu** [comment]
I tried to remove this namespace with no success still, the same error appears. The current testing issue is caused by selenium not allowing any JavaScript related exceptions to appear, the possible workaround is ignoring JavaScript exceptions in selenium which will allow tests to run. I will look into finding is there is a way to ignore specific exceptions.
