### ISSUE TITLE
UI tests related projects refactoring

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm#623]
**Summary**
Currently UI tests are spread into two separates maven projects:
- oscm-webtest-base
- oscm-portal-integrationtests

This is not needed as these are using similar dependencies and common configuration. Additionally one is included in src/main while the other in src/test. This could be improved.

**Details**
Let's introduce single oscm-ui-tests maven project containing both codebase and the tests which will standarize used libraries and plugin configuration.

**Acceptance criteria**
- [ ] new project is built without any issues
- [ ] ui tests included are successful

**Additional context**
This task would require also changes in Jenkins script related to job which execute test

**Comment by GoebelL** [comment]
Related with #628
