### ISSUE TITLE
Skip Selenium Tests from Codecov

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#628]
**Summary**
Exclude Selenium Tests from codecov.

**Details**
The Selenium Test Cases should be excluded from codecov. They are Java-based but should not be executed by the Travis CI (as it makes little sense to add unit tests about test classes).

**Acceptance criteria**
The Selenium Test Cases are ignored by codecov.

**Additional context**
N/A

**Comment by GoebelL** [comment]
Related with #623

**Comment by Piotr-K8i** [comment]
![image](https://user-images.githubusercontent.com/59691196/73529786-92706f00-4417-11ea-8aaa-e837847e8248.png)

Nothing to change - CODECOV untracked this files
