### ISSUE TITLE
initial sample data does not ok

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#63]
[Version] OSCM 17.5.x 2017/12/11

[How to reproduce]

1. build and start containers with sample data (not in SOC environment)
2. log in as sample customer and subscribe to SOC sample service. I know this will lead to nothing good, but I just wanted to "play around"
3. look at status of subscription 
=> stays in pending (forever) NOK, I would expect an error here
4. delete subscription
5. log in as techprovider to
http://estst1:8880/oscm-app/controller/?controllerid=ess.openstackand check if entry for instance is gone 
=> instance is waiting for termination (but it will be forever)
6. as techprovider try "deprovision" and "delete"

[Expected result]
I hope to get rid of the instance

[Observed result]
Error message "The subscription cannot be terminated.: EXCEPTIONID 1512989973532: EXCEPTIONID 1512989973532: Organization 'cd9f7b9c' is not supplier of customer 'e044fb2e'"

[Details]
e044fb2e - is the sample customer org
cd9f7b9c - is the sample tech provider (not supplier)
I do not know why this is checked here, but it seems incorrect. The sample data should work.
Actually I do not know if this has always been an issue since my (in my usual setup without sample) techprovider and supplier are usually the same organization.

**Comment by kowalczyka** [comment]
Closing with spliting into two different issues:  
- https://github.com/servicecatalog/oscm/issues/66
- https://github.com/servicecatalog/oscm-dockerbuild/issues/96
