### ISSUE TITLE
Organization create fails with "The operation failed. "

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#64]
[Version] OSCM 17.5.x 2017/12/11 (master)

[How to reproduce]

1.    build and start containers with sample data
2.    log in as platform operator "administrator" and create organization with
      supplier and technology provider role. Fill out info
3.   save

[Expected result]
organization is created

[Observed result]
operation failed

[Details]
see attached file
[ErrCreateOrganization.txt](https://github.com/servicecatalog/oscm/files/1547753/ErrCreateOrganization.txt)

**Comment by kowalczyka** [comment]
It is a problem with constraint in a sample data provided. Therfore moved to docker repo.

Related issue: https://github.com/servicecatalog/oscm-dockerbuild/issues/95
