### ISSUE TITLE
Group is created on Azure AD when creating an organization failing.

### ISSUE THREAD

**Issue by mchudy-fujitsu** [servicecatalog/oscm#650]
**Version Info**
18.1

**Describe the bug**
Group is created on Azure AD when creating an organization failing.

**How to Reproduce**
1. Go to 'oscm-portal/operator/createOrganization.jsf.'
2. Create a new organization for a user already having an organization.

**Observed behavior**
After failure on creating a new organization, the new organization is created inside Azure AD.

**Expected behavior**
No new organization on Azure AD is created.

**Screenshots**
![bug1](https://user-images.githubusercontent.com/58510012/74225891-da1ab480-4cbb-11ea-897d-ff80dbea68af.png)
![bug2](https://user-images.githubusercontent.com/58510012/74225904-ddae3b80-4cbb-11ea-958d-b92e7dbe2bc3.png)

**Comment by GoebelL** [comment]
This works as designed. Indeed the operation is not rolled back in Azure AD, but it is repeatable and resuming well after correcting the user in step 2. Actually, the main point and desired behaviour is, that the administrator can recover from such errors and create eventual consistency by correcting his operations.
