### ISSUE TITLE
A User is getting assigned to an already existing organization.

### ISSUE THREAD

**Issue by mchudy-fujitsu** [servicecatalog/oscm#652]
**Version Info**
18.1

**Describe the bug**
A User is getting assigned to an already existing organization.

**How to Reproduce**
1. Go to 'oscm-portal/operator/createOrganization.jsf'
2. Create an organization with a name already in use.
3. Go to 'oscm-portal/operator/manageUsers.jsf'
4. Reload users from OIDC

**Observed behavior**
Page returns failure, however on Azure AD user is getting assigned to already existing organization. After reloading users from OIDC, the user is able to log in to the organization.

**Expected behavior**
The user is not added to the organization.

**Screenshots**
![bug3](https://user-images.githubusercontent.com/58510012/74228399-a726ef80-4cc0-11ea-9be8-16faafd1e841.png)
![bug4](https://user-images.githubusercontent.com/58510012/74228422-b1e18480-4cc0-11ea-9cd6-3b7b1aa76ab1.png)
![bug5](https://user-images.githubusercontent.com/58510012/74228427-b443de80-4cc0-11ea-88c0-c7fd60c9d8de.png)
![bug6](https://user-images.githubusercontent.com/58510012/74228435-b5750b80-4cc0-11ea-984e-57f3e8111236.png)

**Comment by GoebelL** [comment]
The bug description is a little missleading. The actual issue is on the createOrganization operation. In fact the createOrganization is not rolledback completely on the given error. Note that it's a distributed transaction: First the OIDC group is retrieved or created (1), then the given user is assigned to that group (2), then the platform user and organization are created in the oscm db (3). After the 'already existing error' only (3) is rolledback.

**Comment by GoebelL** [comment]
The reload users function behaves correctly.

**Comment by GoebelL** [comment]
In given case, the requested solution is to place a uniqueness check for the chosen organization name before delegating to the createGroup endpoint.

**Comment by GoebelL** [comment]
Hi @mchudy-fujitsu 
here some details regarding the fix approach described in my previous comment.

My suggestion is to enhance org.oscm.internal.tenant.ManageTenantService with a new method:

```java
public void validateOrgNameUniqnessInTenant(String orgName, String tenantId) throws ValidationException

```
The caller shall be placed before delegating to the OIDC service. This is A), in the respective UI controller, after determining [the chosen tenant id](https://github.com/servicecatalog/oscm/blob/master/oscm-portal/javasrc/org/oscm/ui/beans/operator/OperatorOrgBean.java#L178).
And B), for the supplier administrator, in the backing bean implementation for registerCustomer, before [retrieving the user details of customer administrator](https://github.com/servicecatalog/oscm/blob/master/oscm-portal/javasrc/org/oscm/ui/beans/OrganizationBean.java#L567).
