### ISSUE TITLE
Status of subscription stays in pending state forever

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm#66]
[Version] OSCM 17.5.x 2017/12/11

[How to reproduce]

1. build and start containers with sample data (not in SOC environment)
2. log in as sample customer and subscribe to SOC sample service. I know this will lead to nothing good, but I just wanted to "play around"
3. look at status of subscription 

[Expected result]
Error message.

[Observed result]
Subscription stays in pending (forever)

**Comment by GoebelL** [comment]
The SOC technical service doesn't exist any more. This issue is void.
