### ISSUE TITLE
Highlight of label next to Dropdown.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#673]
**Summary**
Add the blue highlight of label next to Bootsfaces Dropdown.

**Details**
To all pages where new Dropdown has been introduced, highlight the label with blue color when the Dropdown has the focus.
A new javascript file: select2FocusHandler.js has been already implemented. You simply have  to add this javascript source to the pages where the new Dropdown is used and test that the page is working fine.

**Acceptance criteria**
The modified pages have the blue highlight.

**Additional context**
N/A

**Comment by GoebelL** [comment]
Consider to fix this on higher level via some facelet.
