### ISSUE TITLE
Re-implement selectOrganizationInclude.xhtml

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#676]
**Summary**
Re-implement from scratch "selectOrganizationInclude.xhtml".
Also, re-implement from scracth calling page: selectOrganization.xhtml.

**Details**
The existing page uses the rich:autocomplete component of the Richfaces framework in order to provide some suggested organizations, calling respective bean methods of the "OperatorSelectOrgBean". This mechanism is unnecessarily complicated.

Instead, a b:selectOneMenu with a Search field will be used to simply retrieve all available organizations. The values for the available Organizations can be retrieved from a bean, e.g. OperatorSelectOrgBean.availableOrgs

**Acceptance criteria**
The functionality of all affected pages where the selectOrganizationInclude is used (see Epic) remains as before. The usability of affected pages is improved.

**Additional context**
Add any other context or screenshots about the task.

**Comment by GoebelL** [comment]
Remaining: Complete refactoring of Organization Operator UI.
