### ISSUE TITLE
help '?' is in wrong position in portal

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#68]
[Build] 17.6 2017/11/02

[Steps to reproduce]
Using Firefox
1. log in to portal
2. look for help ?

[Expected result]
usually this is found on the right side of page

[Observed result]
squished in the middle

[Details]
see below
![ctmg_help](https://user-images.githubusercontent.com/15086024/35041433-0e677c30-fb85-11e7-9f79-dd5fbfb18fc2.png)

**Comment by grubskim** [comment]
Added missing CSS class in ESCM version
