### ISSUE TITLE
Update QuickStart Guide 

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm#685]
**Summary**
Due to the new container oscm-maildev, the QuickStart Guide is out of date. On page 9 is a bash script which imports the images into a registry. The new oscm-maildev image should be added to this script.

**Comment by GoebelL** [comment]
@cworf91 This was done in https://github.com/servicecatalog/documentation/blob/master/Development/oscm-doc-user/resources/manuals/installation+operation/en/QuickStart.pdf
