### ISSUE TITLE
OSCM OIDC mode issue with reverse proxy 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#689]
**Version Info**
v18.1

**Describe the bug**
OSCM 18.1 in OIDC mode is not usable with reverse proxy. This is due to hardcoded application paths and ports, like [here](https://github.com/servicecatalog/oscm/blob/master/oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java#L114)
These shall be removed and tested with reverse proxy.

**How to Reproduce**
1. Setup OSCM in OIDC mode with a default tenant as described in the Operator's Guide 
2. Setup a webserver and configure oscm-portal location on 443 with a reverse proxy rule (ask me how to) 
3. Try to access the oscm-portal

**Observed behaviour**
The oscm-portal is not accessible with custom URL (because hardcoded ports and application contexts as shown above)

**Expected behaviour**
The oscm-portal is accessible with custom URL.

**Additional context**
Note: OSCM v18.1 in internal mode is working well with reverse proxy using custom URLs on default HTTPS port 443.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/710
https://github.com/servicecatalog/oscm-commons/pull/43
