### ISSUE TITLE
OSCM internal mode error log 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#692]
**Version Info**
v18.1 internal mode

**Describe the bug**
Though running OSCM in internal authentication mode, we are getting several OIDC related error log entries.

**How to Reproduce**
Steps to reproduce the behaviour:
1. Install v18.1 in internal mode
2. Start tracing oscm-core container with ```docker logs -f oscm-core```
3. Let it server run for one day

**Observed behaviour**
The daily OIDC user synchronization runs regardless of the configured authentication mode and subsequently several errors are logged.

**Expected behaviour**
OIDC synchronization is skipped for internal mode and nothing related gets logged.

**Additional context**
N/A

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm/pull/700
