### ISSUE TITLE
Operation Failed in customizeLandingPage.jsf

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#709]
**Version Info**
Build: /view/Docker_OSCM/job/OSCM_Docker_Build_and_push/556/
Deployed at estessbesci9

**Describe the bug**
Operation Failed in Define Featured Services page, when no marketplace is selected first.

**How to Reproduce**
1. Log-in to admin portal as administrator.
2. Go to "Marketplace->Define Featured Services" page.
2. Select "Marketplace 3".

**Observed behavior**
Operation failed message appears.

**Expected behavior**
Marketplace 3 is selected and its featured services appear.

**Screenshots**
![OperationFailed](https://user-images.githubusercontent.com/49904723/76308759-c6b73500-62cb-11ea-863a-8fcfeb3a766c.png)

**Log file**
[error.txt](https://github.com/servicecatalog/oscm/files/4312193/error.txt)

**Comment by GoebelL** [comment]
This shall be fixed together with #697, which makes the invalid use case "when no marketplace is selected" void.
