### ISSUE TITLE
RESTful API Sample 

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#716]
**Summary**
Create readme description for getting started with the OSCM REST API. 

**Details**
In latest version we have included the OSCM Sample adapter and REST API. The idea here is to elaborate a sample use case for OSCM provisioning using the OSCM REST API. Therefore, this request here is to create a readme like description that contains a sequence of REST calls with respective HTTPS requests and JSON data required for:
* As Supplier defining a Free of Charge Marketable Service S on base of the Sample Adapter
* As Supplier defining service parameter values
* As Supplier publishing S on the existing sample marketplace
* As Customer subscribing S in the marketplace
* As Customer assigning own users to the created Service Subscription   

As side result, any discovered issues shall be noted down and descriptions in the Swagger doc shall be improved where indicated in a separate document. 
 
**Acceptance criteria**
- [ ] Document contains an appealing and professional description that is easy to understand
- [ ] Listed steps can run out-of-the-box on a fresh and with sample data installed OSCM 
- [ ] Document contains improved usage descriptions and list of discovered issues (to be attached in a separate GitHub issue on the oscm-rest-api repo)

**Additional context**
N/A

**Comment by GoebelL** [comment]
Hi @kowalczyka 
Please feel free to comment here.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-rest-api/pull/202
