### ISSUE TITLE
Birt reports are not shown

### ISSUE THREAD

**Issue by victorhrsilva** [servicecatalog/oscm#73]
[Build] 17.6 2018/01/18

[Steps to reproduce]

- Login to ESCM Marketplace
- Go to Account -> Reports
- Select a Report

[Expected result]
Birt report be shown properly

[Observed result]
Reports are out of format:

![image](https://user-images.githubusercontent.com/24247646/35139736-bb50529e-fcf4-11e7-89c8-16019d556851.png)

[Details]
Error message on oscm-birt: `- Unable to find required classes (javax.activation.DataHandler and javax.mail.internet.MimeMultipart). Attachment support is disabled.`

**Comment by badziakp** [comment]
Hi Victor,
do you use HTTPS to enter to the marketplace? What is your REPORT_ENGINEURL?

**Comment by victorhrsilva** [comment]
Hello,
Yes, I am using HTTPS. My URL is https://linux-7aon.pl.fsc.net:8681/birt/frameset?__report=${reportname}.rptdesign&SessionId=${sessionid}&__locale=${locale}&WSDLURL=${wsdlurl}&SOAPEndPoint=${soapendpoint}&wsname=Report&wsport=ReportPort

**Comment by GoebelL** [comment]
Tested build from 2018/01/30 (PRIVATE-BUILD-ON-E56EDFE59045). Reports are working fine.

@victorhrsilva 
What is the exact URL you use for accessing the marketplace? 
Please check if the URL base matches with configuration of BASE_URL_HTTPS.

**Comment by victorhrsilva** [comment]
@GoebelL 
>>What is the exact URL you use for accessing the marketplace?
http://linux-7aon.pl.fsc.net:8080/oscm-portal/marketplace/index.jsf?mId=a8e4368a

Please check if the URL base matches with configuration of BASE_URL_HTTPS.
https://linux-7aon.pl.fsc.net:8081/oscm-portal

@Paulina has figured out that on my backup db from 17.3 I had the link with http protocol and port 8680.

Issue is fixed, thx.
