### ISSUE TITLE
Introduction to Bootstrap Theming with Sass.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#730]
**Summary**
Learn about Bootstrap Theming with Sass and create a simple custom Bootstrap Theme.

**Details**
Follow some tutorials on the web about Bootstrap Theming, and create as a result a custom Bootstrap Theme.
The mechanism of theming Bootstrap can be useful for the customers for defining the look-and-feel of the public landing page.

**Acceptance criteria**
An initial custom Bootstrap Theme for Bootstrap (for example specific style for a  Bootstrap navigation bar,for a  footer as well as specific style for buttons) is introduced.
- [ ] An implementation pattern is provided for common use in new marketplace components
- [ ] Custom Sass file is provided for usage in style sheets  
- [ ] Usage instructions are communicated to the team

**Additional context**
Add any other context or screenshots about the task.

**Comment by GoebelL** [comment]
Packaging is open.
