### ISSUE TITLE
Design new service rating stars

### ISSUE THREAD

**Issue by mchudy-fujitsu** [servicecatalog/oscm#731]
**Summary**
Create a bootstrap version of <mp:ratingStars> tag

**Details**
Create a new tag <mp:ratingStarsBootstrap> and redesign star rating system using Font Awesome star icons, which will allow better control over styling.

**Acceptance criteria**
- [x] Facelet mp:ratingStars is implemented with bootsfaces and working properly
- [x] Rating starts are working like before.
- [ ] ~~Rating stars are made with font awesome icons.~~

**Additional context**
Font Awesome icons:
https://fontawesome.com/icons/star?style=solid
https://fontawesome.com/icons/star?style=regular
https://fontawesome.com/icons/star-half-alt?style=solid

**Comment by GoebelL** [comment]
Check the licences for these icons.

**Comment by mchudy-fujitsu** [comment]
@GoebelL 
Font awesome license: https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt CC4.0/SIL OFL 1.1/MIT 

They require attribution which is already included in files provided by font awesome.

**Comment by mchudy-fujitsu** [comment]
The idea of font awesome icons has been dropped. It would require additional changes to render new stars.
