### ISSUE TITLE
Implement Subcategories Menu.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#734]
**Summary**
Implement Subcategories Tree in the Categories Menu.

**Details**
First, define sub-categories. **Point to clarify:** Check how the definition of sub-categories is currently done in Admin Portal? (Could not find such a definition).
Then, implement layout and functionality of Subcategories in the Categories Menu for the Services List page.

**Acceptance criteria**
- [ ] Functionality and layout
- [ ] UI test for opening subcategories.

**Additional context**
Add any other context or screenshots about the task.

**Comment by GoebelL** [comment]
Find out and share layout sketch how sub categories are displayed.

**Comment by Piotr-K8i** [comment]
Currently, sub categories don't exist in oscm. Lorenz very slightly remembers that once there was a feature request for a subcategory. But obviously it was never implemented.
