### ISSUE TITLE
Implement Tag Cloud in aside menu.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#736]
**Summary**
Implement Tag Cloud in Public MP page and in Services List page.

**Details**
Show Tag Cloud in public landing page (in both the playground and the services list page).

**Acceptance criteria**
- [ ] Tags are shown and styled with bigger font-size based on their frequency.
- [ ] UI Test for tag cloud.

**Additional context**
Services Tags.

**Comment by GoebelL** [comment]
Duplicate with #732.
