### ISSUE TITLE
Search bar stays with searched phrase 

### ISSUE THREAD

**Issue by kolodziejczykm** [servicecatalog/oscm#74]
[Build] 
17.6 2018/01/18

[Steps to reproduce] 

1. Login CT-MG as a End User -> go to marketplace (it happens on every role)
2. Go to "My Subscriptions"
3. Click search subscription    
4. Search for subscription
5. Go back to the standard subscription view by refreshing/clicking subscription card again, home, account, logo etc.

[Expected result] 

Refreshing a page or clicking on another chart in browser should erase the search and show your current subscriptions

[Observed result]

Refreshing, clicking on other charts, does not erase the search. The only way to erase the search is to click in the search bar, delete the used phrase, leave search bar empty and click search

**Comment by ghost** [comment]
@kolodziejczykm This behavior has always been like this. It also came as a surprise to me when I first used it. But I was told it was supposed to be like this.
But since you are a new user, maybe we should change the behavior ....

**Comment by kolodziejczykm** [comment]
@SylviaDehn If there's a reason that it should be this way I believe you can get used to it. But if we're looking at users better experience I think it's just not intuitive for search box to work like this.

**Comment by grubskim** [comment]
Closing, as this is working according to the specification.
