### ISSUE TITLE
Create Organization does not assign TP role.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#744]
**Version Info**
18.1 master build.

**Describe the bug**
The first time an Organization is Created with roles "Supplier" and "Technology Provider", the role "Technology Provider" is not assigned. After the second time it works.

**How to Reproduce**
1. Login as administrator to classic portal and create a new organization with name "supplier".
2. Fill in the fields and assign the roles "Supplier" and "Technology Provider".
3. Then log-in in classic portal as "supplier". 
4. Create a second organization. Everything works as expected the second time.

**Observed behavior**
The organization does not have the Technology Provider role, furthermore the user does not see the menu for Technical Services. 

**Expected behavior**
The organization has both roles "Supplier" and "Technology Provider" and sees the menu for Technical Services.

**Screenshots**
If applicable, screenshots to help explain your problem.

**Additional context**
Similar case if the administrator assigns the role "Technology Provider" afterwards for "supplier". The Technical Services menu is still not accessible for the supplier.

**Comment by Piotr-K8i** [comment]
@GoebelL @farmakiG  This problem existed even before there was a change in the organization's creation. Occurs when we quickly select two options, after choosing the first one there is an onclick event which loads content on the page, removing the next selection. I think the best solution will be on the front-end side, e.g. changing the way the page is rendered or changing the mouse cursor to the waiting status.
