### ISSUE TITLE
Adapt Documentation about Stage Customization.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#745]
**Summary**
Adapt the documentation in oscm-help about the customization for responsive stages. Refer to issue: #549 

**Details**
In the customize stage page for a marketplace, you can define as follows the stage:
Please note that the image must be of size 1600 x 500 pixels (or must have the same aspect ratio), because this is a commonly used format for banners of websites or other landing pages. 

<div class="responsive-container">
<iframe FRAMEBORDER="0"  width="100%" height="290px" marginwidth="0" marginheight="0" SRC="image_path" SCROLLING="no"></iframe>
</div>

In the same way you can define responsive embeds for the public MP page.
<div class="responsive-container">
<embed FRAMEBORDER="0"  width="100%" height="290px" SRC="embed_path" SCROLLING="no"></embed>
</div>

**Acceptance criteria**
The oscm-help guide is updated.

**Additional context**
N/A.

**Comment by SuessI** [comment]
Documentation updated and distributed for review. Relevant section is:

Customizing the marketplace stage
...
Enter the HTML code referencing the desired stage image. For optimum display, you can specify different stage images for desktop and mobile devices. The stage image for desktop devices is used when the display is wider than 768 pixels. For smaller widths, the stage image for mobile devices is used.

As common with website banners, the image for desktop devices must have a size of 1600 x 500 pixels or multiples thereof with the same aspect ratio. The image for mobile devices must have a size of 768 x 940 pixels or multiples thereof with the same aspect ratio. The recommended width of the stage is 100%. The recommended height is between 200 and 300 pixels for the desktop stage, and between 680 and 720 pixels for the mobile stage.

You can enter the HTML code directly, or you can use an inline frame for embedding the stage in the HTML code of the marketplace home page.

Example:

<iframe FRAMEBORDER="0" width="100%" height="290px" marginwidth="0" marginheight="0" SRC="mystage.htm" SCROLLING="no"></iframe>

...

**Comment by SuessI** [comment]
Documentation reviewed and completed.
Closing
