### ISSUE TITLE
Playgrounds styling update

### ISSUE THREAD

**Issue by mchudy-fujitsu** [servicecatalog/oscm#756]
**Summary**
Update styling on playground sites on received feedback.

**Details**
N/A

**Acceptance criteria**
- [ ] Make the category menu button bigger and align text to the left on large screens and to center on small screens.
- [ ] Make hand icon appear on hover at help link in header navbar.
- [ ] Add tag list to service block

**Additional context**
N/A

**Comment by GoebelL** [comment]
Point 1: Make a horizontal list of categories that re-arranges into a vertical list when decreasing window width. 
![image](https://user-images.githubusercontent.com/14805690/78347308-9304bd80-75a0-11ea-8f5f-64381053ecde.png)

**Comment by GoebelL** [comment]
@mchudy-fujitsu As the PR is already in review I consider my above comment is out of scope here. 
I created a separate feature request in #758.
