### ISSUE TITLE
Responsive categories bar

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#758]
**Summary**
If categories are defined they shall appear on the landing page and on the services list views. The displaying in the new marketplace UI requires a horizontal, responsive and space optimizing layout of categories.

**Details**
 The categories shall be displayed as horizontal list that re-arranges into a vertical menu when decreasing the window width. 

**Acceptance criteria**
- [ ] List is responsive
- [ ] Ecological horizontal layout
- [ ] Five categories a max. 12 characters display well
- [ ] List breaks into a vertical menu arrangement under the button
 
**Additional context**
![image](https://user-images.githubusercontent.com/14805690/78348664-b9c3f380-75a2-11ea-99ad-bd6f3efcaa27.png)

**Comment by mchudy-fujitsu** [comment]
Related #479
