### ISSUE TITLE
Service not shown as unavailable; browser hangs

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#76]
[Build] 17.6 2018/17/02

[Steps to reproduce]
Using Firefox
1. import technical service
2. click on imported service to see if it is available  
    (which it is not; it points to a glassfish-domain on another computer and it is not up)

[Expected result]
Service is shown as unavailable

[Observed result]
Firefox busy cursor is shown and it never returns

[Details]
If the glassfish is up, but the service is not available, then this works ok.

**Comment by ghost** [comment]
Workaround is to close browser window and open it again.

**Comment by badziakp** [comment]
Hi,

can you attach the technical service you imported because o n the newest version of oscm I can't reproduce this issue?

**Comment by GoebelL** [comment]
Closing this issue since it hasn't been reproduced anymore.
