### ISSUE TITLE
Unable to assign subscription

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#760]
Version Info
18.1 master 

Describe the bug
After entering the marketplace portal and trying to assign a subscription we receive a message about its positive assignment, but after entering the MailDev we see that the transaction has been rollback

How to Reproduce
1. Go to the page oscm-portal/marketplace/index.jsf
2. Try assign any subscription
3. Check e-mail

Observed behavior
The assigned subscription still has the status "pending"

Expected behavior
The subscription will be added to the user
The subscriptions window will display a list of assigned subscriptions

Screenshots
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/f7788dda-7019-43b6-91b9-4f5f286cd3ca)

![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/8b20c2dd-cacc-4aa1-a479-02b55d24cd40)

Additional context
[Notification of Catalog Manager about the provisioning process for subscription 'Lorem ipsum' failed.](https://app.zenhub.com/files/108258123/a1b89223-3e72-4022-a71d-ee4ee3697e1d/download)

**Comment by GoebelL** [comment]
What is service based on? Can you access the application underneath? Is it up and running? Please check the docker logs, e.g.
1. Run following command and provoke the error
```docker logs -f oscm-app``` 
2. Check last entries in system.log file
``` docker exec oscm-core cat /logs/system.log```

**Comment by Piotr-K8i** [comment]
For the supplier that was created during Pull_and_start on Jenkins, the assignment request works fine. We get an e-mail about its assignment, but we still can't see the subscription in the "My subcriptions" tab. However, for a new supplier, which we will create from the administrator account with the "Supplier" and "Technology provider" roles, after creating the subscription the situation is as described above. We receive errors in the console:
[Subscription_oscm_core_console](https://app.zenhub.com/files/108258123/b95b8d52-3c28-46c5-8283-6512fd59de4b/download)
[Subscription_system_log](https://app.zenhub.com/files/108258123/39a894c4-48d4-4a10-b816-13c16f58ae62/download)

**Comment by GoebelL** [comment]
Sorry to repeat my question: Which service is used here?

**Expected**
1. As long as subscription is in pending state the user assignment is not available.
2. If the service is public and setup correctly, it is subscribe-able by any customer user. 
3. The subscription state should switch to ready state after some time.

@KabacinskiPiotr 
The attached error logs indicate that the service is not setup correctly. The technical service is created with another organization that doesn't own the service. 
```
40125: The current organization doesn't own the technical service of the subscription
```
Note that the owning organization can be configured in the APP. For OpenStack, AWS, VMware or Azure services this can be done as platform administration in the APP UI. For the Sample Controller and for the Shell Integration this has to be done with respective docker-compose commands via command line. See the [Operator's Guide](https://github.com/servicecatalog/documentation/blob/ESCM/Manuals/Operation.pdf) "Updating Controller Configuration Settings" on page 21 how to do this.

**Comment by GoebelL** [comment]
@KabacinskiPiotr 
Please align the responsible organization of the used APP controller with technology provider organization that owns the respective technical service. 
This issue should be solved with the instructions I have given here. If you are still facing these issues though, then let me know and provide the details about the service. Otherwise please close this.
