### ISSUE TITLE
Layout of user search field

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#763]
**Version Info**
18.1 master

**Describe the bug**
User search field is not fully visible

**How to Reproduce**
1. Go to marketplace portal
2. Click on Account
3. Click on Users & Units

**Observed behavior**
User search field is not fully visible

**Expected behavior**
The user search field should look like the Internal mode

**Screenshots**
OIDC mode:
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/d154d81d-895a-4aed-96de-b69f0e67b82a)

Internal mode
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/8a525b31-69a8-443c-bad1-5a11ff661854)

**Additional context**
N/A

**Comment by GoebelL** [comment]
@KabacinskiPiotr 
This works as designed. In OIDC mode the users are registered in the OIDC Provider only. There is no "add users" function. Instead users are automatically created in OSCM by a respective synchronization function. See user documentation for details.
  
I confirm there is a layout flaw on the user search field. Please adapt this bug title and description as "layout of user search field" issue.
