### ISSUE TITLE
Manage categories text input misplaced styling

### ISSUE THREAD

**Issue by mchudy-fujitsu** [servicecatalog/oscm#766]
**Version Info**
18.1 master build

**Describe the bug**
Styling on manage categories entries has misplaced text field inputs.

**How to Reproduce**
1. Go to oscm-portal/shop/manageCategories.jsf
2. Select the marketplace and press the add button.
3. See the misplaced inputs.

**Observed behavior**
Text inputs are not properly aligned.

**Expected behavior**
Text inputs are in proper alignment.

**Screenshots**
![image](https://user-images.githubusercontent.com/58510012/78545211-b4adb100-77fb-11ea-9630-a2338f95ae75.png)

**Additional context**
N/A

**Comment by Piotr-K8i** [comment]
This problem occurs because of a hidden error message
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/9683a5bd-25d9-42af-86fa-56e3c6ae2a48)
