### ISSUE TITLE
Replace Bootstrap footer in MP pages.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#768]
**Summary**
Replace the footer in MP UI pages with the already implemented Bootstrap footer.

**Details**
A footer for Bootstrap has already been implemented in the mainBootstrap template. Split it to a new tag "bootstrapFooter" and reference it in both "main" and "mainBootstrap" template. 
(As a next step, to be defined in a next task, replace step by step the main template with the mainBootstrap template in UI pages.)

**Acceptance criteria**
- [ ] The footer is replaced in MP UI pages and is responsive.
- [ ] Small UI Test for opening one page and checking if footer of style bootstrap_footer is present.

**Additional context**
N/A.

**Comment by Piotr-K8i** [comment]
Related with https://app.zenhub.com/workspaces/oscm-59f31a4996b6c551bc556610/issues/servicecatalog/oscm/765
