### ISSUE TITLE
Missing migration script for oscm-app

### ISSUE THREAD

**Issue by victorhrsilva** [servicecatalog/oscm#77]
[Build] 17.6 2018/01/18 

[Steps to reproduce]
- Restore an app database from 17.4 to 17.6
- Start to use app controllers 

[Expected result]
- During the deployment the database from 17.4 be migrated to 17.6

[Observed result]
- User is unable to login to oscm-app console and to controllers

[Details]
- Oscm-app
![image](https://user-images.githubusercontent.com/24247646/35335504-16064444-0116-11e8-805b-718333f9cf0e.png)

- Controller
![image](https://user-images.githubusercontent.com/24247646/35335530-25b9fd9a-0116-11e8-9f8e-22228a6d0721.png)

**Comment by grubskim** [comment]
Please check if this not not the http problem (app is only accessible with https now).

**Comment by victorhrsilva** [comment]
I have checked with HTTPS and port 8881, the error message does not appear anymore. However I am still not able to access it.

**Comment by GoebelL** [comment]
The older glassfish based app version is no longer maintained. Migration is not needed.
