### ISSUE TITLE
Redirect to Playground Page from GotoMarketplace.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#770]
**Summary**
The user is redirected to the playground page when clicking on the "Go to markeptlace" button in admin portal.

**Details**
For marketplaces starting with id of "pg_" user is redirected to playground pages, for other ids everything works as before.

**Acceptance criteria**
- [ ] Manual testing of the Go to marketplace redirection.
- [ ] Small UI test for Gotomarketplace button.

**Additional context**
N/A.

**Comment by GoebelL** [comment]
@mchudy-fujitsu, all
I know we planned this task for this sprint. However, when thinking it over, this PR is a bit too early.
The marketplace UI isn't ready yet. I suggest we tweak it in a way, that existing marketplace landing pages stay targets for default marketplaces and certain playground marketplace can be created when desired. For example implement the goto marketplace logic with a redirect to playground landing page only for marketplace IDs starting with "pg".  
How about this?

**Comment by mchudy-fujitsu** [comment]
I think it is a good idea, I have updated the issue description.
