### ISSUE TITLE
Removing hard-coded values in mp.css file

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#782]
**Summary**
Because of rebuilding pages in the marketplace, the font style values have been encoded in . After full migration to bootstrap, the changes should be withdrawn

**Details**
Basically it is not a good approach to overwrite styles with !important. Since we would like to use the Bootstrap look-and-feel and be able to customize it, these !important flags will always overwrite the custom styles we have defined.
PR in which changes was made: [PR](https://github.com/servicecatalog/oscm/pull/778/files)
File in which changes was made: oscm-portal/WebContent/marketplace/css/mp.css

**Acceptance criteria**
The appearance of the page should be the same

**Additional context**
N/A

**Comment by GoebelL** [comment]
@farmakiG 
As discussed this issue should be addressed with SASS and custom theming. Please avoid extra work here.

**Comment by farmakiG** [comment]
Solved with #993.

**Comment by farmakiG** [comment]
Fixed with #993.
