### ISSUE TITLE
Errors when manage categories

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#787]
**Version Info**
master 18.1

**Describe the bug**
When adding/removing/editing categories, errors are displayed that are not necessarily related to the action being performed. The errors observed are:

Without console errors:
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/7fff9ad6-fdf8-4d37-ad20-911a419ba702)

With console errors:
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/68a2d42e-e336-4d6b-985e-4890b3714a72)
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/4eee8f12-79c9-4e43-b27c-577ad78c29ca)

**How to Reproduce**
1. Go to oscm-portal/shop/manageCategories.jsf
2. ADD/REMOVE/EDIT CATEGORY

**Observed behavior**
As above

**Expected behavior**
- [ ] During manage categories, errors should only appear for a specific reason
- [ ] Add/remove and edit commands should do the same
- [ ] Test test04addCategory() at PortalMarketplaceWT should pass everytime

**Additional context**
[manageCategories](https://app.zenhub.com/files/108258123/fb44231b-e744-491f-a3ca-1d92f0776b69/download)

**Comment by GoebelL** [comment]
Not sure how "with console errors" relates to these messages shown in the oscm portal.

Anyway, "Operation Failed" indicates an unexpected error here. There should be a corresponding error entry in /logs/System.log. Please check. 
My guess is that the edited transfer object (PO or VO object) is not refreshed after persisting the modification (-> ensure that the value of the version field in same object is increased after saving - I suspect it's not). Thus an old version is edited which leads to this "concurrent modification" error handling.

**Comment by Piotr-K8i** [comment]
I wrote with errors in the console because they were similar and probably caused by the same thing. In the attachment I added logs from the system.log file after the "Operation Fail" error

[system.log](https://app.zenhub.com/files/108258123/bb094197-77e2-4557-9b1a-5d89ef4b41ee/download)

**Comment by GoebelL** [comment]
Yes, it's something like I assumed. The version in one VOCategory object contained in the CategoryRow model is not set (version 0) and an update is attempted. The insert fails on the persistence side with the SQL exception shown in the attached system.log:

Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into Category 
(categoryId, version, marketplaceKey, TKEY) _values ('Category 1', **0**, 11000, 10001)_ 
was aborted.  

This unexpected exception is not handled and therefore results in the "Operation failed" screen.

**Comment by GoebelL** [comment]
I presume a key is set (>0) but the version not (=0) in given case. This would be inconsistent. Try to find by debugging breakpoint around
org.oscm.ui.beans.CategoryBean.saveCategories(CategoryBean.java:108) and
org.oscm.marketplace.bean.CategorizationServiceBean.saveCategories

**Comment by GoebelL** [comment]
@cworf91 please comment the status.

**Comment by cworf91** [comment]
@GoebelL it´s not possible to reproduce this bug so far for me. I have to investigate the logfile and try to do some progress with this information.
