### ISSUE TITLE
[Subscription UI] Redesign payment subscription page

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#801]
**Summary**
Redesign second step Page of Subscription Creation.

**Details**
The second page which appears when creating a new Subscription (where the user clicks on Confirm dialog) should become responsive.

**Acceptance criteria**
- [ ] Functionality remains as before
- [ ] UI test (previous UI test for the first step of Subscription creation can be extended by one further step).

**Additional context**
N/A

**Comment by GoebelL** [comment]
The term "second page" is ambiguous. The page sequence depends on the subcription pricemodel, respectively whether additional payment steps are required or not.
