### ISSUE TITLE
Reduce size of Controls for large resolution screens.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#802]
**Summary**
For large resolution screens the controls appear too big. Therefore, depending on screen size, use smaller controls.

**Details**
A Bootstrap class for buttons (btn-sm has been already tested and looks better than normal buttons in large screens). Find similar classes for the Bootstrap cards and other used controls. 
Probably  a media query with the use of Sass has to be implemented for large screens.

**Acceptance criteria**
- [ ] Manual testing.
- [ ] Resulting UI Screenshots.

**Additional context**
N/A.

**Comment by GoebelL** [comment]
Please update the state.

**Comment by farmakiG** [comment]
This task has been solved with the introduction of btn-sm classe for buttons and media queries for bigDisplay and smallDIsplay..
