### ISSUE TITLE
Integrate bootstrap and SASS compilation in CI

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#803]
**Summary**
Include packaging of the Bootstrap sources and compiled files in CI build.

**Details**
There are three options of packaging Bootstrap. 
1. Node.js and in particular the npm package manager.
2. Packager included in Ruby.
3. Other options such as Webpack.
Probably the preferred option is Node.js with npm because it provides extra options via the npm package manager.

After selecting one of the above options, integrate the packaging of Bootstrap in our oscm-portal project under a "node_modules" separate folder.

**Acceptance criteria**
Bootstrap version 4.3.1 is packaged properly. Sass files refer to the correct directories of Bootstrap located under "node_modules"

**Additional context**
N/A.

**Comment by GoebelL** [comment]
@farmakiG 
I am not clear about this task. In my understanding we are talking of development tools for creating and customizing stylesheets and not of mandatory runtime for OSCM. So there is nothing to be packaged in the oscm-portal except for the resulting CSS artifacts.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-dockerbuild/pull/258

**Comment by GoebelL** [comment]
The bootstrap sources are still found in the OSCM repo [here](https://github.com/servicecatalog/oscm/tree/master/oscm-portal/WebContent/bootstrap). Please remove them.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-jenkinsscripts/pull/5
https://github.com/servicecatalog/oscm/pull/1027
