### ISSUE TITLE
Fix "Search Services" button in playground page.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#805]
**Summary**
The "Search Services" button in the header of the playground page is not working.

**Details**
The Search button should display Services only containing the Search term.

**Acceptance criteria**
- [ ] Implementation independently of the old header.
- [ ] Manual tests. 
- [ ] Small UI test with two cases.

**Additional context**
N/A.

**Comment by GoebelL** [comment]
Please also check the subscription search.

**Comment by GoebelL** [comment]
Pulled from latest master and search is working fine. Issues have been resolved already.
