### ISSUE TITLE
Replace all links in Playground Header.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#808]
**Summary**
The links in the Playground Header go to all the respective playground pages.

**Details**
- "Home" Link goes to playground page.
- Browse to playground services page.
- Account goes to playground account page.
- My Subscription to playground subscriptions.

**Acceptance criteria**
- [ ] Old header is not affected. All links should be changed in the headerBootstrap template.
- [ ] Manual tests.
- [ ] Separate UI test just for new header.

**Additional context**
N/A.

**Comment by mchudy-fujitsu** [comment]
#791 related
