### ISSUE TITLE
DB Errors during intial installation

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/oscm#817]
**Version Info**
latest (27.04.2020)

**Describe the bug**
Duplicate error at VMware connector

**How to Reproduce**
Clean installation of ESCM

docker run --name deployer2 --rm -v /docker:/target -v /var/run/docker.sock:/var/run/docker.sock -e INITDB=true  -e STARTUP=true -e SAMPLE_DATA=true  servicecatalog/oscm-deployer

**Observed behavior**
oscm-initdb-controller-vmware       | You are now connected to database "bssapp" as user "postgres".
oscm-initdb-controller-vmware       | psql:/opt/sqlscripts/vmware/sample.sql:3: ERROR:  duplicate key value violates unique constraint "configsetting_pk"
oscm-initdb-controller-vmware       | DETAIL:  Key (settingkey, controllerid)=(BSS_USER_ID, ess.vmware) already exists.
oscm-initdb-controller-vmware       | psql:/opt/sqlscripts/vmware/sample.sql:4: ERROR:  duplicate key value violates unique constraint "configsetting_pk"
oscm-initdb-controller-vmware       | DETAIL:  Key (settingkey, controllerid)=(BSS_USER_PWD, ess.vmware) already exists.
oscm-initdb-controller-vmware       | psql:/opt/sqlscripts/vmware/sample.sql:5: ERROR:  duplicate key value violates unique constraint "configsetting_pk"
oscm-initdb-controller-vmware       | DETAIL:  Key (settingkey, controllerid)=(BSS_USER_KEY, ess.vmware) already exists.
oscm-initdb-controller-vmware       | psql:/opt/sqlscripts/vmware/sample.sql:6: ERROR:  duplicate key value violates unique constraint "configsetting_pk"

**Expected behavior**
A clear and concise description of what is expected to happen.

**Screenshots**
If applicable, screenshots to help explain your problem.

**Additional context**
Any other context about the problem here.

**Comment by GoebelL** [comment]
@uhu133 
I confirm the are error message in the installer logs. This happens because the installer attempts to create the already existing initial content of the vmware database. Sure the logs aren't nice, but these errors don't have further impact and can be safely ignored.
 Currently there is only one version of vmware db model schema. In order to solve this message properly, we need to implement schema versioning and apply database upgrade handler properly.

**Comment by cworf91** [comment]
Issue moved to [servicecatalog/oscm-dockerbuild #230](https://github.com/servicecatalog/oscm-dockerbuild/issues/230)
