### ISSUE TITLE
Status of the OpenStack subscription

### ISSUE THREAD

**Issue by kolodziejczykm** [servicecatalog/oscm#82]
[Build]
17.6 2018/01/18

[Steps to reproduce]
1.	Subscribe to 3 OpenStack based services 
2.	Go to “My Account” -> “Subscriptions” 
Login to OpenStack dashboard and delete instances manually over there 

[Expected result]
In the Account -> “Subscriptions” view -> our subscriptions from Status green “ready” should change to another because they are no longer available to administrate. 
You can also add users to this subscription. 

[Observed result]
Status of the subscription stays green as “ready” 

[Details]
![deleted from dashboard still on ctmg](https://user-images.githubusercontent.com/34572039/35797465-195c183c-0a60-11e8-99cc-d025a8cf74a6.JPG)

![dashboard instances](https://user-images.githubusercontent.com/34572039/35797564-5f137afa-0a60-11e8-8f5e-e9f2d7b6d961.JPG)

**Comment by GoebelL** [comment]
OSCM provides interfaces intended to ease management of cloud subscription instances. OSCM does not provide for re-synchronizing any instance status or modifications which are triggered from outside. It is expected that the subscription instances are deleted through OSCM by terminating the subscription. In case the instance was deleted from horizon dashboard or any other cloud interface bypassing OSCM, the administrator is supposed to also terminate the subscription in OSCM.
