### ISSUE TITLE
Login dialog with Bootstrap look-and-feel.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#828]
**Summary**
Display the Login dialog to Marketplace with Bootstrap Look-and-feel.

**Details**
The login dialog is responsive and shown with a Bootstrap-look-and-feel.

**Acceptance criteria**
- [ ] Manual tests
- [ ] Resulting UI Screenshots
- [ ] Test for Custom Color. 

**Additional context**
N/A.

**Comment by mchudy-fujitsu** [comment]
![1](https://user-images.githubusercontent.com/58510012/82420088-8b7d7300-9a7f-11ea-80fa-8e2edda3d3b3.png)
![2](https://user-images.githubusercontent.com/58510012/82420090-8c160980-9a7f-11ea-9a93-f82ea7b61c13.png)
![3](https://user-images.githubusercontent.com/58510012/82420092-8caea000-9a7f-11ea-82fa-afe62fe826d8.png)
![4](https://user-images.githubusercontent.com/58510012/82420093-8caea000-9a7f-11ea-9c06-47a36af51f2f.png)
![5](https://user-images.githubusercontent.com/58510012/82420096-8d473680-9a7f-11ea-9820-514899e8f7c1.png)
![6](https://user-images.githubusercontent.com/58510012/82420098-8d473680-9a7f-11ea-990d-aff82eb1a814.png)
![7](https://user-images.githubusercontent.com/58510012/82420100-8ddfcd00-9a7f-11ea-86db-96606f532f86.png)
![8](https://user-images.githubusercontent.com/58510012/82420101-8ddfcd00-9a7f-11ea-8ea6-401a951eb9a7.png)
