### ISSUE TITLE
[Service Details UI]Bootstrap look-and-feel of modal dialogs.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#830]
**Summary**
The modal dialogs appearing in the Service Details page, (such as when clicking on Select button) have a Bootstrap look-and-feel.

**Details**
All modal dialogs have Bootstrap look-and-feel.

**Acceptance criteria**
- [ ] Manual Tests
- [ ] Resulting UI Screenshots.

**Additional context**
N/A.

**Comment by Piotr-K8i** [comment]
@farmakiG I think we can close this task. Do you agree?

**Comment by farmakiG** [comment]
Yes I agree @KabacinskiPiotr
