### ISSUE TITLE
[Service Details UI]Fine-tuning of Service Details page.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#831]
**Summary**
Some fine tuning of the layout of the Service Details page, such as tooltips and Scrollbar.

**Details**
The Service Details page is not really responsive. A horizontal scrollbar appears, and the tooltips near to Select button are misplaced. These small issues must be corrected.

**Acceptance criteria**
- [ ] Manual Tests while resizing Browser
- [ ] Resulting UI Screenshots.

**Additional context**
N/A.

**Comment by GoebelL** [comment]
To be solved with #816

**Comment by GoebelL** [comment]
@farmakiG 
Please confirm the solution with #816. If it's is done then close this issue.

**Comment by farmakiG** [comment]
Closed with #816.
