### ISSUE TITLE
UI tests for VMware fails

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm#841]
**Version Info**
18.1 

**Describe the bug**
A few UI tests for WMware are failing
AppVCenterControllerWT.test01setSettingsAPIvSphere:66 ? NoSuchElement no such ...
AppVCenterControllerWT.test02importServiceTemplate:79 ? NoSuchElement no such ...
AppVCenterControllerWT.test03setSettingsIntoController:92 ? NoSuchElement no s...

**How to Reproduce**
1. Go to https://yourhost/oscm-app-vmware/
2. Click on vCenter -> save
3. See error

**Additional context**
Refactoring the VMware deployment causes this problem. By default, sample data was in the database before refactoring. Sampledata are now only in the database if they were installed with sampledata = true. To fix the UI test, the vcenter must be added to the test.

See: https://github.com/servicecatalog/oscm-app/blob/master/oscm-app-vmware/resources/csv/vcenter.csv

**Comment by GoebelL** [comment]
The cause of these failures are that the VCenter configuration is missing in the database in case the installation was done without sample data. This needs to be fixed in the installer.

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-app/pull/79

**Comment by cworf91** [comment]
Bug is fiexed. Tests are running again.
