### ISSUE TITLE
Make Manage Reviews modals responsive.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#895]
**Summary**
The Manage Review modal dialogs (in case there are more than one) are responsive.

**Details**
The dialog which appears upon clicking of button "Write Review" or "Manage review" should be responsive and have Bootstrap look-and-feel. The entered text and service rating stars are updated on the Services page. The  resulting reviews section is also responsive.

**Acceptance criteria**
- [ ]  Manual tests
- [ ]  Resulting UI Screenshots.

**Additional context**
N/A.

**Comment by GoebelL** [comment]
Should be fine already. Todo: Check with more comments.

**Comment by Piotr-K8i** [comment]
[Done with this PR](https://app.zenhub.com/workspaces/oscm-59f31a4996b6c551bc556610/issues/servicecatalog/oscm/943)
