### ISSUE TITLE
Replace tooltips with Bootstrap tooltips.

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#897]
**Summary**
Replace tooltips by Bootstrap tooltips.

**Details**
The tooltips can be replaced step-by-step by Bootstrap tooltips.  The tooltip should be well-positioned next to the input element where the user clicks.
An example is the page: playground/subscriptions/creation/add.jsf.
In this page the horizontal scrollbar must be removed additionally.

**Acceptance criteria**
- [ ] Manual tests
- [ ] Resulting UI Screenshots.

**Additional context**
N/A.

**Comment by GoebelL** [comment]
To be implemented with #816
