### ISSUE TITLE
Split Bootstrap-related css from mp.css

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#898]
**Summary**
All bootstrap-related UI components should be in darkCustom.scss and not in mp.css. Furthermore, the styles in mp.scss should **NOT Override** Bootstrap-related styles, styles of MP and styles of Bootstrap UI components should be loosely coupled.

**Details**
The concept here is that the Bootstrap-related css styles are split from mp.css and located in "darkCustom.css". 
This makes the maintainance of the CSS files easier.
The same version of this file but importing different sass variables is the file "lightCustom.css".
We are using the sass pre-processor so we should add all styles in either darkCustom.scss or lightCustom.scss.
Please note that in order not to lose styles, we have to integrate the compilation of the sass files into css in our build process.

**Acceptance criteria**
Resulting css files: darkCustom.css and mp.css

**Additional context**
N/A.

**Comment by GoebelL** [comment]
Additional: Update scss files (e.g. mp.scss is outdated).

**Comment by GoebelL** [comment]
@farmakiG Please update this task.

**Comment by farmakiG** [comment]
Things to be done:

- Maintain breadcrumbs and aside menu css styling in one of the files and not split in two files (preferably customTheme.css).
- Move theme color variables to one _variables.scss file for easier maintainance (now we have theme colors in two files: _myvariables.scss and _variables.scss)
- Replace hard-coded colors with respective values in _colors.scss of mp.scss.
- Navigation menu and footer located in one of the files.
- Same with media breakpoints.

**Comment by farmakiG** [comment]
Refactoring open.
