### ISSUE TITLE
Check the impact of asynchronous subscription left in PENDING state after being aborted

### ISSUE THREAD

**Issue by kowalczyka** [servicecatalog/oscm#91]
With the fix which we delivered in https://github.com/servicecatalog/oscm/commit/f5bdefaab38f859442e2577b62b30b3a708a3d08, functionality related to subscription states changed:

- after aborting asynchronous subscription during creation (subscription in PENDING state) subscription stays in PENDING state
- before the mentioned fix, subscription was going into INVALID state

We noticed that this change can have some impact on subscription related actions as state validator now  allow some actions which previously were forbidden:

- https://github.com/servicecatalog/oscm/blob/master/oscm-subscriptionmgmt/javasrc/org/oscm/subscriptionservice/bean/ValidateSubscriptionStateBean.java#L87

- https://github.com/servicecatalog/oscm/blob/master/oscm-subscriptionmgmt/javasrc/org/oscm/subscriptionservice/bean/ValidateSubscriptionStateBean.java#L76

Therefore the imapact of this change must be investigated and proper adaptation must be done if needed.

**Comment by GoebelL** [comment]
Is this still valid?

**Comment by GoebelL** [comment]
No issues have been reported in this area up to now. Unless there are no concrete needs and plans to change the current abort behavior I don't think that this issue is further needed. Feel free to reopen if you consider any concrete action here.
