### ISSUE TITLE
Bugs in forms in mobile view

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#912]
**Version Info**
18.1

**Describe the bug**
Not fully responsive mobile view, missing tooltips at mobile view

**How to Reproduce**
1. Go to playground/index.jsf
2. Click on 'Show Details'
3. Click on 'Get it now'
4. Switch to mobile view
5. See error

1. Go to playground/account/subscriptionDetails.jsf
2. Switch to mobile view
3. See error

**Observed behavior**
Missing tooltips, not fully responsive form 

**Expected behavior**
The mobile view should have all the features of the deskop page, for the form in the mobile view the label should be displayed first and the field to be filled below

**Screenshots**
![Desktop_wiew.PNG](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/719cf303-bb6d-4b7f-a94d-69c4c118af6b)
![Mobile_wiew.PNG](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/ed6103b1-4961-472c-b319-5d496efed31d)
![Desktop_view.PNG](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/1b56b3e0-fe04-48d2-840e-23922dc27120)
![Mobile_view.PNG](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/000ce361-c4f3-46b5-b217-66b02ade5ae6)

**Additional context**
N/A

**Comment by GoebelL** [comment]
Hi @KabacinskiPiotr 
It seems that login dialog has some issue with the change of PR#919. 
![image](https://user-images.githubusercontent.com/14805690/84146912-bba3aa80-aa5c-11ea-8179-c646003ddbfb.png)
Please check.
