### ISSUE TITLE
Marketplace pages that are not responsive

### ISSUE THREAD

**Issue by Piotr-K8i** [servicecatalog/oscm#967]
Below is a list of pages that need to be made responsive so that the marketplace is fully operable by desktop and mobile devices:

/account
- [x]  assignUserInclude.xhtml
- [x]  errorMessages.xhtml
- [x]  importUser.xhtml
- [x]  ldap.Settings.xhtml
- [x]  organizationUdaDetails.xhtml
- [ ]  paramtable.xhtml
- [x]  subscriptionAministratePanel.xhtml
- [x]  subscriptionUdaDetails.xhtml
- [x]  units.xhtml

/subscriptions
- [x]  parameterConfigurations.xhtml
- [x]  status.xhtml

/templates
- [x]  errorcontent.xhtml

/terms
- [x]  imprint.xhtml
- [x]  privacypolicy.xhtml
- [x]  terms.xhtml

others:
- [x]  accessDanied.Page.xhtml
- [x]  changePassword.xhtml
- [x]  changePasswordInclude.xhtml
- [x]  completePwdRecovery.xhtml
- [x]  confirm.xhtml
- [x]  confirmStartPwdRecovery.xhtml
- [x]  enterpriseLandingpage.xhtml
- [x]  errorPage.xhtml
- [x]  index.jsp
- [x]  index.xhtml
- [x]  insufficientAuthorites.xhtml
- [x]  loginPage.xhtml
- [x]  logoutPage.xhtml
- [x]  publicLandingpage.xhtml
- [x]  recoverPassword.xhtml
- [x]  registration.xhtml
- [x]  registrationOk.xhtml
- [x]  serviceProvider.xhtml

/service
- [x]  deactivateService.xhtml
- [x]  reactivateService.xhtml

**Comment by GoebelL** [comment]
The impact is not clear. Let's group and prioritize this list according the user experience. 
e.g. 
1) Password recovery - Priority P2

**Comment by GoebelL** [comment]
Let's turn this into an epic and add issues from this list with respective priority.

**Comment by GoebelL** [comment]
Let's first merge the UI and test those pages.
