### ISSUE TITLE
Make redirect URLs configurable

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm#968]
@cworf91 commented on [Fri Jun 26 2020](https://github.com/servicecatalog/oscm-identity/issues/95)

**Summary**
The redirect in the identity service is hardcodes so far. This can lead to problems when using the proxy or different host systems. Therefore it should be possible to configure these URLs

**Details**
The identity service uses URLs for forwarding and redirecting. I.e:

bf.append(String.format("https://%s:9091/oscm-identity/login?", hostname));

This is hard coded in the source code. In order to make OSCM more flexible, this should be configurable via the cofiguration settings. Therefore, all places in the source code must be found and replaced by a configuration setting. 

**Acceptance criteria**
[ ] OIDC mode works as before.
[ ] Proxy runs with blocked ports in OIDC mode.

**Comment by GoebelL** [comment]
@cworf91 
Please check in the source code for similar cases.

**Comment by GoebelL** [comment]
To be fixed:
https://github.com/servicecatalog/oscm/blob/master/oscm-portal/javasrc/org/oscm/ui/filter/OidcLogoutFilter.java#L97
https://github.com/servicecatalog/oscm/blob/master/oscm-portal/javasrc/org/oscm/ui/filter/OidcFilter.java#L200

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-dockerbuild/pull/256
https://github.com/servicecatalog/oscm-interfaces/pull/52

**Comment by cworf91** [comment]
The update of container works. 
Please note, we add a config setting here, so update also your Database (See: Operatorsguide 3.1. Update OSCM and APP Config Settings)
