### ISSUE TITLE
Wrong access info in OpenStack Sample Service

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#98]
_From @uhu133 on June 8, 2018 7:50_

when creating an instance with the OSCM OpenStack Sample Service the access info at "My Subscriptions" shows the dns name of the server where OSCM is running and NOT the IP address or dns name of the OpenStack server which was created by subscription.
![capture](https://user-images.githubusercontent.com/32158057/41145714-4e9460ac-6b01-11e8-98ce-7789a0aecb7f.JPG)

_Copied from original issue: servicecatalog/development#917_

**Comment by GoebelL** [comment]
_From @uhu133 on June 8, 2018 7:51_

![capture2](https://user-images.githubusercontent.com/32158057/41145800-864afa9c-6b01-11e8-9e6a-6037ce822301.JPG)
The corresponding OpenStack instances.

**Comment by kowalczyka** [comment]
The SOC sample service was prepared for the specific integration of OSCM with the SOC (as a barclamp).

The access info parameter is filled with HOST_FQDN value which in this case is delivered from barclamp UI or automatically assigned by chef script (it is an openstack instance which hosts the docker containers) and is common for the future soc sample services.

**Comment by GoebelL** [comment]
@kowalczyka 
>The access info parameter is filled with HOST_FQDN value which in this case is delivered from barclamp UI

Oh really? Indeed, this would explain the effect, but on the other hand it doesn’t make much sense. An access information is a result from a provisioning service but not an input. This is supposed to contain the information the customer needs for accessing the instance, which has been provisioned with the subscription. In case of the OpenStack adapter the access info is composed from a pattern which is given as input but contains placeholders, which are substituted with the values returned from the heat stack result. 

HOST_FQDN may be delivered from barclamp UI or docker-compose environment, but that refers to the host where OSCM is running, not the instance that has been provisioned.

**Comment by GoebelL** [comment]
@uhu133 
Have you tried giving a different access pattern than the proposed default? For instance "Key pair name: {KP_Out}; IP: {IP_Out}". Not sure if these placeholders work well, but could be worth a try...

**Comment by kowalczyka** [comment]
HOST_FQDN placeholder  is now removed from the access info pattern - https://github.com/servicecatalog/oscm-dockerbuild/commit/428af39f2809c8dff6ef88ed4025824c3202cd3f
