### ISSUE TITLE
Integrate Azure Runbooks

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm#991]
**Summary**
OSCM shall provide for an integration for Azure Automation.

**Details**
1. Get Familiar with [Azure Automation](https://docs.microsoft.com/en-us/azure/automation/automation-intro) and concepts of [Runbook Execution](https://docs.microsoft.com/en-us/azure/automation/automation-runbook-execution).
2. Eloborate a first use case provisioning with with Azure Runbooks.
3. Collect in a list the required ressources and create first task issues 

**Acceptance criteria**
Tbd

**Additional context**
https://docs.microsoft.com/en-us/azure/automation/automation-intro

**Comment by GoebelL** [comment]
Hi @kowalczyka 
Please add a short description of the enhancement. Please write some sentence about the new PowerShell support, used and/or supported versions, known issues if any, how the user can handle authentication for Azure, the samples scripts and external references to Azure Automation scripting. This input is needed for the 19.1 documentation. Thank you.

**Comment by kowalczyka** [comment]
The guide for the azure integration can be found in: 
oscm-dev/-/blob/master/wiki/Technical%20Concepts/Azure%20Automation/powershell_azure_integration.docx
